### ISSUE TITLE
Error Code 52000

### ISSUE THREAD

**Issue by User51** [barronwaffles/dwc_network_server_emulator#100]
I got the Actiob Replay DS(i) code for pokemon platinum. This is my first time doing this. I typed in the code correctly and went to wfc erase configuration and then i made a new one and added the dns number and save the settings then went onto the game and went to gts and i keep getting error 52000 plz help me as fast as you can!!

**Comment by ghost** [comment]
platinum has given me problems in the past as well but with contacting ppl in the Wi-Fi room not connecting to Wi-Fi
