### ISSUE TITLE
[Question]How to give support to more games?

### ISSUE THREAD

**Issue by lordscales91** [barronwaffles/dwc_network_server_emulator#101]
I mean those games for which there isn't any packet data, is it possible to give support for them? It would be possible if I share the packets from the game, of course there will no response from the servers since they are already gone but, just with the client side packets could be enough or they are lost forever? More specifically the game that I have in mind is Monster Hunter Tri, right now I'm playing MH Portable 3rd with my brother thanks to the PPSSPP Emulator and the ProAdhocServer and we would like to play Tri too. The problem is that I think there is some game-specific logic like the player card (which is an item that identifies a player and show their stats), but maybe could be possible to play without that logic.

**Comment by mm201** [comment]
If you're good with ARM assembly, you can do it by inspecting the game in a debugger and seeing how it branches.

If the server logic is almost the same as what's already documented, you might get lucky by making small changes.

**Comment by lordscales91** [comment]
mmmh, so it's necessary to look at the assembly, it isn't enough with just the packet data. the only thing I did with assembly was look for strings in the 1st Project Diva PSP game to create a translation file for the [codestation's Diva Patch plugin](https://github.com/codestation/prxpatch/tree/master/divapatch) I don't have real knowledge of assembly, just learnt a few tricks with IDA Pro (it's a very good disassembler)

**Comment by mm201** [comment]
The only parts of the server which aren't already implemented are things which are specific to each individual game, so pretty much anything you can imagine is possible. You might get lucky and be able to guess the responses but it would be just that--luck.

**Comment by lordscales91** [comment]
That means that if the game doesn't have too much specific things it would possible to play it already? I'm going to test it right now, and let's see what happens

**Comment by mm201** [comment]
Also, we already have packet captures for some gamestats servers. All we need are programmers willing to figure out how they work and implement them.

**Comment by greysondn** [comment]
I wonder - do we really care how the missing server works so long as we match the public API?

I will stone cold open an decompiler and get to work on a couple games I love if you tell me the data on sent and expected structures is of some use to supporting a game or two.

**Comment by AdmiralCurtiss** [comment]
That is indeed the best way to go about it, now that the official servers no longer exist. If you feel up to the task go ahead, and maybe visit our IRC channel to discuss and share info.

**Comment by miguelcobain** [comment]
Related to the Monster Hunter Tri server, there was this project: https://github.com/sepalani/MH3SP

> If you want a local alternative you can try altwfc that now supports MHTri and others Wii games.

Side note: Monster Hunter Tri offered one of the best online experiences I've ever had. I was really sad when I found they have shut down the servers. I'm all in for a MH3 server.

**Comment by sepalani** [comment]
@miguelcobain 
As I said before, altwfc is an alternative to Nintendo servers not (Monster Hunter) Capcom ones.
