### ISSUE TITLE
Support from WBFS?

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#105]
I ripped all my games onto a WBFS disc, and is it possible (or going to be possible) to run the games from there? Some of my games I let others borrow/no longer have.

**Comment by ghost** [comment]
Already works. Sorry!

**Comment by kyle95wm** [comment]
Yes its possible if you have the latest USB Loader GX theres something called "private server" in the game load settings

**Comment by ghost** [comment]
Where is it? Can't find it, sorry.
