### ISSUE TITLE
(Pokémon BW/BW2) Is it possible to make the Random Matchup work?

### ISSUE THREAD

**Issue by RicoSantos** [barronwaffles/dwc_network_server_emulator#107]
Online battles are the main reason for many players, that's why I'm asking. Is there something specific that is needed to make the Random Matchup accessible? I mean, not just connect, but be able to find other players and battle against them.

**Comment by mm201** [comment]
It's supposed to work already. Pick a good date/time, hop on #altwfc, and we can troubleshoot.
