### ISSUE TITLE
Issue connecting following wiki guide

### ISSUE THREAD

**Issue by Anindir** [barronwaffles/dwc_network_server_emulator#110]
Okay so i have followed the guide exept for erasing the wfc connection info since none exists on my fresh game on desmemu. I have added the bios files and firmware compiled the 5102 revision from desmemu svn with wifi enabled and set dns manually to the ip stated on the wiki but it refuses to cooperate and let me connect. I have tried with both pokemon platinum and soulsilver.

Any idea what could be the issue or if i have forgotten something?

**Comment by AdmiralCurtiss** [comment]
Desmume has built-in protection against connecting to nintendowifi.net, you probably just ran into that.
