### ISSUE TITLE
problem nds without cwf code

### ISSUE THREAD

**Issue by GabrielCatDev** [barronwaffles/dwc_network_server_emulator#111]
My nds never connected on cwf and the code is missing....how i do???
[spanish]
Mi nds no se ha conectado a la cwf y el codigo cwf no lo tiene...que hago???

**Comment by GabrielCatDev** [comment]
why?? what are you doing closing if the problem is not solved yet!!!

**Comment by AdmiralCurtiss** [comment]
I don't understand what your problem is.

**Comment by GabrielCatDev** [comment]
No tengo codigo CWF y no me deja entrar...
[spanish]
