### ISSUE TITLE
Local Server Not Working

### ISSUE THREAD

**Issue by SecurityJon** [barronwaffles/dwc_network_server_emulator#112]
I posted this in IRC earlier but no-one was around. Any suggestions?

[12:28] <BTJ> Howdy. Anyone around/
[12:34] <BTJ> Ok if anyone knowledgable wakes up, my issue is this:
[12:34] <BTJ> Trying to run the server on my own kit.
[12:34] <BTJ> Downloaded, changed the IPs to match my local addresses
[12:35] <BTJ> Everything is being run locally on the same LAN at the moment BTW.
[12:35] <BTJ> dnsmasq has been updated to supply the correct IPs and seems to be working fine
[12:35] <BTJ> I'm trying to get a wii to connect to the server.
[12:35] <BTJ> Passes connection test with no issues
[12:36] <BTJ> I've patched Mario Kart with the noSSL stuff, which appears to have been successful
[12:36] <BTJ> I can see connections from my wii (Mario Kart) to the server, and have no errors.
[12:37] <BTJ> But the Wii just times out when attempoting to communicate with the Online Element, with error 61070
[12:37] <BTJ> Last mesage from the server is as follows
[12:37] <BTJ> [2015-02-21 12:21:47 | NasServer] {'locator': 'gamespy.com', 'token': 'NDSqymu43WVe0jdp2kGzaxiq4IVpZteNaj5HS5wi0TBHEEqglExwuGPAxxYqDTgeutaDxyxh8b9v7qxmJpd', 'retry': '0', 'returncd': '001', 'challenge': '4tSFbDuD', 'datetime': '20150221122147'}
[12:38] <BTJ> Anyone have any ideas how to troubleshoot? I see no errors in any logs at all.
[13:13] <BTJ> Just trired with the offical server after wiping out all of my save games - seems to work with no errors.
[13:19] <BTJ> Just repeated the same process with the internal server and getting 61070 again. Something is clearly screwy with the internal setup but how would I go about troubleshooting?

**Comment by mm201** [comment]
MKW uses the sake server. You need to run a web server/reverse proxy locally to forward traffic from `sake.gs.nintendowifi.net` and `*.sake.gs.nintendowifi.net` to `localhost:8000`.

**Comment by SecurityJon** [comment]
Many thanks, I'll give that a go tomorrow.

Are there any other gotchas like that for other games too?

**Comment by SecurityJon** [comment]
Nope still not working. Below is the config from my nginx server. I can see requests coming in, but I'm still getting a 61070.

server {
  listen 80;
  server_name nintendowifi.net *.nintendowifi.net;

  location / {
          # app1 reverse proxy follow
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://127.0.0.1:9000;
        }

}

server {
  listen 80;
  server_name sake.gs.nintendowifi.net *.sake.gs.nintendowifi.net;

  location / {
          # app2 reverse proxy settings follow
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://127.0.0.1:8000;
        }
}

**Comment by SecurityJon** [comment]
Checked the logs and I was getting an error about the whitelist table not existing. I'm guessing this should of been created in the database but wasn't. I've removed the offending code temporarily from gs_database.py

```
        #Check for console ban
#        with Transaction(self.conn) as tx:
#            row = tx.queryone("SELECT * FROM users WHERE userid = ? and gameid = ? and enabled = 0 "
#                "and gameid not in (select gameid from whitelist where gameid=? and macadr=?) limit 1"
#                ,(userid, gameid, gameid, macadr))
#            r = self.get_dict(row)
#        if r != None:
#            logger.log(logging.INFO, "--- REJECTING BANNED CONSOLE --- userid=%s,gameid=%s,macadr=%s", userid,gam$
#            return None
```

This hasn't fixed my issue but at least I'm not getting issues from the code anymore.

**Comment by kyle95wm** [comment]
ehhh why did you remove the white listing line in the script? Also I have a feeling you did something COMPLETELY wrong. Leave those IP addresses the port numbers alone in nas server and instead create virtual host files pointing to the various Nintendo addresses and activate them in Apache song with the proxy.load, proxy_http and proxy.conf (i believe) I don't remember exactly what the modules are called since Im too lazy to SSH into my own server. 

I have a very basic crash course on my channel on getting the server set up, but its really outdated and does not use Apache. Im considering re-making the tutorial some time this week if I have time

**Comment by SecurityJon** [comment]
The whitelisting was removed as a temporary fix to get around the errors I was seeing, once I have everything working I can look at putting it back but as this is only for an internal server it's not required for security.

I've created a nginx server for the reverse proxy element (config above) but happy to switch to Apache or whatever is easiest. I have a feeling I'm missing an entry which is stopping from getting this working, so if someone has a list of the hostnames to internal python servers that would be very useful

**Comment by kyle95wm** [comment]
hmm I am not familiar with nginx but I trust its the same thing pretty much? Ill have a newer video coming up showing how to do the server thing with Apache

**Comment by SecurityJon** [comment]
Its a reverse proxy, so essentially performing the same job yes.

If you've got a set of configs that work for Apache for games like Mario Kart Wii I can reverse engineer them to work out where I'm going wrong. Many thanks!

**Comment by kyle95wm** [comment]
https://github.com/BeanJr/dwc_network_server_emulator/blob/master/server-setup.sh

I just finished coding this a couple hours ago. The config files are in there too. I'd have to admit I'm not exactly a professional at she'll acripting but I'm sure most of it will work for anyone who runs it. I forgot the DNSMASQ stuff so I might add a commit later today

**Comment by SecurityJon** [comment]
Perfect! I'll give that a go later on, many thanks.

**Comment by SecurityJon** [comment]
I've not tried it yet, but I think you might have a typo in that script.

apt-get install apache python 2.7 python-twisted git -y >/dev/null

Apt will be looking for a package called "2.7" to install when I think you want python2.7

**Comment by kyle95wm** [comment]
At nice find! I was tired and threw it all together last minute. I hope my path syntax works out. I'll probably have to test this in a new VMWARE when I get a chance

**Comment by SecurityJon** [comment]
Aha! it _appears_ to be working now at least, I can connect in with a single player on MarioKart.

**Comment by kyle95wm** [comment]
So you mean to tell me my she'll script fixed everything? I feel so accomplished :p

**Comment by kyle95wm** [comment]
Okay looked like my script was sort of broken at the time. I've checked and tested it and everything worked 100% on Kali Linux
