### ISSUE TITLE
Kick support

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#115]
Okay so this may come as a bit of a complicated question but is it possible to add kicking support to the server? basically all we have to do is close a person's TCP connection which will kick them off. Is there a way to integrate this into the admin page or something? Perhaps something also could be set up to block all TCP connections from a specific IP for a set amount of time (temporary IP ban)

**Comment by AdmiralCurtiss** [comment]
This doesn't seem useful. All you'd be able to do is kick people from matchmaking. Once a connection between players is established, everything goes directly between those players; the server isn't contacted anymore.

**Comment by mm201** [comment]
Not entirely true. The game still sends heartbeats to the server, which is why 81010 happens when the server goes offline.

**Comment by kyle95wm** [comment]
This can be closed now since the server kicks banned players from the server
