### ISSUE TITLE
Forum? Community? 

### ISSUE THREAD

**Issue by Juxen** [barronwaffles/dwc_network_server_emulator#117]
Is there a forum for this server? i am really grateful for what you are doing, trying to keep the Online functions alive. Thanks a lot

**Comment by kyle95wm** [comment]
No we don't have a forum for the server.

**Comment by mm201** [comment]
We really should.

**Comment by JzargoTheMage** [comment]
I can set one up easily (really, anyone could if they wanted). The real question is if i have the permission to.

**Comment by kyle95wm** [comment]
Our server isn't popular enough to have a forum community. If we have problems/questions we typically post them all here

**Comment by kratoz29** [comment]
We should be more popular... people keep arguing that DS and Wii cannot be online.

**Comment by ghost** [comment]
well there's a chat group

**Comment by JzargoTheMage** [comment]
Yes, but a forum would retain the posts (I don't believe IRC shows messages from before you joined the room) and it would be more organized. The issue list here could be solely for issues then. Also, it would allow people to make communities for supported games that they wish to play, or submit idea suggestions for the actual programmers to try and consider. There may be a way to dump packet captures there as well under an error section for each game or application. It's just a thought.

**Comment by ghost** [comment]
hm... someone could make a xat chat to use as a forum

**Comment by kyle95wm** [comment]
how is that going to work?

**Comment by JzargoTheMage** [comment]
I'm not familiar with xat chat, but someone else here might or I could learn about it and figure it out.

**Comment by AdmiralCurtiss** [comment]
I don't really want to deal with it myself, but I'd be in favor of a forum. Would also help clean up this issue tracker, since what feels like 90% of the issues are just "help I can't connect to the server".

**Comment by JzargoTheMage** [comment]
As much as I love the project, I'm not really sure I check up on it enough to maintain the forum either, though I would love to. Would anyone else close to the project mind?

**Comment by polaris-** [comment]
I'm not against the idea but I don't really have any time or energy to work on the server anymore so I probably wouldn't look at the forums much at all, so that counts me out as well.

**Comment by polaris-** [comment]
Fat fingers. Ignore the closed thing. :P

**Comment by TDoomX** [comment]
I've made a xat to talk better, check:

http://xat.com/PolarisDSWiiServer

My issue: #233
