### ISSUE TITLE
Phantasy Start Zero gives 52200 error when reconnecting.

### ISSUE THREAD

**Issue by Repflez** [barronwaffles/dwc_network_server_emulator#119]
I tried Phantasy Start Zero online, so far I made a Solo party and it seems to work fine. The issue seems that I get a 52200 error when reconnecting. Does the game do something at disconnect that ends giving the error when reconnecting? I can test further if required.

**Comment by mm201** [comment]
Sounds like https://github.com/polaris-/dwc_network_server_emulator/issues/30

**Comment by the2anoni** [comment]
My solution is restart the game and then reconnect (works on dsi with acekard 2i).
