### ISSUE TITLE
Can we made Dsi games patcher ?

### ISSUE THREAD

**Issue by the2anoni** [barronwaffles/dwc_network_server_emulator#120]
The question is in the topic.
Ps.If you want dump the dsi game just copy it on sd card and insert it to pc go to private ->Ds -> title and copy all files to computer.But i can't open .bin file.

**Comment by einstein95** [comment]
What's the point of patching DSi games when there's no way to play them
after patching it?

**Comment by the2anoni** [comment]
I don't understeand the question 
Ps.Sorry for my english i'm from poland

**Comment by einstein95** [comment]
If we dump the DSiWare from the DSi and patch it, how could we play it
afterwards?

**Comment by the2anoni** [comment]
We can replace original to dumped

**Comment by einstein95** [comment]
But to patch it after dumping it from the DSi, we need to decrypt it. How
are we going to encrypt it and then import it back, which you can't do on
latest firmware.

**Comment by the2anoni** [comment]
But I'm have dsi with 1.4.4.

**Comment by einstein95** [comment]
Then find a way to re-encrypt a DSi game then and maybe it'd be feasible.

**Comment by the2anoni** [comment]
but i'm not a dev.

**Comment by AdmiralCurtiss** [comment]
Not directly related to this server, and unfeasible with the current knowledge of DSi games as far as I can tell.

**Comment by the4anoni** [comment]
We did some cfw dsi progress. Reopen ?
