### ISSUE TITLE
Connect problem with Wii

### ISSUE THREAD

**Issue by PhynixP** [barronwaffles/dwc_network_server_emulator#121]
Hello i have installed the DWC Server on my Ubuntu Laptop for any tests.
When i start the server, i can connect from my handy to the port 9001 and 9009/ban...
from the Laptop too.
i dnsmasq i type my forwarted router ip 77.20.XXX.XXX
forwarded to 192.168.1.248 = my DWC Emu.

In my Wii i type the ip 77.20.XXX.XXX in the dns settings
The Error is 51200
When i type 192.168.1.248 in the wii , i became the same error code.

ps. When i type in my Phone nas.nintendowifi.net with the port 9001i can see the gamestats.

but why i can't connect with my wii to the server ?

**Comment by kyle95wm** [comment]
One thing that made me think was, is your VM on the same network/subnet as your Wii?

I know for a fact that some VM software create their own "network" but share the host's internet connection but the addressing is different but from what I remember you're using a Raspberry Pi so thats not the problem. The problem more than likely relies on either the way your Pi is set up, or something on your network isn't letting things pass through like they should be

Without knowing specific details nobody here can help

**Comment by PhynixP** [comment]
Hello Thanks for help,
My first question ist wrong
my active problem is follow one:

when i type on my laptop with started DWC_server : ping nintendowifi.net it works fine i became the ip from dnsmasq (77.20.XXX.XXX)

But when i type the same on my 2. PC or Phone , i became not a ping info.

Its means, local it works fine but, on a 2. PC ist dont work.
I have type on my 2. PC in the DNS Settings the ip from my Server Laptop (192.168.1.248)

**Comment by PhynixP** [comment]
Hello I have an update:
my  pc's now gives me with a ping the right address when i type ping nintento.wifi.net
but on the wii it doesn't work :(

my config:
dnsmasq
address=/nintendowifi.net/192.168.1.248
listen-address=127.0.0.1
listen-address=192.168.1.248

my hosts
127.0.0.1 localhost
192.168.1.1        myrouter
192.168.1.248    serveremu
192.168.1.47      wii
192.168.1.50      desktop
more i haven't changed

My Router (Fritzbox) have 192.168.1.1

my Wii config, 
ip  192.168.1.47
submask 255.255.255.0
gateway:192.168.1.1
dns: 192.168.1.248

my other pc's have the same config
example: destop
IP: 192.168.1.50
Mask : 255.255.255.0
Gateway: 192.168.1.1
dns: 192.168.1.248

My Server Laptop
IP:192.168.1.248
Mask: 255.255.255.0
Gateway : 192.168.1.1
dns: 192.168.1.1

Have you any ideas ?

**Comment by kyle95wm** [comment]
Something is clearly wrong because this shouldn't happen. The only line I added to my config file was the address= line and nothing else. I suggest asking either @smtddr or @mmc21 as they've been incredibly helpful to me when I was facing the exact same problem. Just make sure your DNS server is running and that your web server is also running along with your master server python file

**Comment by kyle95wm** [comment]
I've recently updated the script on my fork that adds a few extra things and fixes some common issues. Feel free to have a look

**Comment by PhynixP** [comment]
Thanks for your Help.
I will test the the New direct.
I give you info
Am 15.04.2015 21:22 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by PhynixP** [comment]
Hello i have found an issue in line 58 and 67
is works with this code:

if [ $? != "0" ] ; then
    echo "Oops! Something went wrong here!"
else
    echo "It worked!"
fi
sleep 5s
clear
echo "Now lets enable some modules so we can make all of this work..."
a2enmod $mod1 $mod2
if [ $? != "0" ] ; then

**Comment by kyle95wm** [comment]
Sorry I didn't have time to fully check the script. I'll fix this whenever I can

**Comment by kyle95wm** [comment]
Found the problem. I fixed it and ran it through shellcgeck 's website. It should work now.

**Comment by PhynixP** [comment]
Thanks you for this all.
I waite and will test is for you
Am 15.04.2015 22:18 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by PhynixP** [comment]
Hello , the Setup works very fine
The Server works 100% i can connect With the wii on the server.
And the Gameboy search for other Games

But one issue i have Found in the Setup Script.
The sites in the Folder etc/apache2/site-enable must endlich of .conf

Then the Script enabled the sites

Thanks you for your help
If you  i can write a tut to install the server in german
Am 15.04.2015 22:21 schrieb "PhyniX PHX" phynixp@gmail.com:

**Comment by kyle95wm** [comment]
so for example "gamestats2.gs.nintendowifi.net.conf"? Okay I'll defiantly keep that in mind but I haven't had to do that part before

**Comment by PhynixP** [comment]
Yes,  xxx.nintendowifi.net.conf is right.
So it Works perfekt by me.
Tomorow i will test it on my Raspbian

Am 16.04.2015 00:33 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by kyle95wm** [comment]
Let me know how that pans out. In case you were wondering I recently updated the wiki page on the installation steps and included a manual way of doing it

**Comment by PhynixP** [comment]
Ok thanks for the Info
Nice Chance express install and the Menü install
I make my bananapi and rpi ready for test it.
Am 16.04.2015 02:42 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by PhynixP** [comment]
Hey,
I have installed on my bananapi
It works out of the Box perfect

Have got an idea to diasable the Whitelist ?
Am 16.04.2015 09:53 schrieb "PhyniX PHX" phynixp@gmail.com:

**Comment by kyle95wm** [comment]
To be honest, disabling the white list is a little tricky because it involves editing at least 3 files and then deleting the gpcm database file and then restarting master

**Comment by PhynixP** [comment]
i thought so
I think a blacklist is enough
let's see if I can do that disable the whitelist

**Comment by kyle95wm** [comment]
Might I suggest going to SMTDDR's fork and looking up that commit for white listing as this will point you in the right direction to properly removing it

**Comment by PhynixP** [comment]
Thanks it Works fine.
With any more Chance
Am 17.04.2015 10:43 schrieb "Kyle Warwick-Mathieu" <notifications@github.com
