### ISSUE TITLE
Pokémon White 2 Mystery Gifts broken

### ISSUE THREAD

**Issue by AriaRigga** [barronwaffles/dwc_network_server_emulator#129]
Newbie here. I cant find any mystery gifts for my pokemon white 2. I followed your procedure. But i cant find that DLC folder in the repository youre saying. Where can i find it?

**Comment by AriaRigga** [comment]
Ok. I already located the folder. Now, i do not know what year am i going to set to my DS? Is it the current year 2015? I still cannot receive any gifts tho

**Comment by AdmiralCurtiss** [comment]
What language is your game? Currently only English and French works for Pokémon Black/White/2.

**Comment by AriaRigga** [comment]
Im using the english one. i already received gifts from pokemon black 2. but it stopped this April. I got the last gift on March. since then, it always says "there were no gifts to be found. please help. :(

**Comment by AriaRigga** [comment]
Somebody?

**Comment by AdmiralCurtiss** [comment]
Be patient, I'll look into it when I have the time.

**Comment by AriaRigga** [comment]
Thank you. :)

**Comment by AdmiralCurtiss** [comment]
Note to self: May be related to 36dc3af1ebb8fd779b0c6544f3a46f5a7fe64184

**Comment by AdmiralCurtiss** [comment]
Yeah something is broken here.

**Comment by AriaRigga** [comment]
I know you can do it mr.curtiss :)

**Comment by AriaRigga** [comment]
Huh? Fixed? But sir, i still dont get any gifts from my white and black 2 game. :(

**Comment by AdmiralCurtiss** [comment]
Fixed in the repository, code will go live to the official server whenever someone updates that next. I don't have access so I can't tell you when that'll happen.

**Comment by AriaRigga** [comment]
Ok.. Thank you sir. :)
