### ISSUE TITLE
Custom error codes

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#138]
I wonder if its possible to return certain error codes to a console like when it's banned because right now it will take up to a minute and a half to display 61070 which means the connection was timed out

**Comment by AdmiralCurtiss** [comment]
If someone knows how to force error codes to display, sure.

**Comment by AdmiralCurtiss** [comment]
0d7ba68a3b43974bf433ba00cab0a47a0645df2e Not exactly a custom error code but it at least errors out fast.

**Comment by Leseratte10** [comment]
@AdmiralCurtiss : You can force the console to display error 23XXX by having the nas.nintendowifi.net server return HTTP response code XXX. You can force the console to display error 20XXX by setting "returncd" in the nas answer to XXX (XXX > 100).

**Comment by kyle95wm** [comment]
@Leseratte10 I was not expecting to hear from you on here. Sounds very interesting but hardly have any experience with this sort of error return. I suppose its worth looking into

**Comment by AdmiralCurtiss** [comment]
Thanks, that's very useful information. I'll change the returned error code for bans to 23912 to be consistent with http://wiimmfi.de/error.

**Comment by AdmiralCurtiss** [comment]
Well I can't actually get the HTTP response code thing to work, but setting the returncd to 3912 does lead to error code 23912 so that works, I suppose.

**Comment by kyle95wm** [comment]
I saw your commit and I'd have to say you did a good job. However error code 61020 still has meaning if you will. I banned myself and attempted to create a new profile and got 61020 so Im guessing that error code can be changed to whatever I want? Say, 23911 or maybe 23914?
