### ISSUE TITLE
black 2 problem

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#139]
theres a problem with my black 2 it wont connect to the server i set up everything right for it to connect to the server  but it keeps getting error 20100  which is strange because soul silver connects perfectly I set up another connection using pokegts's server to see if they some how are making it work once I found out from experience that its  shot and is not part of one of the new servers(they should just take their site down) I erased my old Wi-Fi connection settings and set up a new one using only this server but black 2 still wont connect to it even though soul silver will which is strange I need help getting black 2 to connect again

**Comment by AdmiralCurtiss** [comment]
You didn't specify which function but the basic Wi-Fi Club connecting seems to work. Dunno if other things like GTS do but they're not part of this server, they're part of https://github.com/mm201/pkmnFoundations

**Comment by ghost** [comment]
it works now but It wasn't before
