### ISSUE TITLE
Auto start master?

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#140]
Okay so allow me to explain.

Basically I have a Raspberry Pi set up to run the server but I only use that Pi for the server so if the power fails I don't want to have to restart the master server manually. Believe me when I say this but I tried everything from a shell script to editing rc.local to indicate that it is to start a python script but nothing works. I can't get any output (tried redirecting it to a file) but get absolutely nothing and I don't see anything under sudo lsof -i :9000 like I should be seeing. I also can't connect to the DWC server using this method. If anyone can come up with anything that works I'd appreciate it.

**Comment by AdmiralCurtiss** [comment]
Not exactly related to this server.
http://www.instructables.com/id/Raspberry-Pi-Launch-Python-script-on-startup/?ALLSTEPS

**Comment by kyle95wm** [comment]
Thanks a lot for that link. Now I can have the confidence of knowing master always starts on boot. I might actually include this in the bash script as a "question" however removing a crontab is a little beyond my scope atm
