### ISSUE TITLE
is the server down for ds games

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#141]
none of my ds games have been able to connect to the server for the last 2 days however, brawl can but it takes longer than usual

**Comment by kyle95wm** [comment]
Might I suggest using any of the alternative servers located in the Wiki page for List of Servers?

**Comment by ghost** [comment]
i tried that and the strangest thing happened  I got communication error ... it didn't even give a code number  and with the regular server I get error code 52100

**Comment by kyle95wm** [comment]
Seems this is happening with one of my subscribers on YouTUbe as well

**Comment by ghost** [comment]
so I hope the regular server comes back soon  but whats very strange is that  the ds games were the only ones that couldn't connect at all  brawl could it just took a lot longer to than usual

**Comment by kyle95wm** [comment]
The only change to my knowledge was that the apache virtual host files were renamed but that shouldn't change anything. I've had several people connect to my server with Pokemon games and MKDS so I assume all is fine

**Comment by ghost** [comment]
then why am I getting this error code when I try to

**Comment by kyle95wm** [comment]
Maybe it's a problem with your ROM.

**Comment by ghost** [comment]
im using a legit cartridge

**Comment by kyle95wm** [comment]
I'm afraid I can't really help with DS games. Perhaps it's worth waiting for someone who knows and could possibly help

**Comment by ghost** [comment]
now I get error 20100 so the game is either trying to connect to the dead servers (which makes no sense) or the server is down and if that's so I hope it gets back up soon

**Comment by kyle95wm** [comment]
You even tried my server for instance? Remember to set the DNS to 99.238.211.192 and see what you get. You must be running the ALTWFC patch for it to work

**Comment by ghost** [comment]
yeah that's the one that gave me that mysterious communication error with no error code

**Comment by kyle95wm** [comment]
Interesting. Theres nothing wrong over here.... although I do admit I don't have a DS to test with

**Comment by ghost** [comment]
well my platinum gets error 20100 and my white version can connect to the gts with no problem so idk whats wrong with platinum

**Comment by mm201** [comment]
Sounds like your ROM patcher isn't working.

**Comment by ghost** [comment]
strange because it's worked in the past and I haven't changed the code

**Comment by EduardoBJP** [comment]
I also have this problem - just to elaborate, I was able to connect once to GTS with main server yesterday (29/04). Since then ip hasn't been reachable (maintenance?) when I tried to connect with alternate servers i got a strange error without error code. Today i got one 61070 and deleted my wifi configuration. The got some 20100 (platinum) or the error message without code - on pearl i only get the error message without code.

**Comment by kyle95wm** [comment]
My server was actually offline the entire night (my internet crashed) but why you couldn't connect on my server (BeanJr-Fi) is baffling

**Comment by ghost** [comment]
very strange its as if the game didn't know  what was wrong it just knew something was wrong  and cut off the connection

**Comment by kyle95wm** [comment]
61070 usually means that the login server can't be reached (maybe it got stuck) or on some servers it means you're banned (assuming that the main server is running the new error code patch) but 61020 means you're banned on new servers and will pop up in a split second

**Comment by EduardoBJP** [comment]
I only got that one once. afterwards i got the usual error without code. So i guess it was just momentary. I also was not able to connect with white, error 13724 - i am using a flashcart - will try different rom / patcher version configurations tomorrow.

**Comment by EduardoBJP** [comment]
Something really weird is going on. I can connect without issues on 104.131.93.87. Get the error without code on alternate server.
