### ISSUE TITLE
error 52231 when typing in the dns of my own local server!

### ISSUE THREAD

**Issue by BadBreath69** [barronwaffles/dwc_network_server_emulator#142]
i type in my ip in the dns settings, it does a connection test, test fails, error 52231, if i try any other dns it works, even the public testing server works.
sorry for my english im dutch.

**Comment by AdmiralCurtiss** [comment]
Can't say I've seen that error code before. Are you sure you followed the install instructions correctly?

**Comment by BadBreath69** [comment]
i have used the auto installer.

**Comment by BadBreath69** [comment]
note: im using a raspberry pi 2, running raspbian

**Comment by kyle95wm** [comment]
It should've worked. That script was ran like 5 times on a Pi and several times on Ubntu

**Comment by BadBreath69** [comment]
sooo, how do i fix this ?

**Comment by ghost** [comment]
5223X - Problem with your router-firewall (ports), check if you can access the port :P

**Comment by BadBreath69** [comment]
it does not work on my rpi, but i tested it on a ubuntu virtual machine aaaaannnnddd it works. :/
