### ISSUE TITLE
Error 23913 and 20100 on LAN server

### ISSUE THREAD

**Issue by Dr-Wily** [barronwaffles/dwc_network_server_emulator#146]
OK, I installed the server from script on a fresh Debian 8 install. My purpose is to setup a LAN of Mario Kart Wii without internet connection.

Server is 192.168.0.144
Wii obtain IP automaticaly and their DNS is setup manualy to 192.168.0.144

I use USB Loader GX with the on the fly patch (no SSL or Wimmfi.de)

The results (on both Wii there no mario kart savegame) :
- First Wii : network connection setup and test is OK with DNS set to 192.168.0.144
  ---> running Mario Kart from USB Loader GX with following options :
  ----> patch No SSL : connection error 20100
  ----> patch wimmfi.de : connection OK I can waiting for other players
- second Wii : network connection setup in the same way and test through Wifi and cable
  ---> running Mario Kart from USB Loader GX with following options :
  ----> patch No SSL : connection error 20100
  ----> patch wimmfi.de : error 23913 (console baned ?)

Why noSSL is not working ? And why wimmfi.de works on my server ? How is possible that one of my Wii is banned ? My server is totaly new and this Wii nerver connect on it before ?

EDIT : strange things... the connection test on wii succed even if my server is off, how is possible when the dns leads to my server ?

EDIT 2 : OK when I unplug my internet connection , I have an error 51421 on Wii's connection test even if I set the DNS to my local server... How the wii can bypass the DNS ? Should I change the gateway to ?

**Comment by kyle95wm** [comment]
Error codes like 23913 are tracked by IP address. The reason you got 23913 is because you added too many consoles at once. In my opinion this new limitation on wiimmfi is rediculous

As to why the wiis are unable to connect to your server is a mystory. Are you running the latest version of the script? Were there any errors in the script to do with Apache or DNSMASQ?

**Comment by Dr-Wily** [comment]
OK I manage to connect two Wii, create a room and launch a game. The odd thing is about the DNS setup on the Wii. When I put the server emulator's IP, sometime the connection test don't takes it. It performs the connection test on Nintendo's server... and a successfull connection gives a diferent service code depending on whether the Wii connects to my server or the Nintendo's server.

A succesfull connection on the server emulator gives 21212. A conenction to Nintendo server gives 31212.

Example : 
- First, I setup the DNS of the Wii to look at the the server emulator's IP --> connection test is OK and give 21212 and the server emulator detect the connection. It's OK.
- after, on the same connection, I change the Wii's DNS to auto, the connection test look at Nintendo's server and gives 31212. It's OK as well.
- finaly, always on the same connection, I change again the Wii's DNS and enter server emulator's IP. ---> connection test OK but with code 31212. Wii performs connection test on Nintendo servers instead of server emulator.

I think, this is a DHCP cache lease issue. When I shut down the Wii (unplug power cord)  and restart the connection test, it's works with code (21212) and the uses the server emulator. I don't know if it comes from my network setup or how the Wii manage the release/renew of his IP parameters.

**Comment by kyle95wm** [comment]
It sounds like a DNS cache issue to me. I honestly don't know why its doing that. The important thing is your Wii's can (sometimes) connect to the server. If you leave your DNS set to your server you can even go on Wiimm-Fi with it still set to your custom server's DNS as if it was set to auto obtain

**Comment by Dr-Wily** [comment]
OK thanks. the shutdown of the Wii fix the DNS issue. The NoSSL patch works and I am able to join and play with two Wii (one wirered and one wireless). (big test with 12 Wii soon)

I notice the is a keepalive option on the server who kick when there is "no" activity. Is there a way tu customize this ? This issue can be closed.

**Comment by kyle95wm** [comment]
Not sure if it can be customized but I was hoping that the keep alive requests can be manipulated to drop a player's connection from the server but that seems impossible right now

**Comment by AdmiralCurtiss** [comment]
The disconnect-on-lack-of-activity is probably actually handled client-side.
