### ISSUE TITLE
error 61070 

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#147]
is my 3ds/pokemon platinum banned I don't see why that would be since im connecting to the main server which last time I checked has no rules  if it had rules that would lead to banning and were breaking them i'd ask what rule ive  broken but the main server has no rules so if im banned on my platinum version why am I and if not why am I getting this error

**Comment by mm201** [comment]
The pokemon server restarted recently. I'll go check that everything's okay when I get home in a couple hours.

**Comment by kyle95wm** [comment]
May I ask what error you were getting? Http://beanjr.hopto.org/error

**Comment by kyle95wm** [comment]
also 61070 now means the login server is un-reachable but could also mean your profile is banned (the owner of ALTWFC - the main server hardly ever goes and bans players) however if you're referring to getting 61070 on my server then there is a real problem with the server itself and must be restarted

**Comment by AdmiralCurtiss** [comment]
61070 just means the profile server isn't reachable. Almost certainly not your fault.
