### ISSUE TITLE
Server error while connecting to my custom Server

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#148]
Hi, 
I am trying to set up my own custom server.  When I try to connect my DS shows the error _20101: either the server is experiencing high traffic or nwc service is down_

The server also throws an error. here is the stack trace: 

> 127.0.0.1 - - [02/May/2015 18:25:00] "GET / HTTP/1.1" 200 -
> [2015-05-02 18:25:00 | GameSpyQRServer] [79.226.44.95:1626] Received availability request for 'mprimeds' from 79.226.44.95:1626...
> [2015-05-02 18:25:01 | NasServer] Request to /ac from ('127.0.0.1', 38691)
> [2015-05-02 18:25:01 | NasServer] {'lang': '03', 'gamecd': 'AMHE', 'makercd': '01', 'unitcd': '0', 'bssid': '001c4a034550', 'passwd': '173', 'devname': '"!', 'userid': '6222676787365', 'gsbrcd': 'AMHE3sg304q', 'apinfo': '00:0000000-00', 'ingamesn': 'D\x00a\x00l\x00l\x00e\x00', 'devtime': '120502172130', 'birth': '020c', 'action': 'login', 'macadr': '0022d73c83c7', 'sdkver': '001000'}
> 127.0.0.1 - - [02/May/2015 18:25:01] "POST /ac HTTP/1.1" 200 -
> [2015-05-02 18:25:01 | GamespyDatabase] [dYC7CLEC] STARTING: SELECT enabled FROM users WHERE userid = 6222676787365 AND gsbrcd = AMHE3sg304q
> [2015-05-02 18:25:01 | GamespyDatabase] [dYC7CLEC] DONE: Took 0.00101089477539 real time / 0.000911 processor time
> [2015-05-02 18:25:01 | NasServer] Unknown exception: Traceback (most recent call last):
>  File "/root/dwc_network_server_emulator/nas_server.py", line 116, in do_POST
>    if self.server.db.check_user_enabled(post["userid"], post["gsbrcd"]):
> File "/root/dwc_network_server_emulator/gamespy/gs_database.py", line 176, in check_user_enabled
>    enabled = int(row[0])
> TypeError: 'NoneType' object has no attribute '**getitem**'

I used the installer script on both my Raspberry PI (Model B) and my 1&1 Server, but I get the same errors on both. 

Is there a way to get around this? 

Thanks!

**Comment by AdmiralCurtiss** [comment]
Oh ha, did I break new account creation with my last commit? Sorry, gimme a sec and I'll fix it.

**Comment by AdmiralCurtiss** [comment]
There, that should fix it. Run a `git pull`, restart the server, and try again.

**Comment by ghost** [comment]
Wow that was fast. Thank you!
