### ISSUE TITLE
nas server broken......

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#149]
[2015-05-02 20:01:44 | NasServer] Unknown exception: Traceback (most recent call last):
  File "/home/pi/dwc_network_server_emulator/nas_server.py", line 291, in do_POST
    self.send_header("Content-Length", str(len(ret)))
UnboundLocalError: local variable 'ret' referenced before assignment

Here's my nas_server file for anyone wondering

http://pastebin.com/EV8PMxrL

**Comment by AdmiralCurtiss** [comment]
It looks like this would happen if the requested path is none of /ac, /pr, and /download. What is the request?

**Comment by kyle95wm** [comment]
Okay I think I figured out the problem but sadly it can't be fixed with my required setup. Basically I was running the nas server off port 80 at the time and thats when that error happened. 

"Why are you running off port 80? You have a web server for gods sake" well that may be true yes, but running it off port 9000 with 127.0.0.1 instead of 80 with 0.0.0.0 doesn't give me the IP of the user logging in (me and @SMTDDR are looking to ban IP's+gameID from the server since anything else is just impossible to code in) but Im running on port 9000 again due to complication in the friend adding on Mario Kart Wii not working otherwise.

That's really all I can think of for the time being since the error no longer appears

**Comment by mm201** [comment]
It should really return 404 in that case anyway.

**Comment by AdmiralCurtiss** [comment]
Yeah it probably should, but that won't help this guy, I don't even see how this error is affecting anything.

**Comment by kyle95wm** [comment]
Might as well close this (it was just my temporary setup causing problems)

**Comment by AdmiralCurtiss** [comment]
relevant: 9bf49b8c67584d09903baa13b11269b2901e0c9d
