### ISSUE TITLE
Feature request : Mario Kart Wii Online Player List

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#159]
At the moment the AltWfc stats give minimal information, for games like Mario Kart Wii a better player list is welcome like in Wiimmfi : http://wiimmfi.de/mkw

**Comment by kyle95wm** [comment]
I have a feeling a lot more work will need to go into this like for instance one would need a copy of mkw-ana running on the server to catch all packets from the server and make a player list out of it. This would be really useful when reporting jackets to ALTWFC admins of any ALTWFC server running this new stats system

**Comment by mm201** [comment]
`mkw-ana` concerns itself with monitoring client-client communications which never hit our server. (Although we could do some interesting things with it if we had a bot spectate each race.) The information wiimmfi displays is all sent to `qr` or `profile`.

**Comment by kyle95wm** [comment]
Ah I get it. The profile server also shows VR/BR but not friend codes afaik

**Comment by mm201** [comment]
Friend codes are just profile IDs (`pid`s) put through some obfuscation formula.

**Comment by kyle95wm** [comment]
ah okay. Im looking forward to seeing something like this on ALTWFC

**Comment by DarthMDev** [comment]
Any updates on this?
