### ISSUE TITLE
Mario Kart DS / Disconnect Problem

### ISSUE THREAD

**Issue by DevEkode** [barronwaffles/dwc_network_server_emulator#161]
Hey everyone !

Today I wanted to play MKDS with my friend but I had a disconnecting problem :
When I start a race the connection simply break down :(

NB : I took a screenshot when the party break
link : http://puu.sh/hFXqd/7c817dcc82.PNG

**Comment by AdmiralCurtiss** [comment]
Desmume does not support Mario Kart DS online play. Report this problem to the Desmume developers instead.

**Comment by DevEkode** [comment]
ok thx

**Comment by kyle95wm** [comment]
We actually plan on banning DeSemue from connecting to the server at all
