### ISSUE TITLE
Matchmaking issues with some Pokémon games/features

### ISSUE THREAD

**Issue by mm201** [barronwaffles/dwc_network_server_emulator#162]
When players try to use the Random Matchup, or (presumably) GTS Negotiations, other players never connect. I'll try to get you packet captures tonight.

**Comment by ghost** [comment]
I was wrong

**Comment by mm201** [comment]
No it's not. I'm running a peerchat and it's working normally. GenV doesn't even use peerchat. It's a matchmaking issue.

**Comment by ghost** [comment]
Does your peerchat server have the stuff for Gen IV's WiFi Plaza stuff (/GETCHANKEY etc)

**Comment by mm201** [comment]
Platinum Wi-Fi Plaza is a different issue (/getchankey in the ircd). I've removed it from the description.

**Comment by ketsuban** [comment]
What's the status of this?
