### ISSUE TITLE
Bypass HTTPS code for NTR-CPUP_EUR

### ISSUE THREAD

**Issue by Maganet** [barronwaffles/dwc_network_server_emulator#163]
I know Ill probably wont get an answer, but what is the code for EU Platinum? When I try to get my code from an EU rom using Wfcreplay, it gives me the US code instead. Also can you get the code from a physical copy of the game?

**Comment by einstein95** [comment]
If you get the same code, then that just means that the code is the same.
It doesn't have a database or anything to look up. You can only get the
code from a physical copy if you dump it yourself.

**Comment by Maganet** [comment]
And how do you dumb a phycical copy or the game?

**Comment by TheSonAlsoRises** [comment]
Read this: https://gbatemp.net/threads/how-to-dump-your-own-3ds-ds-games-saves.274290/#entry3399726

**Comment by Maganet** [comment]
Do I have to do all Wifi, Slot-2 and Hardware to dump my game or just one of them? Also I have a DSi XL and 3DS XL so Ill probablly wont be able to dump my game.

**Comment by TheSonAlsoRises** [comment]
Use one of the solutions, obviously. This cannot be done without extra hardware.
