### ISSUE TITLE
Fix natneg

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#169]
If natneg can be fixed, then we can have a playable server.

I remember there was conversation going on in IRC about this but not sure where it was left

**Comment by polaris-** [comment]
It left off at me saying "someone fix natneg".

Someone fix natneg. :P
The code here can be used to fill in some blanks that were unknown when I wrote natneg: https://github.com/nitrocaster/GameSpy/tree/master/natneg

**Comment by kyle95wm** [comment]
@AdmiralCurtiss ? @ToadKing ?
