### ISSUE TITLE
Change Database engine

### ISSUE THREAD

**Issue by Dr-Wily** [barronwaffles/dwc_network_server_emulator#170]
I notice that dwc network server emulator uses SQL lite with no database engine. I wonder if it would be better to use real database engine. MySQL, Postgres or whatever... 

First, I think existing access with SQL lite is not reliable when the server hosts many connections. I feel there is some data corrupted or lost when there is multiples access to database file. Plus, it would be easier to manage database and profiles.

It would change the way python connects to database. Do you think this is possible ?

**Comment by kyle95wm** [comment]
Wouldn't the statements have to change?

**Comment by Dr-Wily** [comment]
Install MySQL+phpmyadmin. Change the way python connects to the database (if this is the python script that read the database). add a db connection string or create a function to connect to the database engine. And create database.
