### ISSUE TITLE
DLC Server

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#175]
Hi,
Is there a way to run just the DLC (Mystery Gift) server? If so:
- What python script(s) do I run?
- How can I make it pick a myg file corresponding to the date etc '160615.myg' for today, '170615.myg' for tomorrow (IK how to make an MYG)
- Which exact DNS domains are the Mystery Gift ones?

**Comment by AdmiralCurtiss** [comment]
The DLC server is part of `nas_server.py` at the moment, so I don't think you can just run that. If you want to separate it out feel free though!

The date stuff is pretty rudimentary at the moment, Jan 1st returns the first file in _list.txt, Jan 2nd the second, etc, and it rotates back to the first file once it reaches the end.

Mystery Gift runs over the bog-standard DLC servers, so `dls1.nintendowifi.net` on the official servers, or more specifically whatever is returned here: https://github.com/polaris-/dwc_network_server_emulator/blob/master/nas_server.py#L162

**Comment by ghost** [comment]
Thanks, I've decided that instead of ripping out the DLS1 server to just keep it in there and just virtualhost it only for dls1.
Thanks @AdmiralCurtiss 
--Poke
