### ISSUE TITLE
Running AltWFC on Windows

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#176]
Hi,
is there a way to run AltWFC on Windows? I have a spare windows server 2012 machine lying around..

**Comment by kyle95wm** [comment]
For starters, I think if you can get a nintendowifi.net lookup zone created in your DNS server role that's a start. Getting Python 2 on Windows should be relatively easy but maybe that's the same for Twisted. I'm not sure how WAMP if configured to use the virtual hosts but at least this is a start

Someone should add a Windows guide to the wiki if they've had any success.

**Comment by ghost** [comment]
I've already got DNS setup.
I'll be trying later tomorrow, post any findings here!

**Comment by mm201** [comment]
I have it working on Windows. You basically just add a few DNS entries, open ports, and set up ARR reverse proxying in IIS.

**Comment by kyle95wm** [comment]
Can you please add a guide to the wiki?

**Comment by celorodovalho** [comment]
+1

**Comment by ghost** [comment]
Why don't you add one yourself, if required so much? :wink:
