### ISSUE TITLE
Is server on?

### ISSUE THREAD

**Issue by DouglasMartins1999** [barronwaffles/dwc_network_server_emulator#177]
Hello. In a few weeks ago I was connecting very well in this server (Original AltWfc) with my Nintendo DS Lite and a Acekard with Pokémon (Diamond, Platinum and Black 2) and Mario Kart. I was using wifi hotspot from my LG L3 smartphone to connect. All my games was patched. And now, when I tried to connect via router (Cisco E1000 - WEP - 802.11b) I was unable to acess. Firstly I succeeded connect, but when I tried to enter in GTS or others functions I get the mensage "The nintendo wi-fi connection for this software was disabled...". I put correctly the DNS in both: Primary and Secondary. And now, I'm not able to connecting in NWFC Setup, sometimes I get the error 20100 or 20110. I already try set WiFi security to open, use WfcReplay instead of WfcPatcher and nothing occured. It is a server problem or no?

**Comment by kyle95wm** [comment]
Which servers have you tried? There are currently three servers hosted by 3 different people (myself included)

**Comment by mm201** [comment]
I can't think of any way you'd get that error unless your DS is trying to connect to the official server.

And you should be using the main server if you're not already.

**Comment by DouglasMartins1999** [comment]
I tell before... I'm using original altwfc (104.131.93.87). I already tried others, I get same error...
Today I'll try again with my smartphone and see if it works. If work, is problem in my router...

**Comment by DouglasMartins1999** [comment]
My smartphone isn't work right now. I tried again with my router. In Pokémon Platinum I get error 20110 with server official. In Pokémon Black I get error 20100 with three servers. Pokémon Platinum I used before with my LG L3. Pokémon Black I patched yesterday.

I don't know if it'll help. Anyway, is here some prints.
![cam00394 1](https://cloud.githubusercontent.com/assets/13039437/8355590/82d961d8-1b26-11e5-987d-58f5d5229a73.jpg)
![cam00389 1](https://cloud.githubusercontent.com/assets/13039437/8355588/82d82c82-1b26-11e5-8660-6ae4487c9f61.jpg)
![cam00390 1](https://cloud.githubusercontent.com/assets/13039437/8355587/82d5fb60-1b26-11e5-95a3-adf6e2305407.jpg)
![cam00391 1](https://cloud.githubusercontent.com/assets/13039437/8355589/82d8b706-1b26-11e5-8bdc-e889a1f9112b.jpg)
![cam00392 1](https://cloud.githubusercontent.com/assets/13039437/8355591/82db15dc-1b26-11e5-849f-a9c2e3722e7a.jpg)

**Comment by Rottweiler** [comment]
I also can't connect on Dolphin, getting 23915

**Comment by kyle95wm** [comment]
Ah, the default Dolphin NAND is denied access on my server since it can be abused by cheaters

**Comment by kyle95wm** [comment]
Http://beanjr.hopto.org/bans to see a list of all bans that took place on my server

**Comment by Rottweiler** [comment]
Is there any server that I can use Dolphin with? I really want to play Super Smash Bros. with a couple of friends.

**Comment by kyle95wm** [comment]
I suppose I could lift the ban on Dolphin, or better yet you can run the Wiimmfi unbanner on Dolphin to generate a new NAND. Which server did you try to connect to Dolphin with?

**Comment by Rottweiler** [comment]
I used the patcher (wiimmfi-patcher-v3 (1).7z) and my game is NTSC

**Comment by kyle95wm** [comment]
here's a full list of error codes for all three servers

### Error Codes  - ALTWFC
- **20100**: Connection to the Access Point succeeded, but connection to the Wi-Fi Connection servers couldn't be established. Either you forgot to set the DNS and are trying to connect to the now-defunct official servers, or the custom server is currently down for maintenance. May also be a result of not properly patching your game to remove the SSL checks.
- **23404**: Internal server error - To server admins: This usually means that Apache's virtual hosts aren't found on the server (or if nas_server.py is using port 80 when Apache is also using it)
- **23503**: Game server offline but reachable outside of game (i.e web server is up)
- **51300-51399**: The Wii is unable to connect to the access point. Double-check the settings and try again.  
- **52100-52103**: Your DS can't contact the server. It could be a problem with your internet or the server could be temporarily offline.
- **52200-52203**: This error seems to appear when attempting to connect to the server multiple times without properly disconnecting first. Reboot your console and try again.
- **60000**: Error relating to your user profile. Most likely, you're trying to connect to the custom server using save data that still has your Friend Code from the official server stored in it. On the DS, you should be able to fix this by deleting your NWFC Configuration as described [[here|Home]], on the Wii you either have to delete your save file for the game you're trying to connect with or manually remove friend code information by editing your save file. This may improve in the future.
- **61020**: Profile Server unreachable. Probably not a problem on your end.
- **61070**: Profile Server unreachable
- **81010**: The server has been shut down or restarted for maintenance. This error can also mean you were kicked from the server
- **84020**: QR Server unreachable. Probably not a problem on your end.
- **86420**: A direct connection was attempted with another player but the connection failed. Possible reasons could be firewall, ports or latency.  
- **98020**: The gamestats server is not implemented. If you have well-documented packet captures from the official WFC, you should [file an issue](https://github.com/polaris-/dwc_network_server_emulator/issues) with them and perhaps a volunteer programmer can implement it. For the time being, the game is unsupported.

### Error codes - BeanJr-Fi
- **20100**: Connection to the Access Point succeeded, but connection to the Wi-Fi Connection servers couldn't be established. Either you forgot to set the DNS and are trying to connect to the now-defunct official servers, or the custom server is currently down for maintenance. May also be a result of not properly patching your game to remove the SSL checks.
- **23404**: Internal server error - To server admins: This usually means that Apache's virtual hosts aren't found on the server (or if nas_server.py is using port 80 when Apache is also using it)
- **23503**: Game server offline but reachable outside of game (i.e web server is up)
- **23913**: User ID creation denied
- **23914**: Console is banned
- **23915**: MAC changer detected on banned console
- **23916**: reserved for future use
- **23917**: Access denied
- **51300-51399**: The Wii is unable to connect to the access point. Double-check the settings and try again.  
- **52100-52103**: Your DS can't contact the server. It could be a problem with your internet or the server could be temporarily offline.
- **52200-52203**: This error seems to appear when attempting to connect to the server multiple times without properly disconnecting first. Reboot your console and try again.
- **60000**: Error relating to your user profile. Most likely, you're trying to connect to the custom server using save data that still has your Friend Code from the official server stored in it. On the DS, you should be able to fix this by deleting your NWFC Configuration as described [[here|Home]], on the Wii you either have to delete your save file for the game you're trying to connect with or manually remove friend code information by editing your save file. This may improve in the future.
- **61020**: Profile Server unreachable. Probably not a problem on your end.
- **61070**: Profile Server unreachable
- **81010**: The server has been shut down or restarted for maintenance. This error can also mean you were kicked from the server
- **84020**: QR Server unreachable. Probably not a problem on your end.
- **86420**: A direct connection was attempted with another player but the connection failed. Possible reasons could be firewall, ports or latency.  
- **98020**: The gamestats server is not implemented. If you have well-documented packet captures from the official WFC, you should [file an issue](https://github.com/polaris-/dwc_network_server_emulator/issues) with them and perhaps a volunteer programmer can implement it. For the time being, the game is unsupported.

### Error codes - Starlight Connection

Please go to http://185.13.37.244 for a full list of error codes and other info

The Wiimmfi unbanner program works on any server (and is used with Dolphin) and can be found here
https://forums.dolphin-emu.org/Thread-unofficial-dolphin-nand-generator-released

**Comment by Rottweiler** [comment]
Okay I ran the unbanner and now I get the 23913 error (User ID creation denied)

Also I'm wondering how or where you configure the WFC server address, because as to my understanding the patcher has a hardcoded address that it patches into the ISO file.

**Comment by DouglasMartins1999** [comment]
Please, don't forget me...
Until now I'm trying to connect and nothing. Any help?

**Comment by kyle95wm** [comment]
@Rottweiler you DID say to patch DWC using the Wiimmfi patcher right? Also as for configuring the address to use for the server it is to be configured under your computer's NIC settings (the part where you configure IP and DNS settings

**Comment by kyle95wm** [comment]
@LatiosDoug We'll get to you after we fix @Rottweiler 's problem

**Comment by Rottweiler** [comment]
I tried setting my current adapters DNS settings to 185.13.37.244, but I was still not able to connect. (23913 - User ID creation denied)

**Comment by kyle95wm** [comment]
hmmm

What do you get when you do an nslookup of "nas.nintendowifi.net"?

It sounds to me like you're either not setting the DNS correctly or that you're using a Wiimmfi ISO

**Comment by Rottweiler** [comment]
I am using a Wiimmfi ISO, I patched it. Also dnslookup responds 69.25.139.141

**Comment by kyle95wm** [comment]
did you run something like "patch-dwc"?

**Comment by kyle95wm** [comment]
Im in the process of editing an educational video for your problem to help clear up some questions

**Comment by Rottweiler** [comment]
All right

**Comment by kyle95wm** [comment]
I just want to check firstly, are you able to access any of the websites for the servers (except for ALTWFC)

**Comment by Rottweiler** [comment]
I can access Starlight Connection, yes.

**Comment by kyle95wm** [comment]
okay good, that narrows it down to the problem. I'll post here when the video is uploaded, but in the meantime, I'm assuming you're trying to run your image from a folder called wiimmfi-images. If this is the case, this explains why you're getting 23913 (on Wiimmfi it means console creation denied)

You're sure theres no DWC option in the ENTIRE Wiimmfi patcher download? I know for the Mario Kart Wii  specific patcher theres a "patch-wiimmfi" and a "patch-dwc" file that does what the name implies. One patches an ISO to use Wiimmfi and another patches an ISO to remove the HTTPS but leave nintendowifi.net there in the ISO (this is what we use to connect people to out servers)

**Comment by Rottweiler** [comment]
So am I supposed to patch using patch-dwc.bat instead of patch-wiimmfi.bat?

**Comment by kyle95wm** [comment]
yes - if that file is even there to begin with.

**Comment by Rottweiler** [comment]
Yeah, it is. I used the wiimmfi patcher because almost every tutorial video stated that you should use that one.

**Comment by kyle95wm** [comment]
I think you're confusing what people say with how you actually join ALTWFC. The Wiimmfi patcher "patch-wiimmfi" is used for none other than Wiimmfi. The DWC file does the exact same thing except it does the URL's a little differently. It should work if you run the DWC file instead

**Comment by kyle95wm** [comment]
https://www.youtube.com/watch?v=te9Vt_3mpio&feature=youtu.be

Video is processing atm

**Comment by Rottweiler** [comment]
Patching using DWC now. I'll check the video out when it's done processing.

**Comment by kyle95wm** [comment]
yeah its gonna take a while to process lol

**Comment by Rottweiler** [comment]
Okay, I watched your video. This patcher throws an error for me "! wit: One directory scanned, but no valid source files found.". I have my ISO in the same directory though.

**Comment by kyle95wm** [comment]
interesting!

**Comment by kyle95wm** [comment]
are you sure your original ISO is in the patcher and not some random one?

**Comment by kyle95wm** [comment]
have you tried with other games?

**Comment by Rottweiler** [comment]
Yeah, tried two games. I set up the DNS server properly by the way. I think it's the patcher part that I'm having trouble with. For some reason it won't detect my ISOs in the dir.

**Comment by Rottweiler** [comment]
Nevermind actually, the patcher you showed in the video was for Mario Kart only. Patching regular way again now using "patch-dwc.bat" from "wiimmfi-patcher-v3".

**Comment by kyle95wm** [comment]
Keep me posted

Don't worry @LatiosDoug we haven't forgotten about you

**Comment by Rottweiler** [comment]
I got it working! Thanks for your help.

**Comment by kyle95wm** [comment]
okay no problem.

@LatiosDoug now for your problem. Were you able to access ALTWFC before this issue was opened?

Were there perhaps any changes within your network's architecture? (i.e - new devices, router, etc)

Lastly are you able to access the web page of all 3 servers?

If your answer is no to the question above, then something on your network is blocking access to these addresses, or perhaps it's your ISP's way of "protecting" you.

**Comment by DouglasMartins1999** [comment]
I tell before. I was using with my LG L3 Hotspot. But now I unable to access with my router CISCO E1000. I don't try now with my old hotspot (I'm without money to put credit).

Starlight and BeanJrFi ok. Original ALTWFC I'm seen a blank page in browser.

**Comment by kyle95wm** [comment]
I believe the blank page on ALTWFC is normal. So now we can establish that you are able to access all three websites, but are unable to connect to the servers

**Comment by DouglasMartins1999** [comment]
I try right now with my LG L3 and work. But I need working in my router. Some help?

**Comment by kyle95wm** [comment]
Your wireless network MUST be WEP encrypted (nothing higher) or it can be with no encryption. Sadly the Nintendo DS just doesn't support WPA for online games

**Comment by DouglasMartins1999** [comment]
It is encrypted with WEP with 802.11b. My LG L3 isn't encrypted, but is
showed in computer with 802.11n and connect to DS. However, I tried to set
my router to 802.11n and my DS isn't connect to it.

**Comment by ghost** [comment]
BTW @kyle95wm Wiimmfi's patcher no longer has patch-dwc.bat due to the changing IPs - that is Wiimm's decision.

**Comment by DouglasMartins1999** [comment]
I tried set 802.11b/g and WEP and I get "Connection Successful". But when I try to enter in GTS or get a gift I receive the error 20100 or 20110. I try with android hotspot and work perfectly. Some help?

**Comment by kyle95wm** [comment]
Have you tried with any other games so we can do process of elimination @LatiosDoug

**Comment by DouglasMartins1999** [comment]
Now I tried with Pokémon Black (Error 20110) and Pokémon Diamond (Error 20110 and 20100). I also tried with Mario Kart DS (Error "Nintendo WFC service for this sotware has been halted").

**Comment by kyle95wm** [comment]
and you're positive you ran the altwfc patcher on your Nintendo DS games?

**Comment by DouglasMartins1999** [comment]
Please, pay more attention on my comments. I already say it: Yes. And I can connect normally my DS, with the same games, with wifi hotspot of my cell phone. I only unable to connect with my new router. It is encrypted with WEP, but I get errors when I try enter in GTS, Mystery Gifts and Battle Videos. IT'S ONLY IN ROUTER! IN CELL PHONE'S WIFI WORK NORMALLY. ok?

**Comment by mm201** [comment]
Have you set the DNS in the right place, ie. the DS connection settings, not your phone?

**Comment by DouglasMartins1999** [comment]
I published photos with the DNS set in DS... Aren't they helping?
And if I set the DNS in phone will work? I believe that no...
I'm sorry if I sound rude. @mm201 @kyle95wm

**Comment by kyle95wm** [comment]
Geez calm down no need to get defensive on me

**Comment by mm201** [comment]
Set the DNS on all your DS wifi profiles in case it's using a different one from what you think.

**Comment by DouglasMartins1999** [comment]
I'm sorry...
I think I don't need set the DNS on all profiles 'cause I only have one profile XD

**Comment by mm201** [comment]
Check anyway. Delete any of the ones you're not using. Make sure you're using `104.131.93.87` for Pokémon games. Those errors mean your DS is connecting to the defunct server.

**Comment by DouglasMartins1999** [comment]
But... I only have one profile ^~^
Connection Successful in NWFC Setup, but in GTS fail... Same error...

The problem is: Even when I don't set the DNS I receive a "Connection Successful"

**Comment by DouglasMartins1999** [comment]
I tried erase Nintendo WFC Configuration. I set my access point, WEP key, DNS, and I tested the connection. The signal icon stayed green by a moment, after become red and get error 20100...

**Comment by DouglasMartins1999** [comment]
Nobody wanna help me more? Sorry...

**Comment by kyle95wm** [comment]
we're just not sure how to help you. It sounds to me like you're able to do a successful connection test with any of the servers but can't actually connect to them which tells us one of two things is wrongs
1) your game isn't properly patched
2) your network simply isn't allowing you to make a connection with us

**Comment by DouglasMartins1999** [comment]
The first can't be 'cause I tried today with my cell phone and work. So, the patch is working very well... XD

**Comment by mm201** [comment]
Or your router/ISP is doing something very dodgy with DNS requests.

**Comment by DouglasMartins1999** [comment]
Could somebody tell me how I should configure correctly this router? I already set security to WEP, and put 802.11b/g. It is a Cisco Linksys E1000... Is normal Linksys routers show those issues?

**Comment by ghost** [comment]
Have you tried a packet dump? You can get cloudshark on OpenWRT/DD-WRT

Your router's OpenWRT page:
http://wiki.openwrt.org/toh/linksys/e1000

Your router's DD-WRT page:
http://www.dd-wrt.com/wiki/index.php/Linksys_E1000

----- Reply message -----

**Comment by nionios02** [comment]
are the servers working 24 hours a day? and can i play online on your server with my nds or do i need an emulator?
I'll appriciate any help !

**Comment by kyle95wm** [comment]
which server are u referring to? mine or @polaris- 's? mine are up 24 hours a day afaik

**Comment by nionios02** [comment]
i think it's called altwfc...
btw can i connect through my action replay (using patched roms) ? and i'm not sure how to

**Comment by kyle95wm** [comment]
ALTWFC has been having issues lately. My server is well maintained on a daily basis and gets restarted every so often.

**Comment by nionios02** [comment]
can you please tell me the dns just to connect to your server? or just the name of the server and i will google the dns :)

**Comment by kyle95wm** [comment]
Please see the "list of servers" wiki page. The one you wanna connect to is "BeanJr-Fi" but you must register first. Once you register let me know and I'll activate your console.

**Comment by nionios02** [comment]
okay thanks ! should i do anything else to order connect to the server? (except register)

**Comment by kyle95wm** [comment]
No just set DNS, register your console and create a new profile for the game you want to connect with.

**Comment by kyle95wm** [comment]
Basically connect as if you were connecting to alt but the DNS is different.

**Comment by nionios02** [comment]
okay i entered the dns right and you want my mac address right?

**Comment by kyle95wm** [comment]
go to http://beanjr.hopto.org/register and submit your MAC in the indicated format. Ive already received 2 console registration within the last hour and activated them both

**Comment by kyle95wm** [comment]
Did you just try putting in a MAC just now? I see you triggered something that shouldn't have happened. Make sure there are no dashes or semicolons in the MAC

so for instance if your MAC was aa:bb:cc:dd:ee:ff

then you'd enter 

aabbccddeeff into the site

**Comment by nionios02** [comment]
i put aa-bb-cc and so it goes... so you want me to put it again like aabbcc? i'll try again

**Comment by kyle95wm** [comment]
yeah and no caps for letters.

**Comment by kyle95wm** [comment]
Also I just finished fixing that weird exception error so the page should just show "Bad data" if you inputted something incorrectly.

**Comment by kyle95wm** [comment]
is your MAC 0019**f6**ff?
If so then your console is now activated.

**Comment by nionios02** [comment]
thanks for everything! and yeah i put it again..!

**Comment by kyle95wm** [comment]
I didn't include all your MAC in that post since it would make it easier for third parties to guess. You should be able to connect now. Just FYI if you go to http://beanjr.hopto.org/error you should be able to see any error codes for ALTWFC and BeanJr-Fi and their meanings

**Comment by nionios02** [comment]
i had a 52100 error what happend?

**Comment by kyle95wm** [comment]
52100-52103: Your DS can't contact the server. It could be a problem with your internet or the server could be temporarily offline.

Where were you receiving this error code?

Is the wifi you're connecting to WEP encrypted? Anything higher for encryption and it won't work. The DS doesn't support WPA

**Comment by nionios02** [comment]
i was using my lg l3 ii430 android hotspot and i have set it to open hotspot

**Comment by kyle95wm** [comment]
Interesting.... I can assure you that the server is indeed online, or else I wouldn't be able to access the admin portal of my server if it weren't

**Comment by nionios02** [comment]
i will check again and tell you

**Comment by kyle95wm** [comment]
I will be out for the rest of the evening, so anything server-related has to wait though I will try to help you remotely the best I can

**Comment by nionios02** [comment]
okay thanks ! i still have errors but whenever

**Comment by nionios02** [comment]
(whenever) you can just pm me or just comment here !

**Comment by nionios02** [comment]
so should i try connecting to the server again? is the server online? in order to connect to altwfc (in case if the others are down) what should i do?

**Comment by nionios02** [comment]
well i tried pokemon heart gold and i think i keep getting these errors (51200:ds can't reach server or the problem is your internet) becuase no one is online.So,i'll try to connect with pokemon black and if i connect the problem is that no one is at the moment online at heart gold....

**Comment by AudryckModifiesGaming** [comment]
I tried the dwc bat on my mkwii iso and I got 20100 when I tried to connect

**Comment by Thepropper** [comment]
Im using a virtualbox machine to emulate wired connection and i get error 23404, does it mean the server is just down or im doing something wrong? im using the 104.131.93.87 server.
