### ISSUE TITLE
Error 13274

### ISSUE THREAD

**Issue by Kamicrazy** [barronwaffles/dwc_network_server_emulator#178]
Been experimenting the error 13274 trying to connect on AltWFC GTS trade for pokemon (White) from emulator. Had no problem to connect to the server before. This error code is not explained in the wiki page. Also pkmnclassic.net webpage times out for me.

**Comment by mm201** [comment]
Problem is on my end. Investigating.

**Comment by mm201** [comment]
The GTS server was timing out connections. I restarted it and things seem to be working now.

**Comment by Kamicrazy** [comment]
All is working now, thanks.
