### ISSUE TITLE
Limit profile/console creation for a certain time period

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#179]
I'd like to see the server's source code handle the ability to limit a specific user from creating a certain number of profiles during a certain time period

For example, Wiimmfi only allows two profiles to be created within a 24 hour time period and prevents new ones from being created for 24 hours

Only 1 console (perhaps 2) can be created within 24 hours (i.e - Dolphin)

I'm assuming we can implement something like this into the server source code.

Here's now I imagine it:

-user creates profile #1 
-user creates a 2nd profile - the server adds the person's IP address into a database (maybe something called "denied" or "temp_ban")
-user goes to create a 3rd profile and is given an error code of our choosing (via nas_server)
-server removes banned IP from denied database after 24 hours

**Comment by ghost** [comment]
I tried the console limit, it's 1 console per day on Wiimmfi.

**Comment by kyle95wm** [comment]
Im still wondering if a similar system can be implemented into ALTWFC. Im not kidding when I say I have over 193 profiles (nearly 200) and most of the profiles were created on the same console multiple times
