### ISSUE TITLE
how configure and install

### ISSUE THREAD

**Issue by andromeda01** [barronwaffles/dwc_network_server_emulator#180]
i have installed python twisted and win32api on my windows 7 x64;if i run master_server i can go on all server management ip.
now i have to set a dns server how set it?
my pc is on lan 192.168.1.66

**Comment by kyle95wm** [comment]
The only thing I can think of is you need to set up Apache with virtual hosts

As for the DNS server just add the role, create a new zone called "nintendowifi.net" and create a new forward lookup and put a "*" so that it's a wildcard and saves you lots of time
