### ISSUE TITLE
[IDEA] PID adding python script

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#181]
The title explains it all.
I have access to my Wiimmfi PID, GBSCRID, and the other things required for login, yet IDK how to add them to the table, so a python script would be nice.

**Comment by kyle95wm** [comment]
You can use something like sql lite browser to add them but you'll also need to add ur CFC, CSNUM, username, password, email, etc

**Comment by ghost** [comment]
You can get these from a packet dump :stuck_out_tongue:
