### ISSUE TITLE
Possible to reverse proxy to another server?

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#187]
Okay for those of you who might be confused, allow me to explain.

Yesterday, me and PokemonAcer were able to register me a domain name (http://beanjrfi.ml) and make it functional. We used Apache virtual hosts to accomplish this. This part was obviously EASY because it was reverse proxying to the local loopback (for those who don't know - 127.0.0.1)

We then got into a discussion about making my test server (currently located on the LAN as 192.168.101.64 - where as my main server is 192.168.101.63 - yes very original :P)

We thought it would be as easy as substituting the local loopback for said IP address of the test server. Unfortunately things didn't quite turn out very well. We got mixed results (i.e the DNS wasn't working properly) for example at one point we got error 20101 and it seems as if the Wii (or Dolphin in this case) sent an availability request to the MAIN server even though we told the game not to go to the main server but rather the test server (http://beanjrtest.ml) instead

I tried just a few minutes ago and now, I get error 23503 even though the master server is running on the test server (same ports) but obviously port forwarding goes to the main server

Can anyone give me any ideas about whats going on here and how to fix it?

**Comment by the4anoni** [comment]
What system are you using ???

**Comment by kyle95wm** [comment]
Raspbian

**Comment by the4anoni** [comment]
I don't know How to setup wfc server on raspberry . First try an old computer with lite linux installed when try to run server on raspberry pi.

**Comment by kyle95wm** [comment]
Fortunately Raspbian is the same as Debian and with the use of my script it makes installation easy. Now I have a feeling that all that needs to be done is for the 127.0.0.1 stuff has to be changed to 0.0.0.0 but I could be wrong

**Comment by ghost** [comment]
This'd make more sense - normally it only has to listen to requests from apache which is on localhost :stuck_out_tongue: - but there must be a way to make it work. Just saying, leave conntest XP

**Comment by kyle95wm** [comment]
Not sure what you meant by that last part.

**Comment by the4anoni** [comment]
Are this tutorial will help https://github.com/polaris-/dwc_network_server_emulator/wiki/Setting-up-Custom-Domains-for-your-DWC-Server ???

**Comment by ghost** [comment]
That's @kyle95wm 's own tutorial. 
HTTP503 = Service unavaliable - make sure raspian's portforwarding all the ports in the network (normally not applicable because it normally connects via virtualhost)
