### ISSUE TITLE
[IDEA] Add FriendCodes to stats server

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#189]
Hey all,
I think that, to the stats page, a person's Friend Code should be displayed. Thankfully, I've setup a php script that takes profile id and the id4 of the game (gbscrid's ID4) like so:
http://185.99.132.59/billy/fc.php?pid=<pid>&gid=<ID4>
I can give a dev this PHP script if needed, but my VPS can handle requests.

**Comment by kyle95wm** [comment]
how do you think we should go about adding it to the stats page? Im not very good with python/html/php

**Comment by ghost** [comment]
We'd have to somehow make a DB that could actually calculate all FCs every x min or so, then add that to stat page for ease, and then you don't have to remake FC for every PID. Really, you could just save PID 1-999999 fc but that's way too many - just stick with my idea.

**Comment by kyle95wm** [comment]
Whatever needs to be done, I'm sure it'll be worthwhile for many people. Even though 3 people might be on Mario Kart Wii for example, it doesn't mean they're actually racing which confuses most people. I believe a Mario Kart Wii stats page should also be in order, wouldn't you agree?

**Comment by AdmiralCurtiss** [comment]
If you want this added to the server you have to provide the formula for calculating friend codes.

Also, unless the calculation is super processor intensive, which I can't imagine it being, there shouldn't be any issue with just calculating it on the fly instead of populating a database.

**Comment by kyle95wm** [comment]
Ive always been looking to have a more detailed stats page instead of it just telling me who's on what game. It would be nice if it showed WHO was on what game and their friend code. This way, people can easily report cheaters by grabbing their friend code/profile id and reporting it to the server admin who can take actions from there.

**Comment by ghost** [comment]
^^^
@AdmiralCurtiss sure, I'll put a copy now.
http://185.99.132.59/billy/fc.php.txt
Again, you simply give it ?pid=<pid>&gid=<id4> but remember that _most_ games use ***J, so I recommend using the gbscrid.

**Comment by kyle95wm** [comment]
Most games don't have GSBRCD

**Comment by ghost** [comment]
@kyle95wm - http://prntscr.com/7y388u
That is _your_ server's gsbrcd column.
See how there's 2 ADAJ (Pokemon)? one of those is actually not even pokemon (It's FFCC:EoT) yet it usess ADAJ for FC calculation. THAT'S why we need to use gsbrcd

**Comment by kyle95wm** [comment]
Okay true, but games like Smash Bros don't transmit that. The only thing the games on the server have are their ID4 they all end in J

**Comment by ghost** [comment]
Well we can't use their gameID always. and are you sure they don't? I'd think Wiimmfi'd have an issue with that - they require gsbrcd for all games.
Perhaps we use a name approach - for games that do not transmit that data, have a db file that contains the relevant gameid to use, but check by seeing what name it uses (for example, smashbrosxwii.master.gs.beanjrfi.ml - that may not be a real one) and then checking if it has the gsbrcd in the login data. If not, check the db, and if it's not in there, show PID not FC.

**Comment by kyle95wm** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/158 had a problem with GSBRCD (it was because of old code but you get my point)

**Comment by AdmiralCurtiss** [comment]
For local reference, that formula is:

```
<?php
$fc = ($_GET["pid"] | ( ord(md5(pack('V',$_GET["pid"]).strrev($_GET["gid"]),true)) & 0xfe ) << 31); 
echo $fc;
?>
```

**Comment by kyle95wm** [comment]
I'm assuming this can be added to the stats page with an online players table?

**Comment by polaris-** [comment]
For the record: https://github.com/polaris-/dwc_network_server_emulator/blob/master/gamespy/gs_utility.py#L173

Generates the friend code from the profile id. It's based on the code for Tetris DS, but a lot of games use the same algorithm. Some games use the reverse of the output of this function to generate the friend code.
