### ISSUE TITLE
Error Code:20100,Mind helping me here?

### ISSUE THREAD

**Issue by Randy295** [barronwaffles/dwc_network_server_emulator#190]
I'm using a REAL 3DS to connect to this network so that means I'm using a legit cartridge here

The game I got the error code from was Pokemon White 2

Whenever I try GTS (Aka Making a GTS Trade,GTS Negotiations etc etc) and I try to connect,I always seem to get Error Code:20100

What am I supposed to do? and yes I have manually set up the Primary DNS AND the Secondary DNS to 104.131.93.87

**Comment by WinterPhoenix** [comment]
Did you use the Action Replay code before you loaded the game?

**Comment by Randy295** [comment]
Oh! So that's the problem(even though I'm aware that I need action replay obviously)...I tried it without action replay to see if it can work but it didnt....

Thanks,I think this issue is solved for now

**Comment by WinterPhoenix** [comment]
Yeah, you either need Action Replay to patch it before you connect, or you've gotta patch the game's ROM directly.

The reason you get 20100 with trying to connect with a totally legit setup using the Custom DNS Servers is because the official servers used SSL with their connections for the sake of security, but the AltWfc servers don't/can't use SSL.

**Comment by Randy295** [comment]
Wait a minute...I actually don't know if the latest 3DS Update blocks action replay completely or not so I'm not sure if I should buy an action replay code yet

**Comment by WinterPhoenix** [comment]
I would look into that before buying one, yes.

**Comment by Randy295** [comment]
I think It's better if I didnt bother getting an action replay...Well thanks anyways

**Comment by WinterPhoenix** [comment]
Sorry about that ^^;

**Comment by Randy295** [comment]
Or maybe I still can get it and make it work...Hope exists y'know.....But I dont know if there in any local walmarts or bestbuys near me (I live in canada by the way)

...Also what specific action replay DSi code do you  need to connect to the server?

**Comment by WinterPhoenix** [comment]
https://github.com/polaris-/dwc_network_server_emulator/wiki#action-replay-dsi
You'd have to grab the official ROM from somewhere else though.

**Comment by Randy295** [comment]
Okay,maybe I can somehow "transfer" my pokemon from the ROM to my pokemon white 2 cartridge even though the steps are gonna be long

**Comment by WinterPhoenix** [comment]
No no, like, your just need a ROM for your game to get the Action Replay code. You don't need to have your save data or anything like that on it.

So what you would do is find the ROM, like you would for a DS Emulator, on the Internet somewhere, download the utility in the section of the Wiki I linked above, and drag and drop the ROM (probably a .iso file) onto the utility. This will spit out an Action Replay Code that you can use to access AltWfc servers.

**Comment by Randy295** [comment]
OH Okay..Thanks! Does it have to be a white 2 rom for a white 2 cartridge or can a black 2 rom work as well? UNLESS The action replay code is for the ROM and not the Cartridge

And also how can I use this code if I never bought and used an action replay DSi yet?

Do I have to buy one...?

EDIT:Yeah I think it's obvious that I should buy one and then use the code

**Comment by WinterPhoenix** [comment]
It has to be the same ROM for the same cartridge. For example, you would get a Pokemon White 2 ROM for your Pokemon White 2 Cartridge.

You would have to buy an Action Replay DS or Action Replay DSi to use the Code.

**Comment by Randy295** [comment]
Thank you

**Comment by WinterPhoenix** [comment]
No problem.

**Comment by Randy295** [comment]
Hold on a second....Do you know when the Action Replay DSi(3DS Compatible) was last updated?

**Comment by WinterPhoenix** [comment]
I don't believe it matters, unless Nintendo patched the 3DS to break it, but sometime around when Pokemon Black 2 and White 2 came out, I think.

**Comment by Link2738** [comment]
Please note that the ar ds only works on a original ds (3ds crashes and dsi doesn't appear )
The best bet would be the dsi version because it can be used on 3ds might be patched but it could work.

**Comment by Randy295** [comment]
Ah um...I actually know that

I DID say "Action Replay DSI (3DS Compatible)" not "Action Replay DS"

But thanks anyways
