### ISSUE TITLE
[REQUEST] - use altwfc.net as an in-game domain

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#191]
It's actually really easy to set up @polaris- (or whoever owns the domain)

This would make it easier to ISO patch a game to use domains instead of needing cheat codes and DNS (though the DNS option should be left open to Nintendo DS users)

If you're not sure how to set this all up, please have a look at
https://github.com/polaris-/dwc_network_server_emulator/wiki/Setting-up-Custom-Domains-for-your-DWC-Server

**Comment by mm201** [comment]
There's no reason not to. It's trivial to do and helps with certain Wii patching methods. The altwfc.net DNS already points to the correct IP address; you just need to add the virtual hosts.
