### ISSUE TITLE
How I can help with makeing this project ??

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#193]
The question is in the topic.

**Comment by kyle95wm** [comment]
the best thing to do is go through all the feature request issues people have opened up and put your coding skills to the test.

**Comment by WinterPhoenix** [comment]
I'd recommend improving the Stats Page especially, as there's nothing on there that's tying player names to Friend Codes or anything, making it insanely difficult to ban bad players.

**Comment by kyle95wm** [comment]
I agree. We already have a solid ban system (on my repository anyways) where it bans console and IP

**Comment by WinterPhoenix** [comment]
Just uh, no way to actually figure out who is who so we can ban them. At least easily. lol

**Comment by kyle95wm** [comment]
Well the admin page shows the name of each player and all relevant info about them.

**Comment by WinterPhoenix** [comment]
Oh, really? Uh, well then. I stand corrected. Regardless, the Stats Page could use more info anyway, but hey.

**Comment by kyle95wm** [comment]
We should update the stats page so legit players are able to report to server admins what they see so we have accurate information to take care of the cheater.

**Comment by AdmiralCurtiss** [comment]
If you want my opinion, I think some people here are getting way too hung up about banning people. I think we should first fix/rewrite the QR server so it actually works consistently.

**Comment by WinterPhoenix** [comment]
QR Server is a valid point actually...

**Comment by kyle95wm** [comment]
May I ask what's wrong with that server? In my tests with a few players it worked fine. But maybe I'm missing the bigger picture. I agree we should take care of other bugs and leave banning to the last thing we do.

**Comment by WinterPhoenix** [comment]
Basically the main issue is that it tends to lock up/crash seemingly at random. I don't know the specifics of the issue though.

**Comment by the4anoni** [comment]
On save-nintendo-wifi.net I found this :
"How to help

Right now we want to get as many packet captures from as many games as we can. These will be essential in figuring out how the servers work and reverse engineering them. Along with the dumps, details about what you were doing when you dumped the packets would help as well. The more detailed the better, and if you can make a small video recording of your session that would be the best."

Is it isn't outdated from before closing servers ???
Sorry for my bad english.

**Comment by AdmiralCurtiss** [comment]
Yes, that is very outdated.
