### ISSUE TITLE
Please make list of all commands for admin of server on the wiki.

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#194]
The request is in the topic.
I really need this ,because i want make home Wfc Event.

**Comment by kyle95wm** [comment]
If you're talking about setting up your own server there's a post on that by me. If you're talking about the admin portal go to port 9009 on your server (a single console must log in first before anything can load) and then log in with the username and password you provided during installation

**Comment by the4anoni** [comment]
Thanks
