### ISSUE TITLE
3 questions :)

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#196]
Hello.
I have 3 questions about this project :
1.Can I use Nintendo Wi-Fi Usb Connector to connect to AltWfc ???
2.When Ds games doesnt require Ssl patching ???
3.When we can run AltWfc on Windows ?

**Comment by AdmiralCurtiss** [comment]
1. Yes, but you have to adjust your PC's DNS settings.
2. Never.
3. I've never tried it but I don't think anything is preventing it from doing that.

**Comment by the4anoni** [comment]
Anyone trying to setup AltWfc on Windows ???

**Comment by mm201** [comment]
I think Flipnote Hatena is an exception but it has its own server.

**Comment by sepalani** [comment]
@the4anoni 
Done https://github.com/polaris-/dwc_network_server_emulator/issues/188#issuecomment-130043730

**Comment by RicoSantos** [comment]
I don't know about other versions, but it works fine on my Windows 8.
