### ISSUE TITLE
Error Code:52200,What do I do?

### ISSUE THREAD

**Issue by Randy295** [barronwaffles/dwc_network_server_emulator#198]
The game I'm playing is Pokemon White 2 (on my action replay DSi Cartridge of course) and I am using a real 3DS so no emulators here

I booted up the game with an action replay code that allows me to bypass HTTPS v0.5

I'll try to explain what happened:

So when I decided to use the GTS,I look up and saw the bar at red..then it goes up to green..then back down to red and BOOM! The error appears!

I also tried to "reboot" my 3DS (via the power button) but it still doesn't work!

Before that happened,I changed both primary and secondary DNS to the one that was shown on the Pokemon Classic Network website

How do I solve this?

**Comment by mm201** [comment]
It may sound silly but try rebooting _again_. You have to reboot after the server assigns you a profile due to a bug: https://github.com/polaris-/dwc_network_server_emulator/issues/30

**Comment by Randy295** [comment]
Well,how will i know if the server assigns me a profile?

And I assume I'd have to reboot again and again via turning off the 3DS then turning it on,correct?

**Comment by mm201** [comment]
If it gives you the whole "Nintendo Wi-Fi treats the DS and cartridge as a pair" speech, it's about to assign you a profile.

Yes, shut off and restart.

**Comment by Randy295** [comment]
OH! I get it now....Apparently I have to set up a REGULAR Nintendo DS Connection setup..I'm not sure if I can execute this since the access point(I am trying to connect to)'s security type is WPA..I'm sure there are more access points who has their security type as WEP or something

EDIT:Looks like I did it! Successfully connected to a guest network so I'm able to connect to the GTS and stuff now

**Comment by Randy295** [comment]
Wait...I do have a question...If I switch to WEP(Temporarily),doesn't it mean my security can be cracked easily by other people?

if so,then how will I ever be able to connect to the servers without being paranoid?
