### ISSUE TITLE
wfcPatcher doesn't work for me?

### ISSUE THREAD

**Issue by RSubs** [barronwaffles/dwc_network_server_emulator#199]
i try to drag my pokemon white rom into the exe file and it forces quit without creating a second file, what to do?

**Comment by AdmiralCurtiss** [comment]
WfcPatcher only supports proper dumps with full header, so make sure your dump is correct by comparing its checksum to a known good dump.

WoodDumper is the best dumping tool, FYI. You can find it on No-Intro.
