### ISSUE TITLE
These settings are invalid. Confirm the information and try again.

### ISSUE THREAD

**Issue by Moonboy65** [barronwaffles/dwc_network_server_emulator#200]
I need help, so I try adding the Server Emulator IP address on my DS/2DS, did all the steps but when i click to save the changes, this shows up: These settings are invalid. Confirm the information and try again. For help, visit support.nintendo.com

I also can't erase my Wi-Fi configuration :(

If anyone can help, i would appreciate it 

EDIT: I added the server name, I can save the settings but the Connection Test fails.

**Comment by Moonboy65** [comment]
I also tried the Emulator, i still get the same error message

**Comment by Moonboy65** [comment]
Edited my first comment

**Comment by Moonboy65** [comment]
I tried with the action replay code on the emulator, i can't find any access point, HELP!!!

**Comment by Link2738** [comment]
Okay what game are you trying to connect. Are you using the custom emulatior. LAN or WiFi ? And if your using the custom emulatior did you follow the steps

**Comment by Moonboy65** [comment]
actually nvm, I gave up lol

I don't need to connect to altwfc anyways XD

**Comment by LtSurge** [comment]
Hi I'm getting the same 'These settings are invalid' message. except I'm using a original DS w/ Pokémon Soul Silver cartridge and action replay. I already entered the Nintendo server bypass code in the AR menu and tried to change the IP address then this happened :(

**Comment by kyle95wm** [comment]
May I ask which server everyone was using? My server's name is BeanJrFi

**Comment by LtSurge** [comment]
I was trying to use the public server

**Comment by kyle95wm** [comment]
Which one though? There's two at the moment that are listed on the wiki

**Comment by LtSurge** [comment]
Sorry that was dumb. 104.131.93.87

**Comment by LtSurge** [comment]
Nevermind I think I have it figured out, but when I load the game and try to enter the gts I get Unable to connect to Nintendo Wi-Wifi Connection
Error Code: 52000

**Comment by Gabiusnewelius** [comment]
LtSurge can you please tell me what did you do to get rid of the "These setting are invalid" message? I can't seem to get rid of it.

**Comment by LtSurge** [comment]
Sorry It took so long to get back to you. Don't know if you still need help
or not.  I can't remember exactly what I did, I think it was something to
do with the security on my router. DS uses WEP security and most modern
routers use better security. I had to go into my router setup page and
change it to 'open' when trying to connect.

**Comment by NaturalHarmonia** [comment]
I'm using DSiMenu++ to play Pokemon White 2 and everytime I try to save the settings of the two DNS addresses I get: "These settings are invalid. Confirm the information and try again. For help, visit support.nintendo.com." Could anyone help?
