### ISSUE TITLE
GTS + PokéGen

### ISSUE THREAD

**Issue by Moonboy65** [barronwaffles/dwc_network_server_emulator#201]
I have a copy of Platinum/HeartGold with the AR Code but i wanna know if the GTS will work with PokéGen.

**Comment by mm201** [comment]
For now it will work, until I get anti-cheat in place. https://github.com/mm201/pkmn-classic-framework/issues/3

**Comment by Moonboy65** [comment]
so the GTS works, but how will I be able to put PokéGen on it after you get that anti-cheat?

**Comment by Moonboy65** [comment]
I cant connect to the GTS, i get no access point in range

**Comment by AriaRigga** [comment]
Sir. When im trying to connect in random matchups, im always getting error 84020. Communication error. Im playing pokemon BW/BW2. Pls help me.

**Comment by Moonboy65** [comment]
You are on the wrong issue bud

**Comment by mm201** [comment]
Do you mean IR-GTS or other GTS injectors? Those will work and there's no way to stop them. But please don't upload genned pokemon to PCN.

But if you can connect to altwfc, you don't need an injector--you can just as easily modify your save file.

**Comment by Moonboy65** [comment]
That's the issue, i can't connect to altwfc. But i already found a way to get the pokémon I want via Pokédit and Pokésav for Platinum with the Action Replay so I won't be needing the altwfc stuff :)
