### ISSUE TITLE
Did anyone figure out how to make this work on Windows ? 

### ISSUE THREAD

**Issue by Netami** [barronwaffles/dwc_network_server_emulator#203]
I'd really appreciate some guide on how to do it on Windows ;x

**Comment by sepalani** [comment]
Already asked: https://github.com/polaris-/dwc_network_server_emulator/issues/188

By the way, I'm using it on Windows.

**Comment by Netami** [comment]
Didn't understand most of it =p

**Comment by sepalani** [comment]
Search on Google words you didn't understand then ;v)

**Comment by polaris-** [comment]
I'm going to close this. As @sepalani said, #188 already has the instructions. If you don't understand how to install the prerequisites on Windows then you probably won't get much benefit out of running this server on your own, to be honest. You can Google for instructions on how to use pip and Python on Windows.
