### ISSUE TITLE
0 Players In Stats Page *FIXED* Go to Issue #208

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#205]
Whenever I try to go on MKW via altwfc, I can connect to the server, but I can't find anyone in Worldwides. I even tried making a Friend Room with myself, but it wouldn't work from either end. (I have 2 Wiis) So then, I checked the stats page, and I came across this. http://prntscr.com/8dcnhc Is this normal? Or is it a new issue that needs to get fixed? Any help would be appreciated. Thanks.

**Comment by sepalani** [comment]
Thanks for pointing that out. This PR https://github.com/polaris-/dwc_network_server_emulator/pull/206 should fix this issue.

This page used to show a game if there are users connected. Because of my mistake it was doing the contrary. So if you saw MKW it means there is no body playing it. If you really were connected and the page says you're not, it may hide another issue.

**Comment by ghost** [comment]
Oh okay. I see. Thanks! Hopefully it will get resolved soon.

EDIT: I went offline and saw the change. Disregard this message. :)

EDIT 2: The matchmaking on altwfc is not working. The stats page and everything are just fine. I just can't get my 2 wii's to match up in MKW. I have Universal Plug and Play enabled on my router, and checked that all the ports are open. Still nothing. :/

**Comment by sepalani** [comment]
Do your Wiis use the same profile or have the same NAND? Is the matchmaking process working with other people? Can you provide a network dump in both case if possible?

**Comment by ghost** [comment]
1. Both Wii's are using different NANDs
2. The matchmaking from what I see isn't working at all. There was at one point yesterday 4 players on MKW and I still couldn't find anyone. (My other Wii was off at that moment)
3. What do you mean by network dump? I do have access to my router logs, but not 100% sure about dumping from the network.

**Comment by sepalani** [comment]
A network dump or something allowing us to see TCP & UDP traffic. Otherwise, my PR has been merged, the problem might be fixed. Try it again and see if it is still happening.

**Comment by ghost** [comment]
It works! :D Thank you very much!

**Comment by sepalani** [comment]
Thank you as well for reporting this issue ;v)
You can close it if it solved your problem.

**Comment by ghost** [comment]
Okay. You're welcome. :) I will close this now.
