### ISSUE TITLE
Matchmaking on Mario Kart Wii

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#208]
I know that this is a common problem, since matchmaking is not 100% complete yet. I can't seem to find anyone online no matter what I do. Like Fishguy6564's matchmaking fix code, connect with hacked vr, you name it. The weird thing is, I just hang at the "Searching For Opponents..." screen and nothing happens. I don't even receive an error code like 86420 or such. This has been going on since today or earlier. (idk since I joined the server just this morning) Any help will be appreciated. Thanks!

**Comment by sepalani** [comment]
I proposed a PR https://github.com/polaris-/dwc_network_server_emulator/pull/211 that should fix the issue.
