### ISSUE TITLE
Questions about Pokemon Platinum

### ISSUE THREAD

**Issue by Netami** [barronwaffles/dwc_network_server_emulator#210]
There's so many weird Wi-Fi rooms and stuff which one should I use to trade Pokemon? Where to find people for it? I just need someone to trade Pokemons back and forth for evolution etc. I'd trade with myself if I had 2nd PC but I don't =(

**Comment by Netami** [comment]
Okay I think I figured out which place does what now I just need to find some people that actual play Generation IV and use this server =p Anyone here? Any idea where I can find someone ?

**Comment by Link2738** [comment]
Have the same problem it would help the have a forum where you could trade FC's

**Comment by Netami** [comment]
Oh I need to get my FC then

**Comment by Link2738** [comment]
Let's talk about this over on the pokemon classic network page.

**Comment by Netami** [comment]
Sorry where? Anyway my FC is 2748 7793 5501 . Do you have steam? That would be the best place for me to talk.

**Comment by Link2738** [comment]
Yeah but i never use it but my Diamond fc is 3521 8734 3108 ign Link
