### ISSUE TITLE
Yu-gi-oh world championship 2011 Error 90040

### ISSUE THREAD

**Issue by teruy** [barronwaffles/dwc_network_server_emulator#214]
Hello. I have an issue with this game only. Other games are working without any problems. Whenever I'm trying to connect just to download dlc - I'm getting error 90040. I was wondering if it's possible to fix it somehow? Thanks in advance.

**Comment by ghost** [comment]
90040 is because you're downloading DLC we sadly don't have.

**Comment by AdmiralCurtiss** [comment]
Don't be a dick.

**Comment by ghost** [comment]
Better (?)

**Comment by teruy** [comment]
Oh I see. But game was in a list - nintendo ds download content. Anyways thanks for answer.
