### ISSUE TITLE
AltWFC.net

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#215]
Question to the AltWFC.net domain holder - why haven't you setup DNS for it so people can connect by patching the URL in the game to http://x.altwfc.net? Wiimm could then edit the patch_dwc.bat so that instead of using the DNS, the URLs are patched. I helped BeanJrFi do it myself, it took them not long at all :P

**Comment by ZehCariocaRj** [comment]
Hi,
I change the of the domain of game as mario kart and some others, have been playing without having to change the dns. I leave below the Mario Kart iso link with the domain changed to my server. If you still have interest i can help you.


https://mega.nz/#!XJYkTRwQ!S_QhkM400Cuw0pBBqGfOO6ANp6-DLr1R4-cizODD7ds

**Comment by ZehCariocaRj** [comment]
Hi,
I change the of the domain of game as mario kart and some others, have been playing without having to change the dns. I leave below the Mario Kart iso link with the domain changed to my server. If you still have interest i can help you.

[link removed]

**Comment by AdmiralCurtiss** [comment]
Dude you should have gotten the idea from the first time I deleted your post. You can't just go around posting links to ROMs.

**Comment by kyle95wm** [comment]
Yeah seriously? Distributing ISOs is technically illegal and you should keep that sort of stuff to yourself @ZehCariocaRj

**Comment by ZehCariocaRj** [comment]
Ohhh, 

Sorry..
