### ISSUE TITLE
Nintendo DS - Friend Code list (IDEA)

### ISSUE THREAD

**Issue by HellKleitz** [barronwaffles/dwc_network_server_emulator#216]
Hey guys!
I was wondering how can we do to have some kind of list where we would put our "Friend Codes" there. It takes too much time to create a PHP database, so I'm gonna be creative and start with this:

DOCUMENT LINK: https://docs.google.com/document/d/1_qW8Tnkko3nK1PeuUGApUtXwU1otAOBR5DUF8C2yhrI/edit?usp=sharing

This is a Google Docs document where you will be able to "comment" your data (it's all explained THERE) . Then I'll check it out and approve your comment to appear over there.
After this, I'll try out some PHP page but I'm not sure how it's gonna work lol.

I hope to see a lot of people commenting the document! I'm looking forward to it!

Thanks you all!
My regards, 
HellKleitz

**Comment by chardrich** [comment]
Nice suggestion. I will also add my friend code in other games like animal crossing

**Comment by the4anoni** [comment]
Nice idea ,but seems that page needs formatting....
