### ISSUE TITLE
Mac tutorial

### ISSUE THREAD

**Issue by Ryanponthier** [barronwaffles/dwc_network_server_emulator#217]
so im a mac owner using deSmuMe 9.11, and i have a few questions about the whole process. 
1.) will this work on desmume 9.11?
2.) since i cant get wfcreplay on mac is there another program i can use or another way i can get the code?
3.) do i need to have the AR code on before i try and set up the wifi connection?
4.) when i go to set up the connection on the ROM without the AR code im told that my connection settings are invalid. Whys that?
Overall i just need some help with the configuration, if anyone could email me at ryanponthier@gmail.com or kik me at gale321 i could use some assistance.

**Comment by kyle95wm** [comment]
1) idk
2) get virtual box to run Windows
3) no as long as you have wfcreplay patched ROM and the DNS set you should be fine

**Comment by Ryanponthier** [comment]
problem is idk how to get patched rom on mac.
.NET is for windows only

**Comment by sepalani** [comment]
Does it work with Mono instead of a virtual machine?

**Comment by kyle95wm** [comment]
like I said get virtualbox or a similar solution to virtualizing other systems

**Comment by Ryanponthier** [comment]
What emu are you using to do this?

**Comment by Ryanponthier** [comment]
So I've gotten virtual box but not really sure how to set it up for .NET framework

**Comment by the4anoni** [comment]
Use bootcamp...
