### ISSUE TITLE
Can two emulator users play with each other?

### ISSUE THREAD

**Issue by hetpecket** [barronwaffles/dwc_network_server_emulator#221]
Could anyone just confirm if this has been done? Yes/no? By play with each other i mean any form of live interaction such as battling in pokemon or any other games. Thanks.

**Comment by JzargoTheMage** [comment]
They should be able to, but I haven't tried it myself. Someone had a video on it, but I can't find it.

**Comment by TDoomX** [comment]
It's hard to do, includes WinpCap and DesMUME if I remember

**Comment by sepalani** [comment]
I was able to play on Boom Street with two different instances of Dolphin Emulator.

**Comment by chardrich** [comment]
I tried it on Pokemon Heart gold using a DS Lite and Desmume with wifi feature.It depends on PC performance and the internet speed. It was success but its very slow on PC

**Comment by carlosenam** [comment]
chardrinch What did you do?, did you trade pokemon through Wifi Club with desmume?

**Comment by chardrich** [comment]
Yes I already tried it several times but randomly gets a communication error.
