### ISSUE TITLE
Error 20100

### ISSUE THREAD

**Issue by henias** [barronwaffles/dwc_network_server_emulator#222]
Hi!
 I play Pokemon White 2 Europe Version on 3ds xl. Game was bought after official servers was down, so I couldn't even reach Nintendo WFC menu before. Now with the WFCreplay and NoSSL codes finally i get into that. According to altWFC wiki, I Should go to options menu and erase NWFC configuration, what I could not do, couse erase option was shadowed, and actually there was nothing to erase. then go to Nintendo WiFi Connection Setting and setup connection with 104.131.93.87 DNS adress for both Primary and Secondary. Firstly i couldn't even save those settings, but then I read about port forwarding so I opened given TCP ports, but don't know how to allow all traffic to all destinations in UDP, so maybe problem is there, but offcial Nintendo page shows that everything should be fine. Ok, going to end this story. Finally i could save connection settings, and even tested it. This test shows that connection has been established. Then I continued my game i tried to connect with Nintendo WiFi Club (others also) in Pokemon Center and game shows well known error(for me) 20100. My suspicions goes to two thing. First is wrong AR Code, couse I have european version of PKMN White 2 cartridge, but found only Code for USA ver. and second maybe those UDP ports forwarding. Sorry for my English;)

**Comment by JzargoTheMage** [comment]
Could you clarify and confirm a few things for me?
- What system/emulator are you playing the game on? Any action replay?
- Official Nintendo page? Link? I'm pretty sure they don't show the old DS/Wii servers. 
- I don't think any ports have to be forwarded, could you explain?
- Saved connection settings, good. Connection established, good. What specific features of the games were you trying to use?
- WFCReplay creates a new AR code based on the rom you put in, so you shouldn't have to find one.

**Comment by henias** [comment]
Ok, It was all about to UDP Ports. I forwarded all. DMZ Firewall options helped on my Router settings and now it works fine. Finally!
*I use 3DS XL system with Action Replay probably DSi with 3DS compatibility.
*Nintendo page I've used https://www.nintendo.com/consumer/network/en_la/network_status.jsp or http://www.nintendo.co.jp/netinfo/en_US/index.html
*I tried to use WiFi Club and GTS, so according to pkmnclassic.net I used things which should work, but didn't.
*Port forwarding. This is what I said, that helped. Firstly given TCP Ports(those ports are given on this github wiki in troubleshooting page) were forwarded, and it helped to establish connection, but didn't help when i went to pokemon center and wanted to connect with GTS or WIFI Club. Then DMZ Firewall options with forwarding UDP all traffic in all destination helped. I'm after first trades with my friend!
*About WFCReplay. I use European version of Pkmn White 2 so, I thought, that NoSSL codes for US Ver. would not to work with EU ver., but it works fine.

NOW My friend has a problem. We traded yesterday our mons form Pokemon White to Pokemon White 2. Today he wanted to connect in HeartGold to GTS, but same error 20100. What can I say, He didn't forwarded ports yesterday, but it works fine(with W2/W). He uses original cartridge, so he use action replay dsi.

**Comment by henias** [comment]
Continuing problem of my friend. Pokemon White was played on some flashcard, so it was rom, and he used NoSSL code and it works fine, but then, we tried Heart Gold, Platinum and Black 2 everything are original cartridge's with Action Replay DSi(nossl codes) and it's not working! Same error 20100, we tried Platinum on r4 and it works, originals doesn't. That's sad;(
