### ISSUE TITLE
problem registering peoples friend codes on brawl

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#224]
i was trying to brawl my friend we put eachothers fc in our games but neither game would register  the fcs,  he could register other people im not sure  if i can, why wouldnt our games register eachothers fcs  we put them in right 4 times and it still wouldnt register

**Comment by sepalani** [comment]
Is your friend using the same game region as you (NTSC-U?, PAL?, NTSC-J?, NTSC-K?)? Are you connecting to the same servers (i.e. the ones from this repository, not a fork)?

**Comment by ghost** [comment]
we are on different servers can the two servers not read eachother

**Comment by sepalani** [comment]
If they don't share the same database, they probably can't.
