### ISSUE TITLE
Ghosts and Rankings

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#225]
Hey main project devs, Wiimmfi has a public beta of ghosts and rankings, coded by Leseratte and hosted by yours truly. Why not packet dump it?

**Comment by kyle95wm** [comment]
Because you told me on Skype not to?

**Comment by ghost** [comment]
"Why not packet dump it?" I'm not giving the code out, you have to all design the server.

**Comment by kyle95wm** [comment]
True but you did tell me not to packet dump when the server was first being designed for Wiimmfi but now you're saying we can? Is the beta server still requiring a DNS? Or has it moved to Wiimmfi yet?

**Comment by ghost** [comment]
I told you not to because it was private beta. It's now public beta, it still requires a DNS.

**Comment by AdmiralCurtiss** [comment]
This is just wasting everyone's time, if people already have the logic why not at least document it instead of forcing dumb workarounds?

**Comment by ghost** [comment]
because the code author refuses to share the code, and I agree with his decision.

**Comment by kyle95wm** [comment]
is anything going to be done about this?

**Comment by ghost** [comment]
Do you want to code it?

**Comment by ghost** [comment]
OK, I am working through documenting the SAKE and RACE servers for MKW.
http://wiki.tockdom.com/wiki/MKWii_Network_Protocol/Server

**Comment by ghost** [comment]
@AdmiralCurtiss you'll be happy to know that @Leseratte10 will release the sourcecode once Wiimfi's PHP SAKE/RACE is complete.

**Comment by Leseratte10** [comment]
Wait a second, I said I MIGHT release it, not I WILL release it ...
