### ISSUE TITLE
All of my games freeze upon entering the Action Replay code

### ISSUE THREAD

**Issue by cerberus97** [barronwaffles/dwc_network_server_emulator#229]
So I tried using the WFC Patcher to get Action Replay codes, but as soon as I enter the code in my game the game just freezes. I tried it with Pokemon White, White 2, Black 2 and Heartgold, on Desmume v0.9.10.

Pokemon White is the only one which doesn't freeze immediately, but once i click on Nintendo WFC settings, it freezes too.

**Comment by cerberus97** [comment]
So I got Pokemon Platinum working with the codes, but once I did the settings and clicked on Test Connection it gives me error 50099

**Comment by cerberus97** [comment]
I got it working by using the ssl Patcher instead of the action replay codes.

**Comment by JzargoTheMage** [comment]
Did you create a code for each game, or make one code and use it for all of them?

Glad you got it working, though!

**Comment by cerberus97** [comment]
Different codes for each game, of course.
