### ISSUE TITLE
Error page admin

### ISSUE THREAD

**Issue by sergitab94** [barronwaffles/dwc_network_server_emulator#231]
The administradorador page is not working properly. I don't know it can fail. Any suggestions?
-Twisted version 12.2.0 and 15.5.0 (I tried both).
-Python is 2.7.0. 

![cut](https://cloud.githubusercontent.com/assets/16195794/11638005/e0342fa4-9d24-11e5-8c4c-92763a269072.JPG)

**Comment by SMTDDR** [comment]
https://github.com/polaris-/dwc_network_server_emulator/blob/master/admin_page_server.py#L267

That apostrophe needs to be removed.

![conan](https://cloud.githubusercontent.com/assets/3526592/11648380/befb6826-9d28-11e5-83cf-a75589744803.jpeg)

**Comment by sergitab94** [comment]
OMG!!! I didn't saw the apostrophe.
Case close, detective Conan!! :laughing: :+1:
