### ISSUE TITLE
DS Server Forum

### ISSUE THREAD

**Issue by TDoomX** [barronwaffles/dwc_network_server_emulator#233]
Hey fellas,
I'm recent user of this stuff and I want to organize all of it. The owner of these things wants to create a forum? I searched a tool to create a free forum without payment and found this:
http://www.forums-free.com/en/

Anyone wants this too?

Regards.
Doom

**Comment by JzargoTheMage** [comment]
I asked about this previously, but the general consensus was that the community was not large enough yet to warrant a forum

**Comment by TDoomX** [comment]
I think that is not a problem because more people are coming and with a forum it will be more organized and visible

**Comment by JzargoTheMage** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/117

This was the previous discussion on having a forum, if you were interested

**Comment by TDoomX** [comment]
Hmm...  Gotcha, I'm user of xat chat, we can organize this if wanted. Think about

**Comment by TDoomX** [comment]
http://xat.com/PolarisDSWiiServer
The xat
