### ISSUE TITLE
When will be avaliable the Pokémon's trades by Friend Code?

### ISSUE THREAD

**Issue by Sedhaild** [barronwaffles/dwc_network_server_emulator#234]
The GTS works perfectly! but when will be avaliable the Pokémon's trades by Friend Code? because, it's impossible to see all the pokémons in a game, and with the GTS we can only trade pokémon that we already saw.

**Comment by mm201** [comment]
Wi-fi club worked last I checked. (But GTS Negotiations is currently broken. See https://github.com/polaris-/dwc_network_server_emulator/issues/162 )

**Comment by Sedhaild** [comment]
In Wi-fi club, when I try to trade with a friend, the link between us never gets complete... and now after some trys I can't even enter wi-fi club, in HeartGold, I got "error 61010" always.

**Comment by chardrich** [comment]
I already tried the Wi-Fi club on hg to ss and black to white (vice versa) and I don't have any problems except automatically disconnects after trading. On the other hand, if you try hg/ss to /dp and pt it automatically disconnect.

**Comment by carlosenam** [comment]
Chardich, i have tried to trade by WiFi club beetween hg and diamond but 80430 appears. I saw the altwfc log, and its like it cannot match something...

**Comment by chardrich** [comment]
Sometimes I also encounter that kind of error. But randomly, I can trade Pokemon except battle. Try restarting on emulator or in real DS.

**Comment by Safraann** [comment]
No Solution ? I have exactly the same problem for HS to SS battle or trade. I have created a post if someone has a solution :)
