### ISSUE TITLE
How do you suggest one acquires ROMs ?

### ISSUE THREAD

**Issue by Psychmonk** [barronwaffles/dwc_network_server_emulator#238]
I know that downloading them is illegal.  The nintendo ROM laws say that copying devices are illagal and earlier states, though, that a backup copy is okay. How do I legally and in a good way get a ROM of a game I would like to patch with AR?

**Comment by AdmiralCurtiss** [comment]
The correct way would be to acquire a DS flash card of some sort and dump them using WoodDumper.

**Comment by ddugovic** [comment]
Uploading or distributing ROMs is illegal; on the other hand, it cannot be expected that a downloader knows what they are downloading or where it came from.  I agree with @AdmiralCurtiss , it seems the only way you can know that the ROM was legally produced & obtained is to produce it yourself.

**Comment by ghost** [comment]
Yet you have to get a flashcart, which are illegal to buy or sell in UK and other places.

**Comment by ddugovic** [comment]
Arguably by trial and error you could hand-type every bit of the ROM file (using a binary file editor) until you successfully produce the ROM file.  But using special hardware is probably easier.

**Comment by AdmiralCurtiss** [comment]
I, uh... what? If you mean randomly generating data and hoping you get a valid ROM, the chances of that are astronomically low.

**Comment by the4anoni** [comment]
There are rom dumpers. Example of usb rom dumper is sms4....
