### ISSUE TITLE
Club Penguin Elite Penguin Force

### ISSUE THREAD

**Issue by Peteerh** [barronwaffles/dwc_network_server_emulator#239]
Hi.

I succesfully use you new DNS server, but in the game Club Penguin Elite Penguin Force, i can't use any function in the Wifi menu. I can't download mission, or upload coins. I've got a message: Mission download failed, or coin upload failed. What can I do? Please help me!

**Comment by mm201** [comment]
My gut tells me there's either a gamestats server or 3rd party server we haven't implemented.

**Comment by Peteerh** [comment]
I see, And could you implement?

**Comment by Peteerh** [comment]
You can see one of the functions which don't work right now in this video: https://www.youtube.com/watch?v=TICyGmZzhCY&feature=player_embedded

I want to work this function(Mission download) again. I miss so much :(

**Comment by ghost** [comment]
I bet it used gamestats for upload coins, and I bet it used SAKE for mission downloading, or maybe SAKE for both. @Peteerh if you can, create a network dump?

**Comment by Peteerh** [comment]
How can I create a network dump?

**Comment by ghost** [comment]
If Windows, use Leseratte10's good tutorial http://forum.wii-homebrew.com/index.php/Thread/54993-How-to-setup-mkw-ana-on-windows/ (ignore mkw-ana part and just send the dump)

**Comment by Peteerh** [comment]
Okay thanks I will do it tommorrow. Good night.
