### ISSUE TITLE
Black screen in some DS games with WFC 

### ISSUE THREAD

**Issue by chardrich** [barronwaffles/dwc_network_server_emulator#240]
I patched Professor Layton and the Curious Village with WFCPatcher.exe but when I tried on my real DS through Wood R4 v1.62 waiting for few seconds to load and the game did not respond (in Desmume emulator it runs smoothly). But the sequel diablolical box series, run smoothly and it has no problems in retrieving DLC.

Also in Megaman Starforce 1,2 and 3 (any version)
Tetris Party Deluxe.

you can add some games that appear as black screen on real ds

**Comment by the4anoni** [comment]
Try use Action replay codes on r4i. Wfcpatcher have some issues on r4i (i have 2015 model). Action replay codes works for me.
