### ISSUE TITLE
Error 85030

### ISSUE THREAD

**Issue by janoflan** [barronwaffles/dwc_network_server_emulator#241]
I get this trying to set up a WFC match with Mario Kart DS, I assume it's because there are no other opponent's available? Or is it a fault with my setup?

Is there somewhere to exchange friend codes or is there not much of a community for this yet?

thanks

**Comment by chardrich** [comment]
Mario Kart DS works on me both Wood R4 and emulator. Try using the AR code instead of patch. And I'm looking forward to exchange friend codes with you.
my Friend code is 176093 695591

**Comment by janoflan** [comment]
Hi there,  think I've fixed it. A firewall issue with my router. 

My friend code is 493921 275671
