### ISSUE TITLE
Error Code 52100

### ISSUE THREAD

**Issue by PayneXIII** [barronwaffles/dwc_network_server_emulator#242]
Connected to Access Point but unable to connect to Server, is anyone else experiencing this on either of the 2 DNS servers on this site?

**Comment by kyle95wm** [comment]
It's probably just you. My server is online and reachable. May I ask what game/console you're trying to connect with?

**Comment by PayneXIII** [comment]
I'm attempting to play Metroid Prime Hunters and I'm using DeSmuME with a tweaked firmware and a wired connection. Is this just something I can do with either an R4 card or an Action Replay?

**Comment by kyle95wm** [comment]
Ds emulator huh? I've used them on my server before to test the ban system on MKDS. You really should stick with a physical console.

**Comment by PayneXIII** [comment]
I would rather do the physical console since I have the game and everything to do it but I lack the R4 card and I really don't trust other websites. But I've considered the Action Replay method since I'm sure I can get those from a local shop

**Comment by PayneXIII** [comment]
As a side question, would this work with the 3DS Action Replay on a 3DS system or would the DS(i) also work on a 3DS system? Thanks

**Comment by the4anoni** [comment]
There isn't any 3ds action replay. There is Ds(i) Action replay with support for 3ds...

**Comment by PayneXIII** [comment]
Yeah you're right, the other thing was a save file modifier for the 3DS
