### ISSUE TITLE
Professor Layton and the Curious Village (US Version) Error code 31020

### ISSUE THREAD

**Issue by chardrich** [barronwaffles/dwc_network_server_emulator#243]
![2002 - professor layton and the curious village u micronauts _34_15887](https://cloud.githubusercontent.com/assets/16173179/12089261/fbfd6778-b31d-11e5-981d-250ab25dfd19.png)

The issue in retrieving Weekly Puzzles in Professor Layton and the Curious Village (U) is having a error 31020 as shown in image below:
I used the WFCReplay code of the game (although if you patch through WFCPatcher.exe, the game freezes in R4 and works fine in emulators). Is the game itself is not compatible to the AR code?

**Comment by the4anoni** [comment]
Try EUR rom.

**Comment by tolkwes** [comment]
I'm also getting the same error code when using a game patched with SSLPatcher on an R4i Gold SDHC. WFCPatcher causes the game to freeze on a black screen, and the WFCReplay code cause the game to freeze on a white screen.

**Comment by barronwaffles** [comment]
@tolkwes - I've had similar issues in the past - join the [#altwfc](https://qchat.rizon.net/?channels=altwfc) IRC channel when possible and I might be able to help you find a solution.
