### ISSUE TITLE
ERROR 20101

### ISSUE THREAD

**Issue by Juan1087** [barronwaffles/dwc_network_server_emulator#244]
Hi, (First, sorry for my English)can anyone help me with this Error code: 
![error 20101](https://cloud.githubusercontent.com/assets/16520176/12146651/8607c408-b473-11e5-8a8a-2a0df35e5c31.png)
I have configured all (patch ROM, Infrastructure in WIFI settings, BIOS and Firmware, etc).
Actually, i successed to complet the conection test. But when i try to conect from the ROM option it shows me the Error 20101.
Details: Windows 7 Starter SP1 32 bits
Desmume 0.0.9 svn0 x86-JIT (i execute it as Administrator);
Winpcap 4.1.3 (i allowed it all permission in my firewall settings)
I'll thanks any ideas!!

**Comment by chardrich** [comment]
Try using the earlier version of desmume (0.9.7). If didn't work, try to get the game's AR code.

**Comment by Jhoseph12** [comment]
Creo que debe estar en mantenimiento el servidor a mi tampoco no me deja entrar u.u

**Comment by chardrich** [comment]
Maybe they having a maintenance or the server is down. All of WFC games are not working right now.

**Comment by Juan1087** [comment]
Thank you two for the answers. Probably they are having maintenance, but i think my problem is on the Port Fowarding. Due to a bug in Windows 10 I can´t access to 192.168.1.1 and verify if the ports are open.

**Comment by kyle95wm** [comment]
My server isn't undergoing any maintenance

**Comment by Juan1087** [comment]
Thanks for confirmation. I supposed that.
