### ISSUE TITLE
Error Code :: 20100 & 52200 On Desmume Emulator ( Pokemon White (NoSSL)

### ISSUE THREAD

**Issue by Cessius** [barronwaffles/dwc_network_server_emulator#245]
Firstly - After Patching My Rom I See "(NOSSL)" at the end instead of the original "(AltWfc)

Second - When I start the (NOSSL) ROM and go to WFC setting and start a new connection I am able to find the SoftAP Access point - However upon trying to connect to it I get the error "20100"

Third - Upon further inspection of the Troubleshooting  page I ignored the error 20100 and edit the DNS & Alt DNS to 104.131.93.87 Then tested the connection and I got error code "52200" 

Fourth - Upon inspection of the troubleshooting page again I Tried Restarting the Emulator several times, each time re-entering the WFC settings but the same errors keep popping up.

N.B - If it's the Pokemon White ROM that's not being patched properly does anyone know where I can get one that can be patched, please and ty.

**Comment by chardrich** [comment]
The NoSSL patch is working on me even the AR code courtesy of WFCReplay. Try resetting the WFC configuration and create another new Access Point. That should be worked.

**Comment by Cessius** [comment]
The "Delete Nintendo WFC setting is greyed out for me"

**Comment by Jhoseph12** [comment]
El server esta en mantenimiento no corre ningun juego a nadie

**Comment by love6985** [comment]
I also see same problem, It happen just 3 day ago
I can't connect to WFC although try 2 PC with 2 network diffenrent.

beside, trade or battle by "friend code" (mid girl in pokemon-center) not working, although it show connect, I waiting long time (about 1h) and not have anything come...

http://photo.ssc.vn/images/8752015_12_28_20_02_13.jpg

**Comment by ThePlantPrince** [comment]
Hey, for some reason I'm getting an Error Code: 20099, what can I do to fix it?

**Comment by carlosenam** [comment]
love6985 have you traded pokemon by friend code with desmume before?, which DNS you have?

**Comment by carlosenam** [comment]
I installed an AltfWFC on my own computer and I have been trying to use trade by friend code for days. But its not working.
