### ISSUE TITLE
error 20101

### ISSUE THREAD

**Issue by benjajb** [barronwaffles/dwc_network_server_emulator#248]
it used to work but now it doesn't.
I've been trying to get it to work all day with all sorts of different games, consoles, AR codes , flashcarts, rom patches and wifi access points, all of which used to work.
my game is patched, configuration reset and DNS setup, but it still doesn't work.
I keep getting 20101 and very rarely 20100.

**Comment by Jhoseph12** [comment]
El servidor esta en mantenimiento, o seguro ya lo cerraro o estan buscando cambiar de DNS

**Comment by carlosenam** [comment]
That probably means the traffic is high in the server.

**Comment by kyle95wm** [comment]
Both servers are reachable

**Comment by carlosenam** [comment]
Kyle95wm I can't use GTS with the server 104.131.93.87. I had to create my own server.

**Comment by kyle95wm** [comment]
Did you give the second server a try? That one is hosted by me. 104.131.93.87 isn't

**Comment by carlosenam** [comment]
you server is 45.55.80.156?

**Comment by kyle95wm** [comment]
Yep. It's located in NYC

**Comment by carlosenam** [comment]
Sure i gave that server a try, but GTS didn't work.

**Comment by kyle95wm** [comment]
yeah idk what to say. I guess the devs of the ALTWFC source code never had much thought of focussing on Pokemon. I'm sure the server works fine for MKW and Smash but as far as DLC goes idk what games work and what games don't work.

**Comment by carlosenam** [comment]
Yeah I know AltWfc was not designed for pokemon games specifically. It is because of that, I had to install a pkmnfoundations server, and now I have access to the GTS.

**Comment by carlosenam** [comment]
But Wifi Club doesn't work :(, I need wifi club trade

**Comment by Jhoseph12** [comment]
A mi no me funciona el server hace ya dos semanas y como hago para pkmfoundations???

**Comment by carlosenam** [comment]
Jhoseph el pkmnfoundations es lo que hace que el GTS funcione, solo el AltWfc no es suficiente

In English: Jhoseph AltWFC server is not enough, you need pkmnFoundatios too in order to make GTS work

**Comment by Jhoseph12** [comment]
Aya pero actualmente el servidor no funciona esta en mantenimiento o ya se lo bajaron, como hacer para conectarte??

**Comment by carlosenam** [comment]
yo lo que hice fue hacer un servidor propio de GTS y lo estoy usando :D

**Comment by chardrich** [comment]
It seems altwfc is already working. No more error 20101 for now. I already tried downloading the DLC on Yu-Gi-Oh 2009.
