### ISSUE TITLE
Downloading DLC freezes Picross DS.

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#250]
Downloading DLC for Picross DS freezes the game and flashcard.
Everything else works.

**Comment by ghost** [comment]
Perhaps the server doesn't have those DLC?

**Comment by ghost** [comment]
[Here](https://github.com/polaris-/dwc_network_server_emulator/wiki/Nintendo-DS-Download-Content) it says that DLC for Picross DS is available. I dunno.

**Comment by ghost** [comment]
I think I can see why. They're sending text files.

```
info_cl.txt rzDpMLcwwzCvMMVgMVjVMKEwpDDrMA**    Info            522
ClassicMpInfo.txt   3jDqMKowbjDUMK8w7TC5MMVgMVjVMKEwpDDrMA**    MP  Info        1948
ClassicN1Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgAxAMVgMVjVMKEwpDDrMA**    N1  Info        1466
ClassicN2Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgAyAMVgMVjVMKEwpDDrMA**    N2  Info        884
ClassicN3Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgAzAMVgMVjVMKEwpDDrMA**    N3  Info        888
ClassicN4Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgA0AMVgMVjVMKEwpDDrMA**    N4  Info        888
ClassicN5Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgA1AMVgMVjVMKEwpDDrMA**    N5  Info        888
ClassicN6Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgA2AMVgMVjVMKEwpDDrMA**    N6  Info        888
ClassicN7Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgA3AMVgMVjVMKEwpDDrMA**    N7  Info        888
ClassicN8Info.txt   1DCvMO0wuTAu-zD-VgBvAGwALgA4AMVgMVjVMKEwpDDrMA**    N8  Info        888
```

**Comment by AdmiralCurtiss** [comment]
That's accurate though, I remember looking at Picross DS and 3D specifically and they just use text files to indicate which puzzles are available for download.

**Comment by AdmiralCurtiss** [comment]
Although, is that all the server is sending? There's also supposed to be a bunch of *.pmp files that are the actual puzzles.

**Comment by ghost** [comment]
I used the list function from DLS1, and that's all that I received, so yes, that's all it's sending.

**Comment by ghost** [comment]
EDIT: I was wrong, the PMP files were sent when I used my DLS1 downloader.

**Comment by chardrich** [comment]
Thats impossible. I got the content in both Picross Ds and 3d.
