### ISSUE TITLE
My AltWFC is not reachable in LAN

### ISSUE THREAD

**Issue by carlosenam** [barronwaffles/dwc_network_server_emulator#251]
Hi All

I have an AltfWfc server in a linux host, I configured dnsmasq to 192.168.1.6 so just computers in my LAN can connect to my server. But when I try to connect Desmume from other computer in the LAN, the error 52100 appears. The other computer has Windows 8. What can I do for this?

Thanks in advance

**Comment by love6985** [comment]
Everyone can't connect to WFC (about 2 week recently), not effect by IP LAN.

**Comment by RiccardoRoscilli** [comment]
My AltWFC server works great
52.48.186.241
give it a try

**Comment by carlosenam** [comment]
RiccardoRosciIIi, your server has GTS (pokemon)?

**Comment by love6985** [comment]
//RiccardoRoscilli: your server cannot working on both my pc =(
http://photo.ssc.vn/images/1882016_01_18_13_02_52.jpg

**Comment by RiccardoRoscilli** [comment]
ok try now, still have to tune up the server

**Comment by love6985** [comment]
I try it again and connect to AP-soft success, 
however still can't  connect to your server.
http://photo.ssc.vn/images/8022016_01_18_20_31_48.jpg
are you test it success?

**Comment by RiccardoRoscilli** [comment]
yes, I can connect with real nintendo DS console (mario kart)  but cannot connect with desmume.

**Comment by carlosenam** [comment]
love6985 are you trying to connect via Pokemon?, you want to use GTS?

**Comment by love6985** [comment]
//carlosenam: No, from 2 day ago, GTS have active, I can use GTS nomally. No problem

I want to say that, I want use "WiFi-Club" (mid girl in PC)
http://photo.ssc.vn/images/2222016_01_20_2_06_38.jpg
to trade or battle with my friend through "friend code", but it not working :(
And you? are you can using WiFi-Club?

**Comment by carlosenam** [comment]
I have the same problem man

**Comment by carlosenam** [comment]
Solution: in the /etc/dnsmasq.conf uncomment the line that says "dhcp-range=192.168.1.50,192.168.1.150,12h". this activate the DCHP server function of Dnsmasq. Then restart the service: "sudo service dnsmasq restart". That's it!.
