### ISSUE TITLE
PKM-Wifi-Club not working

### ISSUE THREAD

**Issue by love6985** [barronwaffles/dwc_network_server_emulator#252]
Following this info https://github.com/polaris-/dwc_network_server_emulator/wiki/Compatibility
Wi-Fi Club can working on pokemon gen 5,
but I trying many times and it not working :(
I waiting a long time and not have anything come.

http://photo.ssc.vn/images/5102016_01_18_13_21_13.jpg
Can you help me fix this issue?

//edit: exactly, I want use "WiFi-Club" (mid girl in PC)
http://photo.ssc.vn/images/2222016_01_20_2_06_38.jpg
to trade or battle with my friend through "friend code", but it not working :(

**Comment by mm201** [comment]
Add a DNS entry to your server: `pkvldtprod.nintendo.co.jp` / `191.236.98.208`

**Comment by carlosenam** [comment]
mm201 your solution is for Pokemon heartgold (gen 4) too?, which server is 191.236.98.208, a nintendo server?

**Comment by mm201** [comment]
It's my server. And no, the `pkvldtprod` server is only used by Gen5.

**Comment by carlosenam** [comment]
so Wi-fi Club doesn't work in Gen4?

**Comment by mm201** [comment]
Works for me.

**Comment by carlosenam** [comment]
I have a AltfWfc server and a pkmnFoundations server in a linux(apache + mono), when I try to trade pokemons via Wi-fi Club, the game shows me the 80430 error. Do you know what issue is happening there?

**Comment by mm201** [comment]
No, not specifically. I haven't had much chance to debug PCN on Linux so you may want to check that everything's working alright.

Also, PCN only provides GTS, battle videos, and the other stuff in that building to Gen4 games. Wi-fi Club is all AltWFC.

**Comment by carlosenam** [comment]
GTS works fine. When I try to trade pokemon via Wifi Club AltFWC make some GameSpy request, but I don't understand that requests....

**Comment by carlosenam** [comment]
Hey mm201 i was looking in the log file what is the problem, and I found out the problem is like time out. The two clients (two desmume in a virtual box) loss the connection.

http://photo.ssc.vn/images/525Selecci_n_004.png

**Comment by love6985** [comment]
/mm201: I using Desmume and your server not working = =
http://photo.ssc.vn/images/1462016_01_20_2_24_29.jpg

**Comment by mm201** [comment]
Restart your game. https://github.com/polaris-/dwc_network_server_emulator/issues/30

**Comment by love6985** [comment]
maybe this is result :) https://github.com/polaris-/dwc_network_server_emulator/issues/253
