### ISSUE TITLE
Is someone able to trade by Wifi Club in pokemon (Gen4)?

### ISSUE THREAD

**Issue by carlosenam** [barronwaffles/dwc_network_server_emulator#253]
I want to know if someone is able to trade by Wifi Club?

thanks in advance!

**Comment by Jaco2** [comment]
I can´t. I always get 81010 error in pokemon platinum

**Comment by love6985** [comment]
I can, 
about 13h (GMT)  ~ same as 8h.PM in my time (Ha Noi-Bangkok-Jakarta)
I can trade with you (heartgold)
add my skype: huynn21191

**Comment by carlosenam** [comment]
Which server you use?

**Comment by love6985** [comment]
//carlosenam: send me your IP server, I will try it

**Comment by Jaco2** [comment]
Carlosenam I use 104.131.93.87

**Comment by carlosenam** [comment]
love6985 it is  LAN server

**Comment by carlosenam** [comment]
love6985 are you using Desmume?

**Comment by love6985** [comment]
yes, I using Desmume, I run my server in linux but it unstable, so now I use 104.131.93.87

wifi-club able working in your server?

**Comment by carlosenam** [comment]
No, I can't trade pokemon by Wifi Club, the games shows me a 80430 error. are you able to trade pokemon by Wifi Club? I play Pokemon HeartGold and Diamond

**Comment by love6985** [comment]
I try trade with gen 5, While & Black 2 and it show: "Communicating. Please stand by..." last about 1 hour and not anything come. I try White 2 & Black 2 also see same issue --> not working

pkm gen4 I play HG & Platinum, tonight I'll try and feedback result for you.

**Comment by love6985** [comment]
This is result: 
http://www.mediafire.com/watch/bntb44zp9jbpk9s/Wifi-Club_HG_%26_Platinum_not_working.mp4
I try to connect Wifi-club in gen4 HeartGold & Platinnum, and same as gen5, it not woking.

**Comment by mm201** [comment]
Try using real DSes.

**Comment by love6985** [comment]
//mm201: in real DS, is it working?

**Comment by mm201** [comment]
That's what I tested with. Desmume is riddled with bugs and some games just don't work.

**Comment by carlosenam** [comment]
love6985 Thanks for testing, I know real DS will work, I think is because the ingame name, in Desmune, ingame name is always PaRaDoX. Maybe if someone will compile another bios to Desmume with a different ingame name, Wifi Club will work.

**Comment by Jaco2** [comment]
I use a real ds, ds lite with a flash card r4 and i cant use the wifi club either. I dont know what kind of problem is, i always get 81010 error

**Comment by carlosenam** [comment]
Jaco2 are you using just one real DS?

**Comment by Jaco2** [comment]
No, two a friend and i use a real ds and we both get the same error as soon as we enter to the wifi club and choose the battle option

**Comment by the4anoni** [comment]
Try on other network...
