### ISSUE TITLE
Any support for COD: World at War?

### ISSUE THREAD

**Issue by Blazinvoid** [barronwaffles/dwc_network_server_emulator#254]
Will there be any support for W@W in the near future? Honestly my sibling is really hoping to play online once again. If not, oh well.

**Comment by jasonjimnz** [comment]
I think that the CoD Saga on Wii, does not use the Nintendo Servers, for example you can play now Modern Warfare 3 online

**Comment by Blazinvoid** [comment]
Odd, I keep getting an error. "Unable to connect to the Call of Duty World at War servers. Please try again later."
