### ISSUE TITLE
Updating an old server

### ISSUE THREAD

**Issue by Dr-Wily** [barronwaffles/dwc_network_server_emulator#255]
There is a way to update server scripts after a first installation ? Should have to backup the DB file before ?

**Comment by carlosenam** [comment]
update the scripts? why?

**Comment by Dr-Wily** [comment]
Sorry update whole server engine

**Comment by carlosenam** [comment]
are you trying to make changes to the code?, just make the changes and rebuild the project, I guess the server is wrote in Python
