### ISSUE TITLE
Can't enter the server's IP adress after deleting WFC records.

### ISSUE THREAD

**Issue by Gabiusnewelius** [barronwaffles/dwc_network_server_emulator#256]
I keep getting this error every time I try to input the server's IP.
http://i.imgur.com/u4BPw5J.png

**Comment by AdmiralCurtiss** [comment]
Well what are the settings?

**Comment by Gabiusnewelius** [comment]
I've taken screenshots.
http://i.imgur.com/0f8b9gO.png
Tell me what you need to see.
I'm using AR Code for the bypass portion of the walk-through.
Before deleting the Nintendo WFC it used to be able to find the SoftAP network but not anymore after.

**Comment by chardrich** [comment]
Try to disable the AR code first. Connect first to SoftAP then either successful or fail connects try edit it. edit the Primary and Secondary DNS to server's IP. then save. If didn't work, it might the emulator's firmware image has a problem.

**Comment by Gabiusnewelius** [comment]
After disabling the AR code it worked and I could connect to SoftAP and then input the IP.
When I try to connect it gives me Error 50000.
Pic related: http://i.imgur.com/wiu04H1.png
Not sure exactly what to do about it since troubleshooting doesn't have a section on it.
If I re-enable the AR code it just gets stuck forever in Testing Connection with the signal bar staying red and never once becoming green.

**Comment by Gabiusnewelius** [comment]
Both WinPCap and Desmume are allowed by Firewall, run as administrator and yet I still get error 50000. Any ideas?

**Comment by Gabiusnewelius** [comment]
Scratch that, managed to make it work, but now I have another issue, I keep getting Firmware: save config - failed in the Output window. I've tried using other firmware and restarted the game multiple times but it won't go away. Because of this I keep getting Error 52200 because my connection doesn't save on restart. Anyone have any ideas?
