### ISSUE TITLE
Trading in Gen 4 doesn't start

### ISSUE THREAD

**Issue by Gabiusnewelius** [barronwaffles/dwc_network_server_emulator#258]
I manage to make it so my 2 characters can intact, and I manage to get the message "Player contacted you!" then it gets stuck at this screen until it resolves itself and I can move the characters again but no Trade window opens. Any ideas? I get "Player failed to respond..." after some time but I don't get any error message.
Here is the picture of the trading message after which the trade window should open, but it doesn't.
http://i.imgur.com/GnqKBFF.png

**Comment by Gabiusnewelius** [comment]
To be able to trade am I supposed to set up my own server?

**Comment by love6985** [comment]
I also don't know why, but seem Wifi Club (active by friend code) only working on real DS (or maybe no)

you can refer at https://github.com/polaris-/dwc_network_server_emulator/issues/253

**Comment by the4anoni** [comment]
Desmume doesn't work because thre is too big ping... Topic to close....
