### ISSUE TITLE
Error Code 94020

### ISSUE THREAD

**Issue by Gabiusnewelius** [barronwaffles/dwc_network_server_emulator#262]
It's an error I get when trying to connect to the Wi-Fi server.
It's not in the troubleshooting section, any idea what causes this?
Pic related:
http://i.imgur.com/82JGHsa.png

"Communication Error.
You have been disconnected from Nintendo Wi-Fi Connection.

For help, visit support.nintendo.com
Error Code: 94020"

**Comment by the4anoni** [comment]
https://github.com/polaris-/dwc_network_server_emulator/wiki/Troubleshooting :p
