### ISSUE TITLE
ERROR 20100/20101

### ISSUE THREAD

**Issue by arevaloo** [barronwaffles/dwc_network_server_emulator#264]
I tried for 3 days enter to GTS of pokemon soulsilver with desmume wifi. 4 days ago i could connect to GTS and i can exchange pokemons but now appears error 20100/20101 depends of the IP that i write. The connection test in settigs of CWF is succesful but when i enter in the GTS in the game appears the error.
i cant understand why one day works and the next day no.
 I try connect to 104.131.93.87.
Sorry for my english, i'm spanish.

Thanks

**Comment by Saiyaken-PHOENIX** [comment]
Same here, I got the same problem.  I'm using a real DS-Lite with NoSSL-modded roms on an R4i 3DS RTS flash cart.  I've tried with Pokemon Platinum, Soul Silver and White 2 with no results.  20101 is the error I keep getting.

**Comment by hbrickface** [comment]
20101 is the latest error I'm getting. Now in Picross 3D.

I tried different servers, using different routers, using different games over days.

The error number keeps changing but this stuff never actually works. I'm using a Nintendo DSiXL with Action Replay device.

**Comment by hbrickface** [comment]
Yeah I tried the BeanJrFi server and I got a different error code, 52100.

I guess it's hopeless.

**Comment by Saiyaken-PHOENIX** [comment]
I see the Pokemon Classic Network site at http://www.pkmnclassic.net is linked-up with you guys at AltWFC, and there hasn't been an update to the GTS or battle videos since Monday, February 8th.  I don't think it's only a few users... It might be out for everyone.

**Comment by hbrickface** [comment]
From that page: "There seem to be a lot of support requests lately so I'd like to point out that Wi-Fi Club isn't working on Desmume. Problem's on their end."

I don't play Pokemon, but... does this explain why I can't download Picross DS / 3D DLC for several days now? It's because altwfc servers are broken?

**Comment by Saiyaken-PHOENIX** [comment]
I believe the servers are either broken, or that they're modifying something inside it.  Even then, someone would've let someone know about it, somewhere.  I'm getting nothing from anyone.
Wish more people knew about this...

**Comment by hbrickface** [comment]
Hmm.. I hope the servers are fixed soon!

**Comment by Saiyaken-PHOENIX** [comment]
Same here, seeing that you're having problems on your end and me on mine, across different games...
I don't think Mario Kart DS is working for me, neither.

**Comment by hbrickface** [comment]
altwfc status at http://104.131.93.87:9001 has changed - it's no longer showing exceptions and the number of players dropped back to zero. I think maybe it's fixed now? I can't try right now, but will later.

**Comment by hbrickface** [comment]
It works!!!

**Comment by Saiyaken-PHOENIX** [comment]
Thanks for the update, will try ASAP.
