### ISSUE TITLE
[Pokemon HG] Can't fight, no response from server / friend

### ISSUE THREAD

**Issue by Safraann** [barronwaffles/dwc_network_server_emulator#269]
I've not problems about connecting to CWF Nintendo with this ip : 104.131.93.87. But when my friend and me are in the Wifi Friend Room (with the right friend code) we can't fight or trade pokemons. When i ask him a fight or trade with the computer, we wait 2 / 3 minuts but there isn't response. 
Thanks in advance and sorry for my accent, i'm french :3
If you need a video for better explications, i can record it :)

**Comment by Safraann** [comment]
This is a video to show my problem
http://www.mediafire.com/download/bntb44zp9jbpk9s/Wifi-Club+HG+%26+Platinum+not+working.mp4

**Comment by mm201** [comment]
Desmume doesn't work. 90% sure the problem is on their end.

**Comment by Safraann** [comment]
So which other emulators (with wifi abilities) do you suggest to use ?

**Comment by mm201** [comment]
There are none. You need to use a real DS.

**Comment by Safraann** [comment]
And there isn't really no solutions ? Desmume could not have a fix about it ? I saw many videos on youtube which explain how to process to play wifi via desmume.

**Comment by the4anoni** [comment]
You can't use desmume because there is high ping... Topic to close...
