### ISSUE TITLE
Is server in maintenance?

### ISSUE THREAD

**Issue by dfwashere** [barronwaffles/dwc_network_server_emulator#271]
I'm playing in desmume... 5 gen, pokemon black, but, for making the national pokedex, I need to trade with white, and transfer pokemon from 4gen games. Everything was fine, I was playing soulsilver and heartgold, I made some changes with firmware, bios9-bios7, but at the end, It still worked... I was playing heartgold, made one trade, played for a while, but suddenly it stopped working, I restarted adjust the DNS codes to 104 131 93 87 as always (I always have to do, and this cut me of from having an stable friend code, but I got use to it) and everytime I had the error It got solve by restarting and rewriting the DNS code,  but I did the same this time and didn't work, I tried a lot of times, I tried then with soulsilver and 5gen games, with another wifi configuration, I tried a lot of stuff but it simply don't work... Is it me? any desmume config? I have to download again the firmware and all those stuff? or is it just a simple server maintenance and patiente is all I need?

**Comment by mm201** [comment]
Seems it crashed last night. Should be back to normal now.

**Comment by dfwashere** [comment]
I just tried again, still not working..52000 error.

**Comment by dfwashere** [comment]
I've found the solution, it was an issue with the file Firmware.dfc  I just look for information about 52000 error on youtube, and found a file, download it, and that fixed it. CLOSED
