### ISSUE TITLE
Can't 'Erase Nintendo WFC Configuration'

### ISSUE THREAD

**Issue by Fetalini** [barronwaffles/dwc_network_server_emulator#272]
Hello! I've been trying to get the WiFi to work on my emulator (Desmume 0.9.7 - an emulator that previously could connect to Nintendo's servers until they were shut down) to do some trading with a friend in Pokemon Soul Silver. I've tried following all the steps in the tutorial to connect again, but I am stopped dead at the part where I have to load into the Options and "Erase Nintendo WFC Configuration". It and "Transfer Nintendo WFC Configuration" are grayed out. I figured it was a step I could just negate since I reinstalled the emulator fresh and didn't have a WFC configuration. But, upon trying to continue the process, I got an error "These settings are invalid". So, I figure my issue is back to the fact I can't erase the WFC configuration. I'm not honestly sure where my exact issue may be, but I would appreciate any guidance in the matter. Thank you in advance!

**Comment by ghost** [comment]
Are you on default settings in the WiFi options?

**Comment by Fetalini** [comment]
I changed my settings from "Ad-hoc" to "Infrastructure" and selected my adapter from the list, if that is what you mean?

**Comment by ghost** [comment]
I mean like change back to completely default settings the way it was when you got the game, then try to erase xD

**Comment by Fetalini** [comment]
Are you saying the settings in the emulator or the ROM? Sorry if I'm not following exactly.

**Comment by AdmiralCurtiss** [comment]
Double check your IPs, IIRC there's something non-intuitive with how the DS handles less-than-three-digits IP octets that causes this message. Try adding or removing leading zeroes or something of the sort. Post a screenshot of your setting if you still have issues.

If the delete option is greyed out it means there's nothing to delete.

**Comment by Fetalini** [comment]
When I put the IPs in, even adding a leading 0 before the 93 and the 87 in the IP address, it still says invalid settings. I did notice that when I put the 0s in, they disappeared.

At least I know the step about the delete option being grayed out isn't the problem. That helps! Now to find the _actual_ problem xP

Here are some screenshots of what I have for the emulator's WiFi settings as well as what I put into the ROM
https://i.gyazo.com/546d0003f9c736159a07145c71e25c14.png
https://i.gyazo.com/78c6a4cb0b05d0034403e48ab8ff0d3a.png

I appreciate everyone's help so far x3

**Comment by ghost** [comment]
Change all the WiFi settings back to default manually, like change the WiFi connection settings back like when you first got the game you're trying to play.  maybe it will still work xD

**Comment by Fetalini** [comment]
I don't understand. It's a brand new install of the emulator and the ROM doesn't have a save on it currently (as the instructions I followed [here](https://github.com/polaris-/dwc_network_server_emulator/wiki) said to delete saves), so it's technically "new" as well? So, you want me to change the WiFi settings on the _emulator_ to default?

**Comment by Fetalini** [comment]
Got it working, finally. Closing topic. Thanks all who tried to assist!

**Comment by NaturalHarmonia** [comment]
What did you do to get it to work? @Fetalini
