### ISSUE TITLE
Set Redirect Using Router Instead of Patching Rom/Action Replay?

### ISSUE THREAD

**Issue by Wolke-Puppenspieler** [barronwaffles/dwc_network_server_emulator#273]
I'm wondering if it'd be possible to redirect the stock WFC connection attempt to your server using the functions of a home gateway/router, instead of using  a patched ROM or Action Replay?

Theoretically, I would just need the original WFC IP and set a redirect, no?

**Comment by mm201** [comment]
You still need to patch your ROM to disable the certificate check.

**Comment by kyle95wm** [comment]
If you want to reduce the steps, set your router's DNS to that of one of our servers which can be found on the wiki page. All you'd need to do is patch your game

**Comment by ghost** [comment]
Using the DNS on the router is stupid because then all traffic is forwarded through it.
Plus, if just using a DNS was how we could do it, why would we patch it for HTTP? If we didnt have to patch we'd have a lot more users, but Nintendo aren't that dumb.

**Comment by JzargoTheMage** [comment]
Though, connecting like that is a nice idea. I believe PokeCheck used to use a system like that before it went under permanent maintainance with the release of Pokemon's Gen VI. By changing the DNS settings it would somehow forward to their servers rather than the official ones

**Comment by mm201** [comment]
Pokecheck did exactly what we do, only it was just for the gamestats server which has no security. The nas server has an https certificate check which we can't defeat without some kind of game modification.
