### ISSUE TITLE
Not really an issue, but wanted to share this for everyone

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#274]
http://mariokartds.chatx2.whocares.jp/ This is a chat I created that's easy to use. Everyone can talk about Pokemon/Mario Kart DS in the chat and arrange matches, etc. To enter, click the very top left button. In the first box, type your username and click the button on the bottom of the third box to enter.

**Comment by the4anoni** [comment]
Why it is in japanese ? And i also ask why you don't made irc istead  of "japanese chat" ?
But that is very good idea :) Sorry for my bad english...
