### ISSUE TITLE
Disconnected from server right before race starts (Mario Kart DS)

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#276]
I have been trying to play and actually got someone (I'm named Tar), and we've tried to do it three times and it disconnects both of us before the race starts.

**Comment by mm201** [comment]
Are you both using real DSes?

**Comment by ghost** [comment]
Yes, original DS phat. I've now played 2 GPs with this guy, felipe. It error codes 91010 randomly every so often.
