### ISSUE TITLE
[Error 61010] after disconnection issues

### ISSUE THREAD

**Issue by StingMcRay** [barronwaffles/dwc_network_server_emulator#279]
Dear AltWFC Hosters,

After a good connection the last 3 day's (till yesterday) i get now on Pokemon Black Version 2 the error 61010 (Unsupported Game according the Troubleshoot page). This happened after a connection break down between my Nintento 3DS XL and DeSmuMe on my computer when the 2 tried to communicate with each other and an other error number (i don't remind me what number that was) and my nintendo 3ds got a wifi failer/internet disconnection. (in Wifi Club Room)

Before that i could use the GTS and i came in the wifi club room with my 3DS, the emulator is still able to connect to the server, and does not produce errors.

Is there an solution to fix my 3ds to get connected again (like request a new FC) or other things i need to do (my 3ds has a Action Reply DS(i) with the codes to bypass the official WFC)

Regards,
Braveboy

**Comment by 0Zeromus0** [comment]
Erase ur WFC Configration can solve this problem,but you will lose all fc of all ur games, you must get your fc again and some game you will lose ur friend list either! plz be certain!
