### ISSUE TITLE
[ERROR 20100] DS WI-FI Settings give success but game doesnt?

### ISSUE THREAD

**Issue by Lyriati** [barronwaffles/dwc_network_server_emulator#280]
Whenever I test inside the nintendo wfc settings and hit test connection, it says successful, yet when I load up PKMN-BLACK2 it gives me error 20100. WHAT?

**Comment by kyle95wm** [comment]
What type of encryption is your wifi?

**Comment by BraveboyTSL** [comment]
I set is to WEP Encryption (128 Bit), else i could not connect with the old ds connection settings

**Comment by Lyriati** [comment]
It's open. I don't use security settings because i live in like the middle of nowhere.

**Comment by Link2738** [comment]
Did you change the dns to the server you want to connect to?

**Comment by Lyriati** [comment]
Yes. If I didn't then how would I get connection successful? lol

**Comment by Link2738** [comment]
And a dumb question, did you use the action replay code for the game.

**Comment by Lyriati** [comment]
I used the wfcpatcher to patch my game, I then loaded with a flashcart.

**Comment by Link2738** [comment]
Hm...... I'm don't know much about the way the flashcart's work sorry.

**Comment by MjSonic1** [comment]
I have the same problem as Mrguggy except when ever I connect to Nintendo WFC (on Mario Kart DS) it says "Connecting to Nintendo WFC. Please wait a moment." I waited an hour and thirty minutes for that thing to connect on my DS Lite. Does anyone have a solution to this, please?

**Comment by the4anoni** [comment]
AltWfc and Pkmn Classic Framework are separate servers... Thats problaly (sorry for my bad english...) maintenace on pkmn classic....

**Comment by mcdelarosa** [comment]
I need help too, I have a 3ds and play Pokemon Diamond, but if I try to connect my 3ds (in ds modus) in my hotspot, which hasn't security, It looks like it were successfully connecting but it gives me the same error 20100.
I've been searching, why it doesn't connect, and people says it's because of the Nintendo Servers that aren't working anymore.
Could someone help me please?
