### ISSUE TITLE
Looking for people for pokemon battles

### ISSUE THREAD

**Issue by pipiris24** [barronwaffles/dwc_network_server_emulator#281]
Hello. Great server, I have made trades by the GTS using my pokemon platinum retail card (it was a hard but finally I get conected.
It should be a place for people to exchanges friend codes for battling and trading.

my FC is 3221 2258 9042
Leave yours to start a match

**Comment by ghost** [comment]
1417 3394 9494

**Comment by pipiris24** [comment]
Battle right now?

**Comment by ghost** [comment]
im in the wi-fi room

**Comment by ghost** [comment]
hm....

**Comment by pipiris24** [comment]
I'm coming

**Comment by ghost** [comment]
hm....

**Comment by ghost** [comment]
can u see me?

**Comment by ghost** [comment]
????

**Comment by ghost** [comment]
u failed to respond then u left the room

**Comment by pipiris24** [comment]
I'm trying to join.

**Comment by ghost** [comment]
i got a message saying u failed to respond  then ur sprite  teleported out of the room

**Comment by ghost** [comment]
i reconnected to the room

**Comment by pipiris24** [comment]
My game is a retail card I have to use a action replay I restart my game and I must restart if I get 52200 error code

**Comment by ghost** [comment]
now i get a message that says this : no response.
either the player has been disconnected or you have been removed from the players friend roster.
error code: 80430

**Comment by ghost** [comment]
thats  very sad i wanted to battle gen 4 is my favorite gen

**Comment by pipiris24** [comment]
Can we talk through Facebook or Skype? I'm joining again

**Comment by ghost** [comment]
yeah whats ur skype

**Comment by pipiris24** [comment]
Im in the room

**Comment by pipiris24** [comment]
Search Pipiris24@hotmail.com

**Comment by pipiris24** [comment]
I'm in the union room

**Comment by AdmiralCurtiss** [comment]
This is not a forum or chat room.
