### ISSUE TITLE
23404 on ALTWFC and BeanJrFi

### ISSUE THREAD

**Issue by rkalz** [barronwaffles/dwc_network_server_emulator#283]
Been trying to connect to either of these servers all day on real carts with Action Replay to no avail. I know the patch codes are working because I get 20110 when I removed my AR. There is no WFC data saved on this DS Lite. 

Any idea as to what's going on?

**Comment by ghost** [comment]
BeanJrFi is not supported here - contact @kyle95wm himself.
It appears the virtual host is having issues.
