### ISSUE TITLE
Problem with FFCC:EoT on R4.

### ISSUE THREAD

**Issue by evilpol** [barronwaffles/dwc_network_server_emulator#284]
Hello there,

I've tried to play Final Fantasy Crystal Chronicles: Echoes of Time with my friend. We both have DS Lite consoles. I've got R4 SDHC Revolution, my friend - old, original R4 with Wood R4 kernel v 1.62 and YSMenu installed.

After patching, game works fine for me (i need to enable cheat and turn on "save data fix"), but my friend can't see cheat menu. On clean ROM, she can turn on cheat, but after ssl-patching, the cheat menu disappears. Without "fix", she can't save the game data and go "online".

Is there anything we could do?

**Comment by the4anoni** [comment]
Use acekart 2i :) This is better card than totay r4i dual-core 2016...
Acekart have only one problem: it won't support dsi with 1.4.5 FW but You have ds lite ,so you can use it :)
Ps. If you want i can send you Akaio with newest cheat database and loaders :)
