### ISSUE TITLE
Problem with FFCC EOT ON NDS,ERRCOD:86420，80430

### ISSUE THREAD

**Issue by ougontaiyo** [barronwaffles/dwc_network_server_emulator#285]
Excuse me,I am a NDS player,when I was playing FFCC EOT with my friends ,we match a problem.
we can't join each other's rom and the screen appears an errcod:86420,sometimes 80430,
We want to know whether the problem is on the server or on us

**Comment by 0Zeromus0** [comment]
Here is up's friend ~(≧▽≦)/~.
It just occurred these days,but now ,I can make a connection between my nds and wii,when nds as a host ,wii as a guest, it can't be sucess when wii as a host.about after i tested this ,all guys cant connect to eachother any more.we wanna konw what happend and hope u can fix this as soon ,thanks.
