### ISSUE TITLE
Action Replay code

### ISSUE THREAD

**Issue by Paffo** [barronwaffles/dwc_network_server_emulator#286]
Hello,
i've tried connect to this alternative server first with the emulator, then with the Dsi.
With the emulator i've picked up Pokemon black, used WfcPatcher to patch it and it worked, i connected to GTS online without problem.
Then i tried to generate a code for the game with the rom, moved the code to my Action replay and setup everything on my DSi, but it doesn't connect me, it gives an error.
I've tried the generated code on the emulator on pc and it just freeze the game.
Same thing append to pokemon HG.
Why does the WfcPatcher works, but the code generated with WfcReplay doesn't?

**Comment by ghost** [comment]
If you're using a HTTP-patched ROM and a HTTP-patching AR code, it's obviously going to crash..

**Comment by the4anoni** [comment]
@Paffo What region are your games ?
