### ISSUE TITLE
Can someone please help me

### ISSUE THREAD

**Issue by bronzeelf** [barronwaffles/dwc_network_server_emulator#289]
I'm very confused on all of this. So I have a few questions:
1. Can I use my cartridge for this?
2. In Animal Crossing Wild World I go to my Nintendo Wi-Fi connection setup but I get this error when pressing "Save Settings" : "These settings are invalid. Confirm the information and try again. Call . . . in the USA and Canada for help"
3. I know I need action replay but do I ALSO need a rom? I recently bought a new cartridge and would not want it to go to waste. :/

**Comment by Link2738** [comment]
If you have an actual cartridge then you need an action replay and the code for your game.
(Details on the wiki)
If you have a flashcart also see wiki.
But i'm not sure about the "These settings are invalid" part. what setting are you trying to use?

**Comment by bronzeelf** [comment]
@Link2738 I'm in the AC:WW Wifi settings, I put in the IP and all that and it gives me a Phone number to call. I have no wifi connections set up on my DS because it says my connection info is incorrect or something (even though I checked my computer and the password for the connection I'm using IS definitely correct)

edit: I figured it out thanks :)

**Comment by bronzeelf** [comment]
@Link2738  but wow thats relieving, I thought I'd have to essentially "steal" (which I'm not about)

**Comment by bronzeelf** [comment]
@Link

**Comment by bronzeelf** [comment]
@Link2738  I realized it's because I don't have the action replay code in yet, I didn't even buy the AR yet, I thought I had to do this part first. Ok so any specific action replay I need to get? Or do all of them work. I've literally never used an AR before in my life
