### ISSUE TITLE
Patch and Save Compatibilities / Action Replay Hang

### ISSUE THREAD

**Issue by MichaelLawrenceDee** [barronwaffles/dwc_network_server_emulator#290]
You guys have given 2 possible ways but both have a different issue.
I had to use VirtualBox in order to make my Wi-Fi connection into wired.
Now I got Desmume 0.9.7 (Wi-Fi support) running in a Windows XP environment but I had to do all processes in my 8.1 itself. My rom is Pokemon Diamond.
1. Action Replay Code: hangs the game as soon as it is on.
2. Rom Patching: Deletes my Save File (I have renamed the .dsv Save File) So how do I convert to and fro?
Any suggestions? I would prefer for the 1st issue to work.

**Comment by MichaelLawrenceDee** [comment]
Um... Anyone?

**Comment by the4anoni** [comment]
Which rom version you have ?

**Comment by MichaelLawrenceDee** [comment]
Rom version? All I know is it's Pokemon Diamond.

**Comment by the4anoni** [comment]
Us ? Eur ? Or other

**Comment by MichaelLawrenceDee** [comment]
US.

**Comment by the4anoni** [comment]
Try this code on clean(non patched) rom 
520CD848 EE070F90
E2000674 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB88
D2000000 00000000

**Comment by MichaelLawrenceDee** [comment]
Thank you. I'll recheck on this, as well as the rest of the Pokemon Games.

**Comment by MichaelLawrenceDee** [comment]
So it seems that my rom is not clean. This is the exact code that I got from WfcReplay.v0.7
Is there any way to remove any patches from my rom or converting my save file for the clean rom?

**Comment by Prof9** [comment]
The DeSmuME 0.9.7 Wi-Fi build is based on DeSmuME build r3947. Action Replay DS codes generated by WfcReplay are not compatible with DeSmuME versions earlier than r5047 due to a faulty implementation of some ARDS code types in DeSmuME. So WfcReplay will not work for this specific DeSmuME build.

**Comment by MichaelLawrenceDee** [comment]
I see... So that's what keeps making it crash/ hang. I hope there could be another alternative to this... :(
