### ISSUE TITLE
Animal Crossing Wild World-specific patcher?

### ISSUE THREAD

**Issue by bronzeelf** [barronwaffles/dwc_network_server_emulator#291]
So when I have my action replay in my DS Lite, I can enter Animal Crossing: Wild World(US) just fine, I entered the code beforehand, and I go to where I change WFC. My game saves, but then enters a black screen. I've waiting at least 10 minutes(edit: like an hour now) here with this black screen thinking it must be a long loading time but I don't think so. Anyone have this problem? Please help me

Additional Question: what's the difference between the normal game and ADME, on the codelist menu screen. I usually go for the normal game without [ADME] but I tested it on both and have the same problem

EDIT: new issue is to find a wfcpatcher that works with ACWW

**Comment by sebastienrouget** [comment]
As you can see on [WcfReplay repo](https://github.com/Prof9/WfcReplay), _Animal Crossing: Wild World_ is incompatible.

**Comment by bronzeelf** [comment]
Oh no D: I didn't look at that. How are people getting on? On Wiimmfi public stats it shows that there have been 38 FC profiles created. Not advertising servers or anything b/c i cant connect to any but somehow there has to be a way for it to work... but how

**Comment by kyle95wm** [comment]
I'm sure Wiimmfi has a guide for DS

**Comment by bronzeelf** [comment]
It uses the same guide as altwfc. This is a specific patcher problem, not about wifi, but idk where else to post about this

**Comment by MinePlayersPE** [comment]
I found out that people got on AC:WW using WFCPatcher, not WFCReplay.
