### ISSUE TITLE
BeanJrFi server error code 84020 plz help :)

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#293]
Hi there I was trying to Play Mario Kart Wii on the BeanJrFi server it connects to the server successfully so I chose the game mode I want to play and Kart when it starts looking for opponents looks like the game is about to start when it pops up a error code 84020 could any won tell me how I can fix this and if its just the server down than plz explain to me why its down thx :)

**Comment by kyle95wm** [comment]
My server isn't down. Granted I havent tested it with anyone lately, but I recently started using IPTables on my server to secure it better. It sounds like a NAT issue

**Comment by ghost** [comment]
When can you fix this NAT issue Just wondering when you can I would be happy to help test if the server is working I wont be able to test it with Mario Kart Wii but I can test it with Pokemon – Battle Revolution and maybe Super Smash Bros Brawl if I can get that game working again and by the way thx for replying :)

**Comment by djcjf** [comment]
I am doing some hacks on the game Mario Kart Wii so I cant play till I am done with it :)
