### ISSUE TITLE
Ok Honestly, what am I doing wrong???

### ISSUE THREAD

**Issue by PlayfulMaggot09** [barronwaffles/dwc_network_server_emulator#295]
OK. So first of all, I'm using an Action Replay on my 3DS and i have the AR Code for pokemon platinum. I start up the game and enter all the stuff as in wifi, (I did reset my settings or whatever) I put the right DNS in the Primary and Secondary slots, and I can tell the code is working because it doesnt work without the AR and it works with the AR. In the settings it succeeds, yet when I go to the GTS it says I need to make the profile and then it gives me 20100. Help please? I've been stuck here for hours. I can use this with desmume just fine, I get 3 bars then it stops at the last second. In Desmume its 2 bars, i'm not sure if i'm in some weird network or what but I just want to connect. Am I using the wrong SSID? The wrong AR code, please list those if you can.

**Comment by PlayfulMaggot09** [comment]
I managed to make it past the 20100, now I'm currently trying to load in and it gives me 52200, however it doesn't prompt me to create a new wfc.

**Comment by PlayfulMaggot09** [comment]
Back at 20100, but my Nintendo WFC is created, somebody help?

**Comment by dmoeenm** [comment]
20100 is probably a problem with your connection

**Comment by dmoeenm** [comment]
And i think the first few times you try to log on will give you that error because i also got that error

**Comment by dmoeenm** [comment]
Also you might have entered the code wrong it seems wierd but check that your worse case scenario is that is a problem with your save file in platinum and you'll need to delete your entire save
