### ISSUE TITLE
Transformers Autobots/Decepticons AllSpark Wars,Multiplayer

### ISSUE THREAD

**Issue by PlayerGameSK** [barronwaffles/dwc_network_server_emulator#297]
Hello,

It's not really an Issue but I just want to ask. Do this also emulate the Nintendo Wi-Fi? Or just the Local Multiplayer? As I would like to get the bonus stuff for both,Transformers Autobots and Transformers Decepticons which you can only get by playing online. And also,if it would be possible,is there someone who would like to play with me?

Also,I tried the Local Multiplayer but the game that was "joining" was just "Searching..." and nothing happened,so I suppose this game is not supported,or am I doing something wrong?

Thanks :)

**Comment by the4anoni** [comment]
It emulates wfc ,not local play :) But it may dont work with some games

**Comment by PlayerGameSK** [comment]
Can somebody please try out Transformers Autobots/Deceptions for me? The Allspark Wars gamemode I mean.
