### ISSUE TITLE
Are we can dream about playing on altwfc without nossl patch ?

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#298]
By question i mean why we cant implement ssl certificates to server ?

**Comment by Dr-Wily** [comment]
Ask to Nintendo for his private key ;)

**Comment by the4anoni** [comment]
I thinked about reverse enginering ;)

**Comment by mm201** [comment]
We either:
- Find a vulnerability in the DS's SSL client implementation,
- Run a huge distributed computing project to factor the RSA modulus, or
- Beg and plead with Nintendo to either release their private key or sign some certificates for us. (lolno)

**Comment by sepalani** [comment]
Unless Nintendo give their own private key, breaking the Nintendo RSA key is another method but mostly illegal in many countries.

**Comment by the4anoni** [comment]
@sepalani thats why i ask ... Im from Poland so for me this isnt a problem ,but what about ex .Usa...

**Comment by ghost** [comment]
It is still an issue as you live in an EU country. We'd need to get the former (SSL client implementation bug), but even then that wont be that helpful..

**Comment by the4anoni** [comment]
Poland is EU country :D ,but i know that in some EU contries ssl glitch can be illegal :(

**Comment by ghost** [comment]
Yes, Poland is an EU coutnry; and in the EU it's illegal, in EVERY EU COUNTRY infact.
