### ISSUE TITLE
stuck at connecting to nintendo wfc please wait a moment screen

### ISSUE THREAD

**Issue by dmoeenm** [barronwaffles/dwc_network_server_emulator#300]
I'm stuck at the screen on Mario kart ds that says connecting  to Nintendo wfc please wait a moment and i cant get to the match making screen this also happens to me in other games and i am getting a connection successful in the wfc settings i'm also getting three bars i configured every thing on my router so it would work but it has not i changed the channel  security mode changed it from wireless n to b and still nothing has worked i even rest my router so if someone could please help me that would be very nice.

**Comment by Dr-Wily** [comment]
You try to connect on an existing server or on homemade local server ?

**Comment by dmoeenm** [comment]
im trying to connect to this server altwfc so i guess an existing server

**Comment by Dr-Wily** [comment]
Try to install your own server just to see if the issue come from your network (router, ISP, or many others sthings...) or the WAN.
- take a Debian distro
- install a dhcp server on this distro
- follow setup wiki [here](https://github.com/polaris-/dwc_network_server_emulator/wiki/Setting-up-a-server-from-a-fresh-installation-of-Linux)
- plug your server to the wan port of your router (idealy a wifi router like Netgear WNRxxxx)
- test the connection with the DS

Let a feedback here

**Comment by dmoeenm** [comment]
wait how do i "take a Debian distro

**Comment by dmoeenm** [comment]
also im using windows not linux

**Comment by Dr-Wily** [comment]
Setup on Windows is more tricky. Use an old PC (or a Raspberry Pi) and donwload Debian. You can use [this tools](https://unetbootin.github.io/) to put Debian install on USB and install on the PC.

**Comment by Dr-Wily** [comment]
otherwise test the connection [on this server](http://wellby.dyndns.org/dnl/gk/ip.txt) (enter this IP in your DNS setting in DS wifi setup)

**Comment by dmoeenm** [comment]
Sorry to tell you so late but i forgot im using a physical ds and an action replay with an actual cartridge of mariokart i am not using an emulator but i didn't want to reply because i  hadn't tried this out aand i thought that maybe i could see if i get that to work if that would  have helped in someway

**Comment by dmoeenm** [comment]
Hey wily its working for me now
