### ISSUE TITLE
Mega Man Star Force 3 Error code 52000

### ISSUE THREAD

**Issue by ShaolinTurtle** [barronwaffles/dwc_network_server_emulator#302]
Despite putting the game through the SSlPatcher and loading the patched rom on my R4, The game will still not connect to Nintendo Wi-Fi, sometimes green bars are shown but eventually they disappear and go back to red.

Did I do something wrong? Can anyone else help me get this game connected? It's my all-time favorite DS title and I'd like to play online with some others.

Can anyone else try loading this game onto their R4 to see if they get different results?

**Comment by chardrich** [comment]
It's working fine on me. If error occurs, try restart the console. And I suggest you may try using AR of NoSSL instead of patch.

**Comment by ShaolinTurtle** [comment]
I'll keep at it, I'd love to Wave Battle sometime.
