### ISSUE TITLE
Can someone please help me get Mega Man Star Force 2&3 working?

### ISSUE THREAD

**Issue by ShaolinTurtle** [barronwaffles/dwc_network_server_emulator#306]
I've been trying to play the games with some friends for days now but I keep getting error codes like 52000, Mega Man Star Force 2 goes to a white screen when wi-fi play is selected on the R4 while Mega Man Star Force 3 behaves as it should, it just doesn't connect and reports error code 52000.

I'd really appreciate any help overcoming these issues.

**Comment by chardrich** [comment]
Megaman starforce 2 have problem in WFC Patch and AR code. I hope the developer will fix this soon. But on Megaman starforce 3, if error occurs, simply reset the console until you will able to connect. I have MMSF 3, can we have a wave battle? I'm waiting

**Comment by ShaolinTurtle** [comment]
do you have a discord or social media account? I'd love to play you in MMSF3 if we could get a proper chat going, I may need a bit of assistance.
