### ISSUE TITLE
Pokemon Black 2 DeSmuME not working?

### ISSUE THREAD

**Issue by gravvyb** [barronwaffles/dwc_network_server_emulator#311]
I have downloaded the WfcPatcher and put the rom through the executable. The nds file it created was identical to the original except for "   (NoSSL)   "  at the end of the file name. I have followed the instructions to set up the internet connection within the wifi menu in-game (entered my wifi SSID and WEP and the provided DNS).
However when I attempt to test connection, I get the message "Error Code 50009 No access point in range."

Please let me know if there's anything I am missing, or if the game, or the emulator itself isn't supported.
Thanks :)

**Comment by ductator** [comment]
You need to have a version of desmume with wifi support.
