### ISSUE TITLE
Pokemon HeartGold and SoulSilver doest not work with DeSmuME (edit now works)

### ISSUE THREAD

**Issue by herculys** [barronwaffles/dwc_network_server_emulator#318]
i tried to play pokemon soul silver online using this tutorial
https://github.com/polaris-/dwc_network_server_emulator/wiki
with 2 computers in my house connected to same router using desmume and wincap, got eveything working but when i enter in the wi-fi club, in game and start trading it took too long to conect until wi-fi conection go down.

i also created a server on a virtual machine ubuntu, got all working i had see both accounts on same wi-fi club but if tries to battle or trade someone lose conection.
if you want to play one of these games buy a nds, idk about others pokemon games.

**Comment by herculys** [comment]
![kmupfxk](https://cloud.githubusercontent.com/assets/8635798/17271457/b1190752-5652-11e6-84d0-fb0e43a8eb08.jpg)

**Comment by herculys** [comment]
![1](https://cloud.githubusercontent.com/assets/8635798/17274541/7ead1d3e-56bc-11e6-81ea-a246c9ba43a0.jpg)
![2](https://cloud.githubusercontent.com/assets/8635798/17274536/61e27280-56bc-11e6-9dab-c7736cf2c477.jpg)
![3](https://cloud.githubusercontent.com/assets/8635798/17274537/65ace652-56bc-11e6-8bfb-218e13c1ca74.jpg)

**Comment by herculys** [comment]
update tried GTS and it did work:
https://www.youtube.com/watch?v=urQxglHs7vc

**Comment by ghost** [comment]
If one DS can communicate to the other but not vice versa, only one can see the other. Plus as you are running it on the same network it could be a factor (plus emulator)

**Comment by bayurex** [comment]
how u do that? in my desmume gives error #23503

**Comment by ghost** [comment]
HTTP error is 503; the server is down/having issues.

**Comment by mm201** [comment]
Server hiccup. Try again now. I'm still tracking down the root cause.

**Comment by ghost** [comment]
Probably something to do with NAS having an issue on authentication (initial connection) considering it's 23XXX

**Comment by bayurex** [comment]
is server up now?

**Comment by FoxMcloud5655** [comment]
This can be closed now.

**Comment by ghost** [comment]
Can you please explain how you managed it?

Thanks
