### ISSUE TITLE
Error code 23404

### ISSUE THREAD

**Issue by Thepropper** [barronwaffles/dwc_network_server_emulator#320]
Im using virtualbox to emulate the ethernet cable connection and i keep getting this error... the emulated machine gets internet (i checked by using youtube)... so thats not the problem. And i think i did the desmume settings right.... so my question is? is the server 104.131.93.87 down or am i doing something wrong? All i want is to evolve my kadabra... and maybe later my graveler.

**Comment by herculys** [comment]
if youget conection sucessful
you need to go on GTS its on Goldenrod City 
https://www.youtube.com/watch?v=urQxglHs7vc
wi-fi plaza, wi-fi club aren't working.

**Comment by Thepropper** [comment]
Im using Pokemon Diamond. Im not getting conection succesfully... I keep recieving error 23404. I will try again later. Have you been able to connect to the server?

**Comment by herculys** [comment]
yes, im with pokemon soul silver

**Comment by ghost** [comment]
23404: Server sent back HTTP 404
It normally doesn't happen in practice

**Comment by MinePlayersPE** [comment]
Same here, except I'm using an actual Ethernet cable on my laptop!
