### ISSUE TITLE
pokemon heartgold 20100 error, help please?

### ISSUE THREAD

**Issue by wocjf5793** [barronwaffles/dwc_network_server_emulator#322]
I follow every description in this homepage. but i finally find error code 20100...

sorry for the poor english, cause i'm asian.

i also saw troubleshooting too. i try reset DNS setting, restart emulation. but same.

maybe server down? help plz..

**Comment by TheLastMelody** [comment]
Same problem with Pokemon Black. Leaving comment here so I know if the servers are down or I failed at patching the ROM. I'm running the game on a DS.

**Comment by wocjf5793** [comment]
![error20100](https://cloud.githubusercontent.com/assets/20861530/17461865/2c776dca-5cd5-11e6-9838-bfd04728153f.png)
![error201002](https://cloud.githubusercontent.com/assets/20861530/17461868/3014473c-5cd5-11e6-85c1-3b2377a8920d.png)

plus, i'm using cheat code patch. (wfcreplay)

**Comment by wocjf5793** [comment]
problem solved. my rom file was not patched well. so i find another korean heartgold rom file.

**Comment by ghost** [comment]
Close this issue please.
