### ISSUE TITLE
Wifi Pokemon Black Error 50000 Tryed everything

### ISSUE THREAD

**Issue by filipyking** [barronwaffles/dwc_network_server_emulator#323]
It's been three daysand i still can't have it to work

i'v tryed everything  admins, change wincap versions, change desmume versions

i tryed to add my ip manually and it still won't work

The dns 104 131 93 87 

and i can't have it to work, i would like to know if is is there anything i can do?

i don't mind playing without wifi connection , i just want to connect the game with my brother, both of us can't make it work

**Comment by calamity316** [comment]
Have you tried plugging your pc up to the router with an Ethernet cable

**Comment by filipyking** [comment]
It's the only way i have internet , i don't have a wireless adapter on my desktop

**Comment by noiraxen** [comment]
I have same problem I downloaded a different desmume here: http://www.mediafire.com/download/x5odqqph39oaurs/DeSmuME_PCAP_v1.2.zip 

And it worked, connecting to the server at test connection. I'm stuck at smthing else now(the real thing).

**Comment by jojo162** [comment]
what version of desmume do you have?
