### ISSUE TITLE
Request to add Fossil Fighters Champions

### ISSUE THREAD

**Issue by CryoKing96** [barronwaffles/dwc_network_server_emulator#325]
Would somebody be so kind as to add the Fossil Fighters Champions DLC. There are plenty of people who'd be thrilled if you did.

**Comment by ghost** [comment]
Do you have dumps of the DLC?
IIRC nobody can magically pull DLC out of thin air..

**Comment by CryoKing96** [comment]
I apologize, I really don't know the first thing about a lot of what you guys do. So what is a dump and how do I obtain it?
