### ISSUE TITLE
Fix 50000 51099 52200 52000 52100, avoid code missmatch.

### ISSUE THREAD

**Issue by noiraxen** [barronwaffles/dwc_network_server_emulator#326]
51099&52200 I am not 100% sure which exacly fixes which in some of these (I guess in brackets from memory) but 52000 comes before 52100 comes before 52200 comes before 51099 comes before celebration) : 
(52100/52000 in "test connection") {{Connect ethernet}}. Try changing IP between static and automatic.
(51099 in poke center) Go to 192.168.1.1 enter your router pass, go to wifi security and put from wpa wpa2 etc to open or wep. 
(52200 in poke center)Assign the static ip above the dns in pokemon wifi settings that is 10 higher than your PC (192.168.1.[PC number+10], you can get your pc at start->cmd>ipconfig/all. The mask and default gateway remain the same as in the cmd. 
(? Probably 51099)Turn windows firewall off. 
(? Probably 51099)Use some kind of registry cure.
(52200 in poke center) Make sure what you are doing is supported, if it isn't it will always be 52200, example is wifi plaza in heartgold.
(50000 in "test connection") Use a different  desmume if 50000 is in "test connection" this I don't know why but both where wifi enabled but the other one didnt work for me while this one was working fine (http://www.mediafire.com/download/x5odqqph39oaurs/DeSmuME_PCAP_v1.2.zip) and start over.
(52100 in "test connection") Use the correct dns server from alt wfc(104.131.93.87). It occurred when I used a different one.
(52100 in "test connection") Try changing IP between static and automatic. Connect ethernet.
(avoid code missmatch after using SSL patcher) Ctrl+R everytime you want to re enter.
(fix code missmatch after using SSL patcher) delete/reset nintendo saved wfc again in wifi options.

That's what I learned in past 2 days when I had an idea to play this.

**Comment by ghost** [comment]
http://wiimmfi.de/error?e=50000,51099,52200,52000,52100 :wink:
