### ISSUE TITLE
Help me, Error 20100, too many times.

### ISSUE THREAD

**Issue by PlayfulMaggot09** [barronwaffles/dwc_network_server_emulator#327]
I've been connecting to the GTS or at least trying to for the longest time now and been getting the same results in Error 20100, and I know the patcher isn't the problem because i've used it on desmume, and have done it before with the same code and same device. WEP is my Wi-fi type, everything should be fine, i'm connecting fine in the settings too.

**Comment by JaviSrG** [comment]
Could you solve your problem already?
becouse i have the same problem, thanks for reading.

**Comment by ghost** [comment]
20100 means either it cant connect to NAS or SSL is broken; how long does it take to get 20100? The DS tries a few times before failing..

**Comment by dmoeenm** [comment]
Hey are you still haveing this issue cause i could help
