### ISSUE TITLE
Hi, can anyone help me?

### ISSUE THREAD

**Issue by JaviSrG** [barronwaffles/dwc_network_server_emulator#329]
Hello everyone,
Can anyone upload the pokemon platinum patched rom please?
and second: can anyone say to me if the servers are Up or Down, thanks
sorry my english level is so basic.
Thanks for reading.

**Comment by ductator** [comment]
Use https://github.com/polaris-/dwc_network_server_emulator/wiki to create a patched ROM yourself.
After all it is copyrighted material and nobody is going to upload it for you.

**Comment by JaviSrG** [comment]
Hi, technically if you patch a game it can't be copyrighted, and second if i'm asking for roms is becouse i tried 3 differents methods.

**Comment by noiraxen** [comment]
http://www.filedropper.com/3541-pokemonplatinumversionusxenophobianossl
http://www.megafileupload.com/7nho/3541_-_Pokemon_Platinum_Version_(US)(XenoPhobia)_[NOSSL].rar

**Comment by JaviSrG** [comment]
Tnks you so much

**Comment by ghost** [comment]
Someone please close this and remove the ROM links.
