### ISSUE TITLE
Help Me i cant connect to altwfc

### ISSUE THREAD

**Issue by Gamerman5** [barronwaffles/dwc_network_server_emulator#332]
When i patch mario kart it patches but dosent want to connect i have a r4 NDS/NDSL but when i try to setup altwfc i get error 51300 everytime Plz help me so i can play online

**Comment by Jam64** [comment]
Did you check the Error Code lookup?

**Comment by Gamerman5** [comment]
Yeah Bit It Didnt Help

**Comment by chardrich** [comment]
Try using the AR code?
