### ISSUE TITLE
Pokémon White Memory Link Issue

### ISSUE THREAD

**Issue by NuggetBuster** [barronwaffles/dwc_network_server_emulator#333]
The main reason I wanted to have WiFi on the emulator was so I could have the memory link on Pokémon White 2. So on Pokémon White I needed to do the game sync but has been saying "Creating Data... Please wait a moment." for about 12 hours now. (I went to sleep and when I woke up it was still saying it.) Does anyone know why this is happening?

**Comment by NuggetBuster** [comment]
So about 5 minutes after making this it now says "Communication Error..."

**Comment by mm201** [comment]
It's not supported...yet. Use the local memory link for now.

**Comment by NuggetBuster** [comment]
How?

**Comment by chardrich** [comment]
Using DS wireless communications. A DS to another DS or 3DS.
