### ISSUE TITLE
Using with dolphin

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#335]
How do you connect to altwfc with dolphin?

**Comment by SilverSzymonPL** [comment]
i don't think you can. but you can use wiimmfi

**Comment by ghost** [comment]
I found a patcher that patches the iso to altwfc or wiimmfi. Wiimmfi works (I still have to wait 7 days) but altwfc gets error code 20100. I have set up the DNS.

**Comment by ghost** [comment]
It works now. My antivirus was blocking the DNS.

**Comment by SilverSzymonPL** [comment]
What? How does it work? I thought the homebrew channel only works on a real console!

**Comment by ghost** [comment]
If you really wanted to you could boot homebrew on dolphin. But you don't need homebrew for this. It works because it accesses the dns and you can change the dns in windows.

**Comment by SilverSzymonPL** [comment]
"Does the Steven Strange impression" Teach me!

**Comment by Maritoguionyo** [comment]
on the connection properties (windows) and on the ipv4 settings you can put the dns there.

**Comment by SilverSzymonPL** [comment]
Since the homebrew apps the main page mentions don't work and the ocarina code seemingly not working either this is so far my only way to connect, and idk where these settings are and whether it will screw up my computer's internet settings

**Comment by ghost** [comment]
Just use https://wiimmfi.de. There is an ISO patcher that patches the disk for wiimmfi. It doesn't need the DNS to be changed either. The only other thing you need to do is run this program: https://www.dropbox.com/s/pagcu7bfmtjce5z/Wiimmfi%20Unbanner.exe to allow connnection since Dolphin's original save format(I think) is banned.

**Comment by softestpoly** [comment]
Any news on this? I want to play MKWii with my friends who don't have Wiis. I set up DWC and It works on my real Wii, but Dolphin will not connect to the server at all with a patched ISO, but the connection test succeeds.

**Comment by Dr-Wily** [comment]
Can you give us your network config between Dolphin and the AltWFC server ?

**Comment by barronwaffles** [comment]
@sethseth6 it requires some method of SSL patching (either on the images or via Gecko code) and the DNS set on the network adapter.

**Comment by softestpoly** [comment]
I found out what happened: I couldn't get DNSmasq set up correctly, and I still haven't fixed it. It works locally with my machine's Dolphin and my Wii in my DMZ but not with my friend's Dolphin, my DNS isn't doing anything for them.

**Comment by Dr-Wily** [comment]
You must use a router between the altWFC server and your clients.

**Comment by softestpoly** [comment]
Oh, alright. I'll try normal port forwarding instead.
