### ISSUE TITLE
error 52100 for unknown reasons

### ISSUE THREAD

**Issue by SilverSzymonPL** [barronwaffles/dwc_network_server_emulator#336]
Hi, i'm using DesMuMe Wi-Fi. I want to play Pokemon White and i patched the game. i know i did it properly because i used the action replay program and it didn't detect any checks or anything like that. i put in my IP adresses and the proper DNS in both places (words are hard) and i was able to connect to the internet, but the error above still happened. i need help.

**Comment by SilverSzymonPL** [comment]
Here's a screenshot
![2016-09-08](https://cloud.githubusercontent.com/assets/22057754/18354350/80b26c68-75e5-11e6-8336-837e85076444.png)

**Comment by bayurex** [comment]
did u use lan cable/ethernet?
if no, maybe i can help u.
u can use hamachi(or something like evolve, tungle, etc) for virtual ethernet, link >> https://gbatemp.net/threads/desmume-wifi-with-wlan-using-hamachi-no-virtual-box.436107/

but it's give error 23503, i think server was offline.

**Comment by SilverSzymonPL** [comment]
it was online. well, now that i think about it, i set my adapter as the internet source, not a cable, and even it says that it will only connect with anything if the connection is wired. i guess i need to find the right cable.

**Comment by jaisgo** [comment]
i have the error 52100 but i using the r4 in my 3ds 
help me :(

**Comment by SilverSzymonPL** [comment]
Maybe it's not properly patched?

**Comment by SilverSzymonPL** [comment]
i figured it out

**Comment by MisterSheeple** [comment]
Ok? Well what did you do to fix it? Nothing I do works
