### ISSUE TITLE
Server doesn't work

### ISSUE THREAD

**Issue by Andyta2016** [barronwaffles/dwc_network_server_emulator#340]
Since 1 week ago, I can't connect to WFC, and the connection try always is bad

**Comment by joaoric** [comment]
me too :(

**Comment by jaisgo** [comment]
me too :(

**Comment by Andyta2016** [comment]
I have the error 23502, who else have this error?

**Comment by maknawer** [comment]
I have error 23502 too

**Comment by kevinrodolfo** [comment]
Me too...

**Comment by maknawer** [comment]
@Andyta2016 please try to change the title of the issue to mention error 23502, maybe that way we'll be more likely to get help

**Comment by chardrich** [comment]
It appears that the server randomly working or not. I'm not sure, everytime I try to find some players in Mario Kart DS the WFC is working.

**Comment by jaisgo** [comment]
What time?

**Comment by jaisgo** [comment]
Mario kart U ? E?

**Comment by chardrich** [comment]
I tried it every 8:00 am PST. @jaisgo I am using the US version.

**Comment by FlintFrisk** [comment]
I have the same problem

**Comment by mewoneplusone1** [comment]
Try Alternate servers cause they seem to be working I was having the same problem. But you need to make a new profile with a new friend code.

**Comment by Andyta2016** [comment]
I tried with BeanJrFi's DNS, but now I have a connection error, it shows me a blue screen with a message saying shut down and try it again D:

**Comment by Andyta2016** [comment]
Hey guys, the server is working again, I play Pokemon HG, if you want, my friend code is 2104 5339 8231
