### ISSUE TITLE
error 52200 

### ISSUE THREAD

**Issue by jaisgo** [barronwaffles/dwc_network_server_emulator#341]

**Comment by jaisgo** [comment]
help me :(

**Comment by syntax868** [comment]
I have the same problem when i try to connect to 104.131.93.87 or to my own server. Also http://104.131.93.87:9001 tells me "exceptions.OSError: [Errno 24] Too many open files", but sometimes it seems to work. It is possible to test the connection in wifi settings and recieve the friend code from the server. But then 52200....

**Comment by syntax868** [comment]
Here is the log of my server (Check connection, recieve friend code, connection failed (52200)
[server_log.txt](https://github.com/polaris-/dwc_network_server_emulator/files/505120/server_log.txt)

**Comment by kevinrodolfo** [comment]
Yeah, the server is like that since weeks.

**Comment by jaisgo** [comment]
Add me in Fb please i want to speak for NDS 
Javier Gómez Avendaňo

**Comment by jaisgo** [comment]
Javier Isaac Gómez sorry *

**Comment by mewoneplusone1** [comment]
The alternate servers still work though.

**Comment by syntax868** [comment]
Not for me, also get error 52200 with BeanJrFi (192.241.153.27) or a blue screen, that tell my i have to turn off the nintendo ds

**Comment by mewoneplusone1** [comment]
On BeanJrFi (192.241.153.27) the test connection works and so does wonder gift. But the GTS (aka the reason most of us are here for) gives me error 52200 and/or a blue screen of death.

**Comment by syntax868** [comment]
I think there's a problem with the "pokemon classic framework" but there are no issues on github with error 52200 on the pcf site (https://github.com/mm201/pkmn-classic-framework/issues).

Also there is only maintenance announced for Thursdays at 0300 UTC (http://pkmnclassic.net)
