### ISSUE TITLE
Error 23502 on desmume , Is server down? (pokemon)

### ISSUE THREAD

**Issue by Waboba** [barronwaffles/dwc_network_server_emulator#342]
i have tried with different desmumes, tutorials, etc to fix other errors, like 20100, 52000, but after completing all steps and recommendations I always end up with error 23502 when I´m about to connect to the GTS.
The game tells me that the server is interrupted or too overflowed, so, it might be possible that servers are down right now? if they are not, please help me.

**Comment by kevinrodolfo** [comment]
Yeah, the server is down... (I dunno why)
You can check in the ip from the server http://104.131.93.87:9001/
When you try to connect you get the error 52200.
You can also try other ip from other servers https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers

**Comment by mewoneplusone1** [comment]
The alternate servers are working but you need to create a new profile and friend code.

**Comment by chardrich** [comment]
The alternate servers you gave is not working.

**Comment by chardrich** [comment]
I might take some time fixing the server. Anyone notice the pkmnclassic website? Someone managed to deposit pokemon on gen 4 (hg, ss, d&p, platinum).

**Comment by Waboba** [comment]
yep. now I am getting error 52200 when I am connecting. what should i do?

**Comment by Waboba** [comment]
nothing. IT WORKED!

**Comment by chardrich** [comment]
Please close this thread. Happy playing.
