### ISSUE TITLE
20100 and 23502

### ISSUE THREAD

**Issue by Jam64** [barronwaffles/dwc_network_server_emulator#343]
Hello. 

I have been trying to connect to AltWFC for around 3 weeks now. I used to constantly get 20100 and was doing everything i could to fix it, i even called my internet company to reset my router to try to connect. I soon realised that i was missing a code and i put that into my gecko and tried again. It worked, i connected and played 1 race and then i had to leave for a camp (this lasted a week). When i came back 1 week later, i tried it again. I hadnt changed anything at all and i connected, 20100.  Fast forward to around 4 days ago when i realised the AltWFC servers were down (because of the statistics website).  I waited until the website was back up again and connected, 23502. What an odd error code, i had never seen it before and neither had 3 other hackers, one by the name of BeanJR.  He said the servers are still down because of the frozen statistics. I have still been trying to connect and constantly get 23502. I am using Mario Kart Wii by the way and i really would love someone to contact me by my skype instead of here. My skype is (jack.ponder2) with no caps or brackets.

Thanks
~Jam

Edit: I am PAL by the way.

**Comment by mewoneplusone1** [comment]
No one has been able to connect for weeks and we don't know why try BeanJR's alternate server that one seems to work on DS (not sure for wii).

**Comment by Jam64** [comment]
I tried, i even worked it out with him. I couldnt connect, 20100.

**Comment by Jam64** [comment]
@polaris-

**Comment by Jam64** [comment]
Will it ever come back up?

**Comment by Jam64** [comment]
The stats are frozen at
 Game ID    # Players
mariokartwii  
3
codmw2ds  
2

Last updated: 2016-10-08 01:26:55.076074

**Comment by damianexus** [comment]
now is working perfect, thanks

**Comment by Jam64** [comment]
Yep it is 💃
