### ISSUE TITLE
Please help me ^^

### ISSUE THREAD

**Issue by Aljen115** [barronwaffles/dwc_network_server_emulator#347]
Hello, Im new here. I just found out the project yesterday and I must say, you guys made a wonderful job bringing WFC back to NDS. But for some reasons, I cannot connect to the AltWfc server. I am using a 3ds with R4i white card to play 2ds games. Also I patched all the games with Wfcpatcher 1.6 and follow the steps here: https://github.com/polaris-/dwc_network_server_emulator/wiki (the "Erase Nintendo WFC Configuration" is gray for me). But for some reasons, I still cant connect to the server. I tried changing WPA/WPA2 to wep security or no security for my wifi at the same time but it still not work. Please help me! Thank you in advance.

**Comment by vigneshd332** [comment]
Keep ur wifi security open. And try connecting again. What error does it give you my friend?

**Comment by the4anoni** [comment]
Issue to close.
