### ISSUE TITLE
Problem connecting , help please!

### ISSUE THREAD

**Issue by AlexBirchi** [barronwaffles/dwc_network_server_emulator#349]
Hello i've been searching a lot about my error , found many like mine , but never a solution.

First, I am using a TP-Link Router (if that is important to know). 

I changed the security to WEP in order to connect to the DS, I patched my rom wich i have on a R4 card and i did every step. Introduced the DNS 104.131.93.87 , tested the connection and it works! But , when i am in game and i try using for example GTS, random battle , etc. but it won't connect, giving me the error 20100.

I tried it with Pokemon HG and Black 2 , doesn't work on both. I was wondring how can it be solved , do i have to do something to my router? Do i have to do something to my console ? Anything? Please answer , i really want to play via wi-fi with friends.

**Comment by Hauteknits** [comment]
Same here

**Comment by ghost** [comment]
it wont even work on retail cartridges using the wifi enabler  ar code i tried and it gets the same error as if the server doesn't exist

**Comment by the4anoni** [comment]
Server under maintenace. Try again.

**Comment by vigneshd332** [comment]
hey buddy listen.
you must have an android phone right, do this:

1. Disconnect router fron computer (not the internet cable. dissconect the ethernet cable.)
2. Connect phone to wifi on the router.
3. Use usb tethering and u will get 'local area connection x'(some number).
4. Bridge that connection with local area connection(your ethernet).
5. Keep tethering on and router on and just restart the computer.
6. It will work.

**Comment by the4anoni** [comment]
Use wimmfi ,altwfc doesn`t work correctly now....
