### ISSUE TITLE
Server down!?

### ISSUE THREAD

**Issue by celorodovalho** [barronwaffles/dwc_network_server_emulator#351]
Hi there!!

I can't connect since Wednesday, its giving error 25003.
Server offline?

**Comment by thiagobfiorenza** [comment]
+1

**Comment by celorodovalho** [comment]
Here:
http://104.131.93.87:9001/

We always seeing the same players:
syachi2ds	1
mariokartwii	1

Never changes.

**Comment by Bruno13Lance** [comment]
+1

**Comment by Korokato** [comment]
+1

**Comment by ruidemagalhaes** [comment]
Same problem here!

**Comment by jelufe** [comment]
Same problema here

**Comment by Valkristh** [comment]
Try the other server BeanJrFi

DNS: 192.241.153.27

FC is reset btw

**Comment by Linkgzm** [comment]
+1

**Comment by AlejandroGarciaHub** [comment]
+1

**Comment by OctoNezd** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/351#issuecomment-266569118
doesnt work

**Comment by fargot258** [comment]
Same problem, even without access

**Comment by bacanozx** [comment]
dial tcp 104.131.93.87:9001: getsockopt: connection timed out server down and 192.241.153.27 same

**Comment by OctoNezd** [comment]
Looks like there is something wrong with code...

**Comment by Valkristh** [comment]
Hey I'm connected right now to DNS: 192.241.153.27 in Diddy kong Racing its really working!

**Comment by celorodovalho** [comment]
New server: 45.55.238.131

Please join us.

**Comment by fargot258** [comment]
It proves with the platinum pokemon game, it does not connect me, at the moment of entering the GTS it gives me connection error

**Comment by Filius226** [comment]
DNS 45.55.238.131 don't work for me.

Seems like there is no info :/

**Comment by Filius226** [comment]
Any news about the server ? still down ?

**Comment by vigneshd332** [comment]
No buddy server is up and runnin

**Comment by vigneshd332** [comment]
No buddy server is up and runnin
