### ISSUE TITLE
Mystery Gift Pokémon Black/White Black2/White2

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#352]
Hello! I'm here because the mystery gift don't work in my pokémon BW/BW2, I have a DSI XL, they work on all games of the 4 gen., the GTS work too, in both gens.

**Comment by celorodovalho** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/351

**Comment by ghost** [comment]
Yes, but before the server crashes
