### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by fargot258** [barronwaffles/dwc_network_server_emulator#353]
Help, I tried to connect, but since November 7 I can not login to the servers, it gives me error 23502, apparently the server is down, my question is if it is going to work again, I tried the platinum pokemon game And pokemon Heart Gold but in both I get the same errors, I leave a screenshot, thanks and I hope they can help me
![pokemon_edicion_oro_heartgold_esp nossl _34_25819](https://cloud.githubusercontent.com/assets/24517581/21089776/73731b00-c000-11e6-87fd-fd9d680014db.png)

**Comment by celorodovalho** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/351

**Comment by AlejandroGarciaHub** [comment]
+1

**Comment by OctoNezd** [comment]
Try this DNS:62.109.29.237
This is mine server

**Comment by fargot258** [comment]
I proved it but it does not connect me

**Comment by bacanozx** [comment]
dial tcp 104.131.93.87:9001: getsockopt: connection timed out server down ?
