### ISSUE TITLE
Couldnt get mine server to work

### ISSUE THREAD

**Issue by OctoNezd** [barronwaffles/dwc_network_server_emulator#355]
DS says error 52100

**Comment by OctoNezd** [comment]
Looks like dns does nothing at all

**Comment by celorodovalho** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/351

**Comment by OctoNezd** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/355#issuecomment-267296828
You havent understood mine question,
I trying to dwc_network_server_emulator work on mine server.
But DNS on mine server reffer to nintendo.com from nintendowifi.net

**Comment by OctoNezd** [comment]
Looks like there is a issue with QR server
