### ISSUE TITLE
Error 13274 (again)

### ISSUE THREAD

**Issue by celorodovalho** [barronwaffles/dwc_network_server_emulator#356]
In my own server is giving this error when I connect in GTS.

Everything works fine, but this error still everytime I connect in GTS.

I restarted the server many times, can you help me?

**Comment by celorodovalho** [comment]
@sepalani can you help me? Please?
I think you and @AdmiralCurtiss are the most active members of this project, and I'm really need help with that. :(

**Comment by sepalani** [comment]
My work is completely unrelated to Pokémon GTS, so I'm helpless as I don't have these games. IIRC, GTS on altwfc is handled by: https://github.com/mm201/pkmn-classic-framework

**Comment by the4anoni** [comment]
Issue to close.

**Comment by celorodovalho** [comment]
@the4anoni can't close, is not solved yet.

**Comment by ghost** [comment]
Close it, and open it somewhere else, this is not the repo for this.
