### ISSUE TITLE
Mario Kart DS keeps connecting FOREVER

### ISSUE THREAD

**Issue by Avi2002** [barronwaffles/dwc_network_server_emulator#357]
Hi,
I'm running a dwc network server on my raspberry pi 3, when i test connection via WFC settings the connection is successful but when i try to connect via Mario Kart DS it just says connecting and on the server log a stay alive message arrives every 30 seconds. What am i doing wrong?

Kind regards,
Avi2002

**Comment by the4anoni** [comment]
If you connect to server from wiki are you still getting error ? What are you using emulator or real ds ?

**Comment by the4anoni** [comment]
Emulator wont work (timeout) ,real s work fine.

**Comment by dmoeenm** [comment]
Im having the same issue im on a regular ds and it won't connect

**Comment by dmoeenm** [comment]
Like for me it dosent give me a message and it just sits there trying to connect

**Comment by SilverSzymonPL** [comment]
I wonder if the emulator will ever work, It would be cool if it did.

**Comment by Avi2002** [comment]
I'm using a real ds and a small router secured with a wep encryption where the raspberry pi and te ds are both connected to.

**Comment by rtm516** [comment]
Mine hangs on the public servers on mkds but I show up on port 9001
