### ISSUE TITLE
Problem with Phantasy star 

### ISSUE THREAD

**Issue by Valkristh** [barronwaffles/dwc_network_server_emulator#359]
Hi everyone, i tried to patch the rom phantasy star zero (U) and it's not running in my r4, but others games like Diddy Kong Racing, Mario kart DS, metroid PH, etc. are working fine

There's another way to patch that game?
Or someone who patch successfully, can tell me what rom did use

**Comment by the4anoni** [comment]
r4 is china flash card.... Use Acekard 2i. What console you have ?

**Comment by Valkristh** [comment]
Ok I'll try another... I have a dsi

**Comment by Valkristh** [comment]
I forget, the rom without the patch is working fine, so... Really i need another flashcard?

**Comment by the4anoni** [comment]
r4 dont lke on official roms :( have dual core r4i and it dont work with some altwfc patched games :( The best solution is buy ak 2i ,and if you have 3ds consider installing luma3ds

**Comment by Valkristh** [comment]
Ohh i see. thanks for the answers! I'll try in a friend's 3ds

**Comment by AlexisDev01** [comment]
NEW Server Friends :D 

DNS:  192.241.153.27 Enter :) works Fine

**Comment by Valkristh** [comment]
I'm able to play this game and others in my r4 CLONE, no need for a new flashcard, i'm using AR codes :D
