### ISSUE TITLE
New Server DNS

### ISSUE THREAD

**Issue by AlexisDev01** [barronwaffles/dwc_network_server_emulator#360]
New Server Working 

DNS:  192.241.153.27 Enter :)

**Comment by AlexisDev01** [comment]
Im playing Mario Kart enter :)

**Comment by Valkristh** [comment]
Old news, it's BeanJrFi server, i use this since 3 or 4 months

**Comment by Valkristh** [comment]
But for Mario Kart ds and MPH i use wimmfi
(sorry for the multipost)

**Comment by AlexisDev01** [comment]
Valk how to connect to wimmfi bro help me :c

**Comment by AlexisDev01** [comment]
what are the dns or the tool bro

**Comment by Valkristh** [comment]
Its the same instructions in here 

https://github.com/polaris-/dwc_network_server_emulator/wiki

But in dns you must use 46.4.79.141

Also it's not necessary deleted wfc data just change dns in those games, because games like diddy Kong racing ds or bomberman are not working in wimmfi

**Comment by the4anoni** [comment]
Issue to close (not new news....).
