### ISSUE TITLE
Unable to connect to the server

### ISSUE THREAD

**Issue by YogaSmara** [barronwaffles/dwc_network_server_emulator#361]
Hello. Firstly, I'm sorry if this has been answered many times.

So after I set up everything, I tested the connection and it was successful. However, when I tried to connect to Wi-Fi club in-game, it says that I was unable to connect with error 20100. I also tried to erase the WFC configuration, but it is still unable to connect. The game is Pokémon Black 2, if it helps.

**Comment by YogaSmara** [comment]
Oh, I forgot to mention I was using DeSmuMe via USB tethering.

**Comment by Valkristh** [comment]
20100: Connection to the Access Point succeeded, but connection to the Wi-Fi Connection servers couldn't be established. Either you forgot to set the DNS and are trying to connect to the now-defunct official servers, or the custom server is currently down for maintenance. May also be a result of not properly patching your game to remove the SSL checks.

Extracted from troubleshooting...

**Comment by YogaSmara** [comment]
I don't really think that's the case, since the connection test was successful, but not when I tried to connect in-game

**Comment by Valkristh** [comment]
In what server you tried?

**Comment by YogaSmara** [comment]
Um, can you clarify?

Edit: Never mind about the question. I want to connect to the AltWFC (104.131.93.87)

**Comment by the4anoni** [comment]
also have this problem ,on real 3ds

**Comment by Valkristh** [comment]
Guys you must visit the other sections sometimes, there is other server here

https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers 

i use BeanJrFi server with pokemon HG

**Comment by YogaSmara** [comment]
Tried to use BeanJrFi, the test was successful, but when I tried to connect in-game, it gave me error 23503 instead :/

**Comment by Valkristh** [comment]
Yep it doesn't work wifi plaza :( 
i tried to contact with pokeclassic via Twitter if they can change the dns for use with beanjrfi

**Comment by the4anoni** [comment]
Play on altwfc

**Comment by YogaSmara** [comment]
But I can't play on AltWFC :/

**Comment by the4anoni** [comment]
You need to wait ,because i had this same problem. After 7 days of waiting it work for me. Maybe they must add you to whitelist

**Comment by YogaSmara** [comment]
Tried with AltWFC again, now it gave me error 23503...

**Comment by the4anoni** [comment]
Game server offline but reachable outside of game (i.e web server is up)
