### ISSUE TITLE
Wimmfi DNS working

### ISSUE THREAD

**Issue by AlexisDev01** [barronwaffles/dwc_network_server_emulator#363]
you need to delete the ALTWfc data to connect to Wimmfi DNS

DNS: 46.4.79.141

**Comment by sepalani** [comment]
By doing that you're not using altwfc anymore so it's pointless.

**Comment by Valkristh** [comment]
Isn't necessary deleted the wfc data, i use wimmfi  (because the stats page) with mario kart ds and metroid PH, i just change dns for that games
