### ISSUE TITLE
I have some questions for people who got altwfc working on a physical ds hardware 

### ISSUE THREAD

**Issue by dmoeenm** [barronwaffles/dwc_network_server_emulator#364]
I have questions for people who got altwfc working on an actual ds because i need to know because i tried it once and failed so i need some help and examples on how you did this and also get some answers clear answers on how stuff like dlc works

**Comment by Valkristh** [comment]
Eh... The questions are...?

**Comment by dmoeenm** [comment]
okay my first question regards a problem im having im trying to connect using mariokart ds but its stalling at the connecting to nintendo wifi screen so im asking one how would i solve this and have you ever had this problem]

**Comment by Valkristh** [comment]
Nope i never have that problem, did you patch the rom and change dns?

**Comment by dmoeenm** [comment]
yes i did

**Comment by Valkristh** [comment]
What error appears in the screen?

**Comment by dmoeenm** [comment]
none there is no error it just stalls there or crashes

**Comment by dmoeenm** [comment]
Anyway  i have a new question

**Comment by Valkristh** [comment]
It's very strange, maybe your internet is too slow or something...
