### ISSUE TITLE
Connection via dial-up

### ISSUE THREAD

**Issue by vigneshd332** [barronwaffles/dwc_network_server_emulator#366]
Hey guys,
     I am damn great user of this altwfc server. I till now i used broadband net but due to a cyclonic storm which pulled down the cables, im desperate to get connection to altwfc> please tell how to connect via dialup. i have a blackberry bold which i can put to good use.

**Comment by vigneshd332** [comment]
Hey I figured this out by myself. Use hamachi copy some ip addresses and viola. Case closed.

**Comment by dmoeenm** [comment]
Nice

**Comment by vigneshd332** [comment]
Thanx

**Comment by vigneshd332** [comment]
Awesome rss service man!
Sent from My Blackberry® Bold 9780 @ Tata Docomo

-----Original Message-----
