### ISSUE TITLE
 Can't 'Erase Nintendo WFC Configuration' 

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#368]
Hello,
I`ve got NDSL with "0168 - Mario Kart DS (U)" rom on R4iSDHC Dual Core. I patched rom witch WfcReplay. Option  'Erase Nintendo WFC Configuration'  is grey, I cant click on it. I tried to follow next steps, but i get wrong configuration error. Is any way to fix it and let me play Mario Karts online?

**Comment by dmoeenm** [comment]
Try using a regular version of the  rom and the cheat method or action replay method on the  r4 it still works

**Comment by ghost** [comment]
I`m not sure if I understand you clearly. I have to use non-patched rom and try to conncet to this server?

**Comment by ghost** [comment]
I played non-patched rom witch cheat - press B to Moon jump - and it is working.

How its linked with my problem?

**Comment by dmoeenm** [comment]
No no like the wfc relpay method using an un patched rom

**Comment by dmoeenm** [comment]
Cause ut might help you get around the configuration issue

**Comment by ghost** [comment]
I patched my first rom with WfcReplay.v0.7 as I said in the first post. Do I have to patch it again or what?

Its Mario Kart DS (U)(SCZ) ROM

**Comment by ghost** [comment]
My AMCE code is:

::Bypass HTTPS v0.7 for [AMCE] MARIOKARTDS
5200FD08 EE070F90
E20002F8 00000046
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EBD571 0B8000F8
0009000A 00000000
0200FD08 E92D401E
0200FD0C FAFFC179
D2000000 00000000

**Comment by ghost** [comment]
Form instruction:

    1. Download Prof. 9's WfcReplay v0.7 (requires .NET 4.0): https://github.com/Prof9/wfcreplay/releases
    2. Drag and drop the ROM file onto WfcReplay.exe.
    3. Use the code from the text file that was created in the same folder as the ROM.
3 - how and where use this code? I should rename that file the same as Mario Kart rom and put in the same folder or what?

**Comment by ghost** [comment]
Patching by WfcPatcher is giving the same results.
Anyone can help me fix it?

**Comment by Valkristh** [comment]
That's strange, did you try deleting wfc data in other game?

**Comment by ghost** [comment]
Yes, in Pokemon Black 2 - same situation

**Comment by vigneshd332** [comment]
Try patching with wfc patcher. And try to erase the configuration. Worked 4 me.

**Comment by AdmiralCurtiss** [comment]
If the button is greyed out it means there is no WFC configuration on the system; you've either already erased it or you've never gone online with that DS. Just proceed with the next step.
