### ISSUE TITLE
Trying to Connect on DSi using TTDS(i) but refuses when entering my network info with Homebrew

### ISSUE THREAD

**Issue by NWIFICSDSiHBCh** [barronwaffles/dwc_network_server_emulator#369]
Hello,

I got the NoSSL rom of Mario Kart DS and used it on my TTDS(i). I had erased everything and wanting to connect but says These settings are invalid. Confirm the information and try again. I new to this but how do you fix this.

**Comment by NWIFICSDSiHBCh** [comment]
That was the AltWFC. Tried the 2nd one. Loads but gives error code 52000. On DSi

**Comment by Valkristh** [comment]
52000 This error seems to appear when attempting to connect to the server multiple times without properly disconnecting first. Reboot your console and try again.

From the troubleshooting section
