### ISSUE TITLE
can't use mystery gift 

### ISSUE THREAD

**Issue by dmoeenm** [barronwaffles/dwc_network_server_emulator#370]
I can't use mystery gift via Nintendo wfc in pokemon diamond when i try to it gives me error 31020 as soon as i start searching and when i try again the connection bars disappear and it freezes in the middle of the search but when  i do this in my other pokemon games it works and i can receive mystery gifts so is there anyway to resolve this and im using a dsi and an action replay i have tried this on my other ds' s and it still dosent work and going to the gts or wifi club dose work.

**Comment by vigneshd332** [comment]
Maybe the problem is on their side. For me mystery gift works in black and white. Dmoeenm r u a developer of this serever or just a techie gamer combo?

**Comment by dmoeenm** [comment]
Im just a combo really but like i said mystery gift dose work in my platinum and soulsilver but not my diamond version

**Comment by vigneshd332** [comment]
Physical hard ware?

**Comment by vigneshd332** [comment]
Tell me full bio of the hard ware

**Comment by dmoeenm** [comment]
Yes im using physical hardware an action replay and a dsi and what do you mean by full bio of the hard ware

**Comment by vigneshd332** [comment]
O one thing. Patch your rom woth wfc patcher or ssl patcher. Play the game again. Tell me if the problem commes . If yes, what error code and error description does it give? Make sure your internet connection is good

**Comment by vigneshd332** [comment]
Tell me the full bio means the full info of your nintendo wfc settings and how r u connecting to the internet.

**Comment by vigneshd332** [comment]
Tell me the full bio means the full info of your nintendo wfc settings and how r u connecting to the internet.

**Comment by dmoeenm** [comment]
I did say im using an action replay and a  dsi im not using roms and im tethering my phone to my dsi  to play online

**Comment by vigneshd332** [comment]
Do one thing connect via mobile hotspot(with no security). Make sure your wfc settings are configured properly and that mobile data is on. Cheers, Vignesh.

**Comment by vigneshd332** [comment]
Tell me if this works.

**Comment by dmoeenm** [comment]
Oh i am connecting without any security

**Comment by vigneshd332** [comment]
Does it work?

**Comment by dmoeenm** [comment]
Yes

**Comment by dmoeenm** [comment]
Not mystery gift but i can go online that's how i have been going online

**Comment by vigneshd332** [comment]
What error does it give?

**Comment by dmoeenm** [comment]
31020

**Comment by redfoxxyz13** [comment]
Can someone please help me?
