### ISSUE TITLE
DLC file in repo

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#373]
There's anyone have a more DLC files?I'm searching it but fail.

**Comment by vigneshd332** [comment]
What dlc files?

**Comment by ghost** [comment]
Anything.I don't care about that

**Comment by vigneshd332** [comment]
What r dlc files. Whaere can I find em?

**Comment by ghost** [comment]
In source.Folder dlc

**Comment by vigneshd332** [comment]
Give me the full path of the file. U will have it in a second. Which source file.. Give full path

**Comment by vigneshd332** [comment]
Is it in desmume source folder. Give full path

**Comment by ductator** [comment]
https://github.com/polaris-/dwc_network_server_emulator/issues/237
look there for DLC. Just extract those into your local copy and use that server to connect.

**Comment by Valkristh** [comment]
That link is full of ads xD
