### ISSUE TITLE
Ban and Admin area

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#374]
Hello,

i have a problem.
In the admin area, the users have the 127.0.0.1 ip would have since their ip is not displayed? Does anyone know what went wrong? Under "ipAddr" will be when I banned any user ban all.

**Comment by kyle95wm** [comment]
Yes, you seem to be using an improper setup. Did you use my install script? This sets up Apache properly and whatnot. The master server will not be running on port 80 directly.

**Comment by jamefane** [comment]
The server runs over nginx everything works fine only the  ban not
