### ISSUE TITLE
Action Replay (WfcReplay for DS) Solve Error 20100 (FOR EU)

### ISSUE THREAD

**Issue by malekairmaroc7** [barronwaffles/dwc_network_server_emulator#376]
Hi, GH!

I patched my (EU) game with WfcReplay, but it shows me an 20100 error in my 3ds! Can anyone solve this issue?

**Comment by malekairmaroc7** [comment]
The Game is ACWW (EU)

**Comment by Valkristh** [comment]
Did you activated the AR code?

**Comment by malekairmaroc7** [comment]
Yes.

**Comment by malekairmaroc7** [comment]
Did anyone have a solution

**Comment by dmoeenm** [comment]
I have a solution

**Comment by malekairmaroc7** [comment]
dmoeenm, Say it, please!

**Comment by dmoeenm** [comment]
You might need to delete your save or check if you used the right rom

**Comment by dmoeenm** [comment]
What is the exact file name of the rom you used

**Comment by malekairmaroc7** [comment]
Animal Crossing Wild World (EU).nds

**Comment by Valkristh** [comment]
20100: Connection to the Access Point succeeded, but connection to the Wi-Fi Connection servers couldn't be established. Either you forgot to set the DNS and are trying to connect to the now-defunct official servers, or the custom server is currently down for maintenance. May also be a result of not properly patching your game to remove the SSL checks

The save isn't the problem, why don't you use the wfcpatcher?

**Comment by dmoeenm** [comment]
Well the save can be a problem when i was connecting with Mariokart ds i kept having issues untill i deleted my save file

**Comment by Valkristh** [comment]
The only problem (in my experience) with save is the error with the user profile, but is 60000 not 20100
I think the problem it's the method he are trying to use for connect, idk if he are using a r4 or homebrew for the rom
Some r4 doesn't work with AR codes

**Comment by malekairmaroc7** [comment]
It worked now! The Problem was only SAV file. Dmoeemn you have right! Valkristh, thanks for your time to help me (Dmoeemn as well!!) THANKS A LOT!

**Comment by dmoeenm** [comment]
Welcome also what games do you play on altwfc  besides animal crossing

**Comment by malekairmaroc7** [comment]
MKDS, Pokemon black 1/2, Picross 3d

**Comment by dmoeenm** [comment]
Would you like to olay some games with me in pokemon and Mariokart
