### ISSUE TITLE
Error 85020

### ISSUE THREAD

**Issue by FlintFrisk** [barronwaffles/dwc_network_server_emulator#377]
All games are giving this error, except pokemon black and white 2. someone having the same problem?

**Comment by Valkristh** [comment]
Nop, i tried 3 games right now, and are working ok

**Comment by dmoeenm** [comment]
No mine are working pretty well

**Comment by dmoeenm** [comment]
It could be a matchmaking or firewall problem what mode are you trying to connect to

**Comment by BrokenR3C0RD** [comment]
Error occurs on Mario Kart DS after waiting in Worldwide matchmaking for about 5 minutes.

**Comment by BrokenR3C0RD** [comment]
https://wiimmfi.de/error?e=85020

The error code means the master server can't be connected to. I'm thinking that my error is more likely to be the game thinking the server is down because of no matchmaking response. @FlintFrisk is most likely trying to use his own server without port forwarding.

**Comment by Valkristh** [comment]
But what dns are you using?

**Comment by BrokenR3C0RD** [comment]
I'm using the testing server DNS

**Comment by Valkristh** [comment]
Try to use wimmfi dns for mkds
