### ISSUE TITLE
Mystery Gift server

### ISSUE THREAD

**Issue by jxgreen5** [barronwaffles/dwc_network_server_emulator#378]
Can you make a version of this that only does mystery gift?

**Comment by Valkristh** [comment]
But already exist support for mystery gifts in pokemon

**Comment by dmoeenm** [comment]
What exactly do you mean

**Comment by Valkristh** [comment]
I mean for receive gifts from wfc connection, or you refer to another thing? Be more specific

**Comment by dmoeenm** [comment]
I wasn't asking you valkristh

**Comment by ghost** [comment]
You want just the NAS server (that has the DLS functionality in it) - look at that script, find what it needs and copy it over.
