### ISSUE TITLE
Error 86420

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#379]
Hello, when I try to play anygame with a friend the game we are playing (Pokémon, Metroid, etc) send our the same error, the 86420. I don't know why it's happen.

**Comment by ghost** [comment]
We use the phones like router because our wifis isn't wep.

**Comment by malekairmaroc7** [comment]
Try to enable DMZ OR port fowarding.

**Comment by malekairmaroc7** [comment]
Which OS do you use, to play oder WiFi?

**Comment by ghost** [comment]
We use real DS

**Comment by ghost** [comment]
What is DMZ?

**Comment by malekairmaroc7** [comment]
DMZ is a kind port fowarding, but good for running home Servers like SSH, SQL, ...

**Comment by malekairmaroc7** [comment]
But what me More interested is whic Kind of Router do you use? (NOTE: If you usw mobile Phones they usually didn't work with DS, but actually works)

**Comment by ghost** [comment]
You want the model Of my router?

**Comment by ghost** [comment]
The model is TL-WR841N/TL

**Comment by malekairmaroc7** [comment]
Yes..

**Comment by malekairmaroc7** [comment]
Do you use wep on it?

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
I use wpa2-psk

**Comment by malekairmaroc7** [comment]
Didn't you know how to set it up wep on it?

**Comment by ghost** [comment]
No

**Comment by malekairmaroc7** [comment]
Do you want that I explain it for you?

**Comment by ghost** [comment]
Yes

**Comment by malekairmaroc7** [comment]
Okay

**Comment by malekairmaroc7** [comment]
Is the brand TP LINK?

**Comment by ghost** [comment]
But, can I create another WiFi with wep security?

**Comment by malekairmaroc7** [comment]
If your Router support it, then it is possible. I do this myself.

**Comment by ghost** [comment]
Yes, it is

**Comment by ghost** [comment]
Can explain me how to? I don't want yo change the security

**Comment by ghost** [comment]
To*

**Comment by malekairmaroc7** [comment]
Visit: tplinkwifi.net
And enter the Security password of the router. The password can be on the router or in the instruction booklet.

Go to Wireless and change the settings.

**Comment by malekairmaroc7** [comment]
If the link don't work report it

**Comment by malekairmaroc7** [comment]
On some routers, you can activate an "guest network". If it support only WPA2 change to free and make it invisible.

**Comment by ghost** [comment]
I found a way To change the security to wep, can you hope me how to create another WiFi with WEP security? With the same router

**Comment by ghost** [comment]
Oh, ok

**Comment by ghost** [comment]
Thanks you!

**Comment by malekairmaroc7** [comment]
No problem! If it works say it;)

**Comment by ghost** [comment]
Okay

**Comment by ghost** [comment]
My router can't create guest networks -_-

**Comment by malekairmaroc7** [comment]
If the guest network is invisible, your network is safe. Don't worry! TIP: If your router support it, activate Firewall. Only if you find it.

**Comment by ghost** [comment]
The firewall is on

**Comment by ghost** [comment]
I should search that programs create wifi networks

**Comment by malekairmaroc7** [comment]
Exist there a guest network section?

**Comment by malekairmaroc7** [comment]
Is it a dual band router?

**Comment by malekairmaroc7** [comment]
If yes check out here: http://www.tp-link.com/us/faq-649.html

**Comment by ghost** [comment]
How I know it?

**Comment by malekairmaroc7** [comment]
There are two antennas.

**Comment by ghost** [comment]
Yes, it is.

**Comment by malekairmaroc7** [comment]
Then it should possible

**Comment by malekairmaroc7** [comment]
Check out here: http://www.tp-link.com/us/faq-649.html

**Comment by malekairmaroc7** [comment]
There should be a guest network section

**Comment by ghost** [comment]
Nop :(

**Comment by ghost** [comment]
I trying with Connectify

**Comment by malekairmaroc7** [comment]
Is this a program?

**Comment by ghost** [comment]
Yes

**Comment by malekairmaroc7** [comment]
Maybe the guest network is under wireless section?

**Comment by ghost** [comment]
Nop

**Comment by malekairmaroc7** [comment]
Why does it have two antennas without Guest network?Totally weird.

**Comment by malekairmaroc7** [comment]
Does it work with Connectify?

**Comment by ghost** [comment]
Too weird, yes. The program doesn't give me the option to change the security -_-

**Comment by ghost** [comment]
Only the paid version of the program gives that option

**Comment by malekairmaroc7** [comment]
If your mobile phone support hotspot use it.

**Comment by malekairmaroc7** [comment]
I use my hotspot for DS browser and it works.

**Comment by malekairmaroc7** [comment]
I use my hotspot for DS browser and it works.

**Comment by ghost** [comment]
I use it but I think the speed of this is too slow for online play and because this gives me that error

**Comment by malekairmaroc7** [comment]
Change it to HSPA+ or HSDPA

**Comment by ghost** [comment]
How?

**Comment by malekairmaroc7** [comment]
Which android version do you use?

**Comment by ghost** [comment]
Ah, It works me too but don't work me when the game need to contact wit another player

**Comment by ghost** [comment]
5.1

**Comment by malekairmaroc7** [comment]
Go to Settings > More... > cellular network > preferred network type > Use 3G

NOTE: the Network provider must activated the 3G support!

**Comment by ghost** [comment]
If I don't buy the program I can't create a WEP Network... I keep use the phone

**Comment by malekairmaroc7** [comment]
Go to Settings > More... > cellular network > preferred network type > Use 3G

NOTE: the Network provider must activated the 3G support!

**Comment by malekairmaroc7** [comment]
Which country and time did you have?

**Comment by ghost** [comment]
Argentina and 20:02

**Comment by malekairmaroc7** [comment]
Okay.

**Comment by ghost** [comment]
I already use 3G xD

**Comment by malekairmaroc7** [comment]
If you activated hspa or HSDPA the connection should be high

**Comment by malekairmaroc7** [comment]
You will see an H+ on the

**Comment by malekairmaroc7** [comment]
Okay. Unfortunately, I must go offline, because its almost 00:07 AM (Sunday) in my country and I go to bed. I can help you tomorrow. Do you agree? I don't forget you...

**Comment by ghost** [comment]
Thanks for your help, dude!

**Comment by malekairmaroc7** [comment]
NO PROBLEM! And I've said tomorrow I will help you again!

**Comment by ghost** [comment]
No problem, but I think there no solutions if I don't buy that program

**Comment by malekairmaroc7** [comment]
Search for a cracked one...

**Comment by ghost** [comment]
Bye!

**Comment by malekairmaroc7** [comment]
But it will difficult.

**Comment by malekairmaroc7** [comment]
Okay. Bye! See you soon!

**Comment by dmoeenm** [comment]
Axes don't worry about what he was saying i can help you i have been using my phone  and a physical ds for months

**Comment by dmoeenm** [comment]
Alright i looked up the error  and now i gotta  ask did you set everything up correctly like did you patch your game and enter the dns if not thats your issue if you have what mode in pokemon and metroid are you trying to access

**Comment by ghost** [comment]
I patch the games, I enter the DNS, we try in pokémon Black 2 (Spanish ver.) and SoulSilver with HeartGold (Spanish ver. too).

**Comment by malekairmaroc7** [comment]
Do you Connecticut now?

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
dmoeenm, you can connect with your friends in Pokémon Black? In the WiFi club

**Comment by dmoeenm** [comment]
Yes

**Comment by ghost** [comment]
You got 4G?

**Comment by dmoeenm** [comment]
Yes

**Comment by ghost** [comment]
Hello guys, I used WEP, don't find any solutions.

**Comment by malekairmaroc7** [comment]
The WEP is maybe not the Problem. Is it maybe the compatibility? Do you usw still the phone or router?

**Comment by ghost** [comment]
I now use the router

**Comment by ghost** [comment]
When now I use the router, I don't have the error 86420

**Comment by dmoeenm** [comment]
So you're able to get online axes

**Comment by ghost** [comment]
Buuuut, I have other errors

**Comment by ghost** [comment]
Someome want to try?

**Comment by ghost** [comment]
But I keep trying because some errors are normal

**Comment by dmoeenm** [comment]
Well what are the errors

**Comment by ghost** [comment]
Normal erorrs, 52100 and others

**Comment by ghost** [comment]
In Mario Kart I have the error 81010

**Comment by ghost** [comment]
Now I can't use the gts, because say me disconnected from nintendo WFC (No error code). I only can use the mystery gift

**Comment by ghost** [comment]
And I have the DMZ on

**Comment by dmoeenm** [comment]
Hmmm ill look up the errors and see whats going on

**Comment by ghost** [comment]
Ok, and what is the problem?

**Comment by ghost** [comment]
I need to open ports or something else?

**Comment by ghost** [comment]
I have the WEP on open system

**Comment by ghost** [comment]
Can be the R4? I have R4 Wood

**Comment by ghost** [comment]
Actually works with phone WiFi

**Comment by Valkristh** [comment]
81010: The server has been shut down or restarted for maintenance. This error can also mean you were kicked from the server

I play Mario kart without problems in Wimmfi server, try write to my email puedo ayudarte en español :D

**Comment by ghost** [comment]
Mobile phones usually have CNAT - Carrier-Grade NAT - which stops DMZ from working. You need a real broadband connection.

**Comment by dmoeenm** [comment]
Acer i have been using my phone's hotspot mode  to play online  it works for me

**Comment by dmoeenm** [comment]
Also Acer do you know what is going on with  error 31020 in pokemon diamonds mystery gift

**Comment by dmoeenm** [comment]
I hate to ask but i need to

**Comment by ghost** [comment]
31020 is a DLS1 error; if it's happening in AltWFC you need to ask their devs. If in Wiimmfi it's something I have to fix and I have. And CNAT<->CNAT might work, and server<->CNAT will obviously work, but CNAT<->NAT (regular broadband) could have issues.

**Comment by dmoeenm** [comment]
Okay  well then im going to have to talk to the altwfc devs i hope i can find a way to speak to them and thanks for helping
