### ISSUE TITLE
No SSL AR Code roundup

### ISSUE THREAD

**Issue by Link2738** [barronwaffles/dwc_network_server_emulator#382]
If anyone has (or can get) any no ssl codes that would be great i'm tweaking the AR Codes page and I need codes

**Comment by dmoeenm** [comment]
Wait you can actually edit the site

**Comment by dmoeenm** [comment]
And i could get you some codes that i have

**Comment by Link2738** [comment]
Yes you can edit the site, and any codes would be appreciated

**Comment by dmoeenm** [comment]
Okay

**Comment by maylay** [comment]
I started to clean up some of the changes but I noticed all of the codes are shown as a long string of text and missing the game ID. There is also a problem with the links pointing to a dynamic URL. If the title of a page is updated or if you change your username the link in the wiki would have to be changed as well. This may lead to dead links down the road which would discourage new players. I think we can come up with something that is more robust.

**Comment by Link2738** [comment]
All ears on anything you got I made that lazily in an hour

**Comment by maylay** [comment]
Okay, I put a new list together with the codes that were missing.

**Comment by Link2738** [comment]
Great
