### ISSUE TITLE
can't conect in pokemon white 2

### ISSUE THREAD

**Issue by marakandrusca** [barronwaffles/dwc_network_server_emulator#383]
I was trying to connect but I get the error 52001

**Comment by dmoeenm** [comment]
Likely cause: It appears that the security settings entered into the Nintendo DS are not the same as what your wireless router is set to allow, or your router is not able to assign the Nintendo DS an IP address.
How to fix: Make sure the security key and security type are entered into the Nintendo DS exactly as they appear in your router's settings; manually assign an IP address to the Nintendo DS. This is from Nintendos website

**Comment by dmoeenm** [comment]
So you may be trying to use a wpa router which won't work

**Comment by dmoeenm** [comment]
You need to either use an open connection or a wep connection

**Comment by redfoxxyz13** [comment]
Can someone help me?

**Comment by dmoeenm** [comment]
What do you need help with

**Comment by redfoxxyz13** [comment]
I'm trying to see if I can get on the gts on dpp
