### ISSUE TITLE
Mario Kart Wii - Error Code 84020/94020 & broken game stats page

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#384]
This error happens whenever I connect to MKWii altwfc. After about a minute, I receive the error code mentioned above. Am I doing anything wrong, or is the server temporarily broken?

**Comment by Gippy0** [comment]
Got it too for Advance Wars. Server is inoperative as of April 16.

**Comment by catandkot** [comment]
Me too. connect and waiting VS battle but disconnect with 84020 error :(

**Comment by Microeinstein** [comment]
Me too - I've just checked [here](https://forum.wii-homebrew.com/index.php/Thread/51738-Collecting-Error-Codes/#post590284):
> 84020: Master server down or UDP packets are being blocked

I don't have any blocked UDP port, then i think master server is down
