### ISSUE TITLE
Pokemon pearl gts help

### ISSUE THREAD

**Issue by redfoxxyz13** [barronwaffles/dwc_network_server_emulator#385]
I'm reading that you can still use the gts but I have a ds lite and trying to see if it can still be used. Is it possible to use it?

**Comment by dmoeenm** [comment]
Yes its possible on all systems

**Comment by redfoxxyz13** [comment]
Ok how can I do it on my ds lite?

**Comment by redfoxxyz13** [comment]
Do I have to use a action replay?

**Comment by dmoeenm** [comment]
Yes

**Comment by redfoxxyz13** [comment]
Ok I have one if I put in the code what esle do I need to do?

**Comment by redfoxxyz13** [comment]
I just want to battle and trade ppl. So I just wanted to see how to do it

**Comment by redfoxxyz13** [comment]
So anyway you can help me out with getting on the gts?

**Comment by dmoeenm** [comment]
You need to set up your connection because you need a wep connection

**Comment by redfoxxyz13** [comment]
Wep connection?

**Comment by redfoxxyz13** [comment]
Can you tell me?

**Comment by dmoeenm** [comment]
Yes its a lower type of security / connection which was replaced by the wpa connection which most routers use today and the ds only uses wep so if you wanna connect you have to have a wep connection set up and also quick question have you entered the code in

**Comment by redfoxxyz13** [comment]
How can I find my wep key?

**Comment by redfoxxyz13** [comment]
Do you mean the action replay code?

**Comment by dmoeenm** [comment]
No i mean the connection on your router

**Comment by redfoxxyz13** [comment]
Is it behind the router?

**Comment by dmoeenm** [comment]
No its your settings

**Comment by redfoxxyz13** [comment]
I went to my settings on my ds but couldn't find any information.

**Comment by dmoeenm** [comment]
No i ment your router settings  not your ds its not behind your router its not an action replay code all you need to do is see what company made your router  and what version it  is then look up its ip adress to access your routers settings  on your computer

**Comment by redfoxxyz13** [comment]
Ok cool.  I know the ip

**Comment by dmoeenm** [comment]
And if you have a  phone you can set an open hotspot if you have the plan and data to do so

**Comment by dmoeenm** [comment]
All you need is a  wep or open connection

**Comment by redfoxxyz13** [comment]
I know a place that has Internet.  All I have to do is connected to it but
it gives me a error

**Comment by redfoxxyz13** [comment]
Do I need the ip and the wep key too? At the place I go to for Internet?

**Comment by dmoeenm** [comment]
What do you mean

**Comment by redfoxxyz13** [comment]
Is there a video that can show up how to do it spet by step?

**Comment by vigneshd332** [comment]
Hey red foxy. Do this
1 Connect using open security.
2 if ur using a dsi cartridge use an AR code. Or if using a ROM best way is patch it.
3 if u have internet in ya phone, switch in hotspot with open security and connect to it. Or if u r using a wifi router, then change the security of the connection from wpa to wep or open and connect to it.
4 altwfc is down for the moment so try it with beanjrfi. 
5 you cannot use all the features with beanjrfi. But you can use it to check if your connection is getting established or not. Further queries ask me. Happy to Help.

Vk

**Comment by vigneshd332** [comment]
Well tell me if it works
