### ISSUE TITLE
I can't even get the AltWfc!

### ISSUE THREAD

**Issue by Athanetos** [barronwaffles/dwc_network_server_emulator#386]
I'm on Mac, latest OSX. I download the newest WfcPatcher 1.6. I try to drag HeartGold (extracted in nds form) to the exe file, but it doesn't work! Is there something I'm doing wrong or is this just not compatible with Mac or something? Thanks.

**Comment by dmoeenm** [comment]
.exe files don't work on mac os only Windows so you will need a windows computer but i can give you the code to heartgold

**Comment by Athanetos** [comment]
@dmoeenm crap! Thanks, is there an alternative on Mac? Yea, I would appreciate the code thx.

**Comment by mm201** [comment]
Install [Mono](http://www.mono-project.com/), then, from the command line, run `mono wfcpatcher.exe game.nds`.

**Comment by Athanetos** [comment]
@mm201 What does that do, and what is it for?

**Comment by Athanetos** [comment]
@mm201 I downloaded the Mono thing and then tried to run the text you sent in the Terminal. It says "Cannot open assembly 'wfcpatcher.exe'. No such file or directory." I even tried moving it out of its folder.

**Comment by mm201** [comment]
Mac is case sensitive. Is the case correct? `wfcpatcher.exe` vs. `WfcPatcher.exe`. Use whatever the filename actually is.
Does the console have the correct working directory? If the rom and exe are in different directories, you'll need to include the full path to one or both.

**Comment by Athanetos** [comment]
@mm201 Ok, thanks, that might be the problem. Then I tried it and that error stopped appearing. For "game.nds", should I write that or the literal name of the game in my files? When I use:
WfcPatcher.exe game.nds
I get:
-bash: WfcPatcher.exe: command not found

And when I use the file name:
WfcPatcher.exe 4840 - Pokemon - SoulSilver Version (v10) (E).nds
I get:
-bash: syntax error near unexpected token '('

It's just soooo complicated, and I really don't understand anything. Thank you for all the help however.

**Comment by sepalani** [comment]
You need quotes in paths if there are characters such as spaces and other special characters.

Not sure if it works on mac but it works on decent terminals, you might want to drag & drop the file on the terminal and see if it inserts the file's full path. Otherwise, I'd advise you to read tutorials on how-to use a terminal/command line interface.

**Comment by mm201** [comment]
You forgot `mono` at the start of your command. What you probably want is
`mono WfcPatcher.exe "4840 - Pokemon - SoulSilver Version (v10) (E).nds"`

**Comment by Athanetos** [comment]
@mm201 
Great! That seemed to work, but now this happened....
And thanks for all the help.

mono WfcPatcher.exe "4840 - Pokemon - SoulSilver Version (v10) (E).nds"
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
WfcPatcher 1.6

Reading and copying 4840 - Pokemon - SoulSilver Version (v10) (E).nds...
Patching ARM Executables...
Patching Overlays...
Replacing and recompressing overlay 0...
Patched to 4840 - Pokemon - SoulSilver Version (v10) (E) (NoSSL).nds!

**Comment by Masamune3210** [comment]
It looks like it worked fine, does the game work as expected?

**Comment by Athanetos** [comment]
@deadair3210 Sure, but when I search for an access point, it tells me I'm not connected. "No access point in range."

**Comment by redfoxxyz13** [comment]
Can you guys help me connect to the gts on dpp I'm on my ds lite

**Comment by Athanetos** [comment]
I think that the emulator has some issues or something. I just can't seem to set it up properly. Is there a certain emulator I should be using?

**Comment by redfoxxyz13** [comment]
Idk I need help with trying to get the gts on my ds lite

**Comment by Athanetos** [comment]
@redfoxxyz13 Unfortunately I have no idea what that means. On my DS Lite I just connected to a random wi-fi server and inputted the given IP address thingy.

**Comment by redfoxxyz13** [comment]
Really? What  ip do I have to put in?

**Comment by Athanetos** [comment]
@redfoxxyz13 Here are the instructions. It differs based on which game you are using but should look this way for most of them. Follow the pictures and the instructions, set _Auto-Obtain DNS_ to _NO_ and then type in the server provided at the top. Maybe then we can battle! :)

https://github.com/polaris-/dwc_network_server_emulator/wiki

**Comment by Athanetos** [comment]
@redfoxxyz13 But what do you need the connection for? Are you going to trade/battle with the game that you emulated?

**Comment by redfoxxyz13** [comment]
I'm not useing a emulator I'm on my ds lite. I want to battle trade.

**Comment by redfoxxyz13** [comment]
I'm playing pokemon pearl

**Comment by redfoxxyz13** [comment]
Are you using a emulator?

**Comment by redfoxxyz13** [comment]
Well I don't know how you got it working but it's not working for me

**Comment by Athanetos** [comment]
@redfoxxyz13 I'm using both. The point is that I can trade between the emulator and my actual game, for Pokemon HeartGold. That means we can battle, both games are Gen IV.

**Comment by redfoxxyz13** [comment]
Ok cool.  But I don't know how to do the set up for the gts. I don't know my wep key or anything

**Comment by redfoxxyz13** [comment]
I tried to follow the instructions but I don't know what to do.  Do I need a action replay?

**Comment by Athanetos** [comment]
@redfoxxyz13 No. Go to Options and if there is an option to _Erase Nintendo WFC Connection_, choose it. If not go to the connections and look for an access point. Connect to any wifi network that's unlocked, then in the setting turn off _Auto-Obtain DNS_ and enter the codes given at the beginning of the instructions I sent.

**Comment by redfoxxyz13** [comment]
Ok I will tomorrow.

**Comment by redfoxxyz13** [comment]
I just did the connection but it says it has been discontinued.

**Comment by redfoxxyz13** [comment]
I did what you told me to do but nothing working.  What can I be doing wrong?

**Comment by Athanetos** [comment]
Where did it say that?

**Comment by redfoxxyz13** [comment]
When I tried to connect online to check the Internet

**Comment by redfoxxyz13** [comment]
I mean to test connection
