### ISSUE TITLE
Getting error code 52100 again ._.

### ISSUE THREAD

**Issue by AmeBird** [barronwaffles/dwc_network_server_emulator#387]
I use a patched Rom on my Laptop with DeSmuME. Do I need to change my routers security to wep in order to get it work or is it something with the severs? If its the severs please give me one that works. Thanks in advance^^
Oh and Idk if it's important but I have Mario Kart and Animal Crossing wild world, MK is fine but AC is kinda slow.. if you could help me with that as well that'd be great! Thank youuuuu

**Comment by Westretroman** [comment]
It's an issue with the emulators, right now, hope they can notice.

**Comment by AmeBird** [comment]
any way to fix that on my own?

**Comment by 81457** [comment]
The QR Server (Matchmaking) is down at the moment, so it's impossible to fix that on your own. Meanwhile you can use BeanJrFi, which use the AltWFC source code.

**Comment by AmeBird** [comment]
I'll try that one then^^
Edit: It worked yay! 
Edit: now I get that error code again even though I used beanjrfi :c

**Comment by vigneshd332** [comment]
Ame it is better if you connected the router with an ethernet cable to the laptop. Ethernet is the best. Im playing in my laptop too.
Or if u r using ur phone bridge the lan and your phone connection and select the wifi adaptor as anythig that is in the network bridge. It should work if it does not tell me.
