### ISSUE TITLE
Error 91010 on Pokémon Black 2

### ISSUE THREAD

**Issue by wwsnkneo** [barronwaffles/dwc_network_server_emulator#388]
This afternoon was working, but out of nowhere this error started, I searched but did not find any place that spoke about such an error. Does anyone know what it is?

I'm using the emulator.

**Comment by dmoeenm** [comment]
Thats one of the errors you would get trying to connect to Nintendos servers here's Nintendos info You are unable to connect to an online feature and you receive the error code 20110 and the error message "Nintendo Wi-Fi Connection service for this software has been discontinued." Have you entered the dns yet

**Comment by 81457** [comment]
Error code 91010 means basically that you got kicked from the server, or your connection dropped in-game. Try connecting again.

**Comment by wwsnkneo** [comment]
@dmoeenm 

I have entered.

@81457 

For what reason? Well, i will try again.
