### ISSUE TITLE
Exchange friend code for acww (if anyone still plays it)

### ISSUE THREAD

**Issue by AmeBird** [barronwaffles/dwc_network_server_emulator#389]
My name is Amelie, my city is called Rein and my friend code is 0515 3960 7690.
I hope I'm not the only one who still plays it, nostalgia made me wanna play it :D

**Comment by redfoxxyz13** [comment]
What game do you have?

**Comment by redfoxxyz13** [comment]
Are you using a emulator?

**Comment by AmeBird** [comment]
@redfoxxyz13 yes, I use an emulator, the game I was talking about is animal crossing for ds^^

**Comment by redfoxxyz13** [comment]
How can I hook up to the Internet on my ds lite?

**Comment by AmeBird** [comment]
if you want to use your ds directly you need an action replay

**Comment by redfoxxyz13** [comment]
I have one

**Comment by redfoxxyz13** [comment]
Can you help me step by step?

**Comment by AmeBird** [comment]
Sure but you can also look it up here haha or go look up some tutorials on YouTube :D

**Comment by redfoxxyz13** [comment]
I tried looking online here but don't I don't know how to do it.  And
there's no videos online

**Comment by AmeBird** [comment]
Okay so first of all you need to get an action replay ds/dsi

**Comment by redfoxxyz13** [comment]
What's the code?

**Comment by AmeBird** [comment]
Code for what?

**Comment by redfoxxyz13** [comment]
Action replay

**Comment by redfoxxyz13** [comment]
Someone gave me a code but it missed up a ds a buddy had

**Comment by vigneshd332** [comment]
Ok Amelie, which server r u connecting to?

**Comment by Pablo200** [comment]
My Friend code is 2103 5339 7788 name Pablo and city Gameland (I have nostalgia too)

**Comment by Pablo200** [comment]
Im playing with a R4 cartrigde

**Comment by vigneshd332** [comment]
Hey pablo which server r u connecting to
