### ISSUE TITLE
Can't got the connection working on an emulator.

### ISSUE THREAD

**Issue by Athanetos** [barronwaffles/dwc_network_server_emulator#390]
Hi, I'm on the DesMuMe emulator on Mac and am playing Pokemon HeartGold. I installed the file with Wi-Fi (extension NoSSL), but when I open the emulator and look for an access point in tells me "No access point found". When I try to manually install the new server settings it tells me "These setting are invalid. Confirm the information and them try again". Do I need to use a different emulator, have a different PC (Windows), or did I get the wrong file? Thanks.

**Comment by Masamune3210** [comment]
I dont think DesMuMe emulates WiFI, correct me if im Wrong

**Comment by Athanetos** [comment]
@deadair3210 Oh really? I didn't know that. Which emulator should I use then? And thanks.

**Comment by Westretroman** [comment]
Desmume Wifi (A special build of desmume.)

**Comment by Athanetos** [comment]
@Westretroman Yea, I found it. I'm gonna half to switch over to my Windows for it though :(
