### ISSUE TITLE
New file?

### ISSUE THREAD

**Issue by Athanetos** [barronwaffles/dwc_network_server_emulator#391]
I used the WfcPatcher to create a new file of the Pokemon HeartGold ROM. I realized the new extension on the Wi-Fi compatible version said "noSSL". This seems to be correct since there is a new extension regardless, but I know it should be AltWfc. Is there a difference?

**Comment by Westretroman** [comment]
NoSSL is the correct extension and it worked time and time again with me.

**Comment by Athanetos** [comment]
@Westretroman Great, thanks. One more question - I want to trade between my DS and emulator (and thanks for the advice on Desmume Wifi), but my DS can't connect to a server. I've tried optimumwifi and linksys - do I need an actual server to do this?

**Comment by Westretroman** [comment]
No, what you do need is Action Replay (DSi) and follow the AR instructions to connect, you just need your internet connection to play online.

**Comment by Westretroman** [comment]
If your internet won't connect with it, tether your phone (Hotspot connection with no password.) Too, that helps, since I've seen others do it to get online on ALTWFC.

**Comment by Athanetos** [comment]
@Westretroman I can't do it without an AR? I'm on a DS lite. And do I need the AR exclusive to the game? (pokemon heartgold) And thanks, I'll try a hotspot for my emulator.

**Comment by Athanetos** [comment]
Nothing is working. I tried a hotspot and that didn't work, as well as a public network. The actual emulator comes with its own signal, though (which is what I was connected to in the game). Whenever I tried to request a friend code it tells me no access point in range.

**Comment by dmoeenm** [comment]
Hey westroman can you help redfoxy

**Comment by Westretroman** [comment]
Sadly, you can't do it without AR or a patched rom. If you don't have AR, then you must run a patched rom of the game through R4.
