### ISSUE TITLE
23502 on Mario Kart Wii ALTWFC

### ISSUE THREAD

**Issue by Chaos35000vr** [barronwaffles/dwc_network_server_emulator#392]
i have tried to connect to ALTWFC on MKWii recently, and i have got error 23502. I have repatched ISO, used ALTWFC Access code, and still 23502, is there anyway i can connect to altwfc without getting 23502, or when searching getting 84020?

**Comment by 81457** [comment]
It is not a problem on your iso, the matchmaking server crashed. That's why you get those error codes.
