### ISSUE TITLE
is the server offline 

### ISSUE THREAD

**Issue by dmoeenm** [barronwaffles/dwc_network_server_emulator#393]
I gotta ask is the server offline because i keep getting errors about high traffic and the gamestats page hasn't updated in weeks

**Comment by Chaos35000vr** [comment]
Its down, the matchmaking server crashed

**Comment by gabrielpzme** [comment]
Hi, I was having the same error here. Was a little afraid to ask... Anybody know when they will fix this problem?

**Comment by dmoeenm** [comment]
No not really i just hope it gets fixed soon
