### ISSUE TITLE
Mario Kart Wii: Error Code - 23502

### ISSUE THREAD

**Issue by clavignejr** [barronwaffles/dwc_network_server_emulator#398]
When selecting to go to WFC error code 23502 seems to persists. I've heard the server crashed, but is that true? If so, any notice when it will be back up at all? Thanks in advance.

**Comment by WebTiger89** [comment]
Same here. Some information would be nice. Thanks

**Comment by alivebacon** [comment]
use BeanJrFi instead.

**Comment by kyle95wm** [comment]
I see people are using my server after all :p
