### ISSUE TITLE
mkwii says servr is down 

### ISSUE THREAD

**Issue by alivebacon** [barronwaffles/dwc_network_server_emulator#400]
title says all. i am connecting to the altwfc server and not mine. do you need to foward some ports?
@Toad King

**Comment by toad** [comment]
On 04/05/17 17:13, censoredscrewgithub wrote:
> title says all. i am connecting to the altwfc server and not mine. do you need to foward some ports?
> @Toad King
>
Wrong toad :)

**Comment by dmoeenm** [comment]
Wait you're toad king?

**Comment by alivebacon** [comment]
pls fix the mkwii servers

**Comment by alivebacon** [comment]
i now use beanjrfi pls tell me your beanjrfi mkwii friend code

**Comment by clavignejr** [comment]
censoredscrewgithub, how are you using BeanJrFi, when it's literally the same thing? Or am I wrong? As I go to the page, the instructions to conenct are the exact same as AltWFC's...

**Comment by alivebacon** [comment]
u r rong it uses a different dee enn ess dns* pls add me

**Comment by clavignejr** [comment]
I will add you if you can tell me what the DNS for their server is, as of now I've been playing on Wiimmfi, but if you can tell me what the DNS is, I can play on both.

**Comment by alivebacon** [comment]
i now use 158.69.112.35 and my fc there is 0515-3960-7593

**Comment by clavignejr** [comment]
I tried that DNS, doesn't work, doesn't even let me connect to the internet. I've also tried the official BeanJrFi DNS (104.238.144.225) and all i get is an error of high traffic usuage on Mario Kart Wii. Until then, i'll be sticking to Wiimmfi, because it works.

**Comment by alivebacon** [comment]
u wot? Is wimmfi usable on a real wii u?

**Comment by clavignejr** [comment]
Yes you can, you have to download the ISO of Mario Kart Wii, put it on a USB in WAD format, use the Homebrew application USB Loader GX, and from there in the Loader Settings, you can make it go to wiimmfi.de and then start Mario Kart Wii, that's how I play online.

**Comment by alivebacon** [comment]
woah! i am NOT getting an iso of mkwii!

**Comment by clavignejr** [comment]
I did, just because i've bought 2 Mario Kart Wii disc, and they both got laser burnt from playing it to much, so im not about to buy a 3rd. Scratch that though, when i said you have to use an ISO, I meant that's what I do, you can use your disc as well dude.

**Comment by alivebacon** [comment]
I just run mkwii via usb loader gx using disc? OK, I will when I find mkwii

**Comment by alivebacon** [comment]
ftpiiu is not installing pls help meeeee
