### ISSUE TITLE
pls make it easy to setup on ds(i)

### ISSUE THREAD

**Issue by alivebacon** [barronwaffles/dwc_network_server_emulator#401]
title says all. pls make it quick and easy i.e no roms or action replays needed. i wanna play mkds but i don't have an mkds rom or an action replay ds.

**Comment by Masamune3210** [comment]
its impossible to do this without either modifying a rom or using a action replay, as it involves changing where the game is set to look for the server

**Comment by barronwaffles** [comment]
Not currently (if ever) possible.

**Comment by alivebacon** [comment]
d-ram it

**Comment by alivebacon** [comment]
can't you use a dns

**Comment by barronwaffles** [comment]
No.

**Comment by alivebacon** [comment]
why not

**Comment by barronwaffles** [comment]
Because you can't strip out the security check with a DNS redirect - your console/handheld won't talk with a server that doesn't have the required certificate.

Before you ask, no - it's not (reasonably) possible to forge the certificate.

This is why you need either patched roms or an action replay.

**Comment by vigneshd332** [comment]
So true. Issue to close.

**Comment by alivebacon** [comment]
I think i have an mkds rom on a disc... I may check

**Comment by alivebacon** [comment]
i do.

**Comment by flutterbrony** [comment]
Is it not possible now to do that with the ssl flaw in ds and Wii console ?

**Comment by barronwaffles** [comment]
Yes - the wiki has been updated to reflect this.

**Comment by Dr-Wily** [comment]
I'm surprided that the answer is no ! It's may be possible [with this](https://github.com/KaeruTeam/nds-constraint).
