### ISSUE TITLE
Switch from Altwfc to BeanJrFi

### ISSUE THREAD

**Issue by vigneshd332** [barronwaffles/dwc_network_server_emulator#403]
Hey guys i know altwfc is down. I want to continue playing. But i cannot play Pokémon on BeanJrFi. So does anyone have a solutikn or a way through which i can frequently switch servers and play seamlessly. (Note: I will play only on the official servers not on my own server)

**Comment by vigneshd332** [comment]
Im playing on DesMuMe svn4319 wifi on Windows XP.

**Comment by Valkristh** [comment]
Wimmfi

**Comment by vigneshd332** [comment]
Umm dns?

**Comment by vigneshd332** [comment]
ok gotcha!
