### ISSUE TITLE
Frequent need to erase WFC Configuration.

### ISSUE THREAD

**Issue by vigneshd332** [barronwaffles/dwc_network_server_emulator#404]
Im playing in Desmume emulator. Whenever i switch games it says WFC Config does not match from System and Game Card. I have to get a new WFC ID  and then after getung the id and saving the game, when logging in, it gives an error so i have to reset the cartridge to connect. Pls help.

Emulator Build: Desmume svn4219 wifi x86
OS : Win XP x86

**Comment by Microeinstein** [comment]
I've switched permanently to BeanJrFi because Altwfc seems constantly down. I suggest you do the same.

**Comment by campanelli72** [comment]
does beanjrfi have the pokemon mystery gifts?

**Comment by vigneshd332** [comment]
Oh ok thanks.

**Comment by vigneshd332** [comment]
Thank u all
