### ISSUE TITLE
Patcher will not work 

### ISSUE THREAD

**Issue by meegs1089** [barronwaffles/dwc_network_server_emulator#406]
Every time I run any of the available patchers the command prompt window flashes and nothing happens. No text file is generated, no additional rom file is created, nothing. I have tried several different roms with more than one patcher (and multiple versions of the patcher) on more than one computer. I do have netframework 4.0 or later. Am I missing something?

**Comment by barronwaffles** [comment]
Are you dropping the file/rom into the patcher or just running the patcher itself?
