### ISSUE TITLE
Will the main server ever be up again?

### ISSUE THREAD

**Issue by campanelli72** [barronwaffles/dwc_network_server_emulator#407]
i want to be able to get the mystery gifts, and i think the main server is the only one that has them. will it be down forever?

**Comment by RayX159** [comment]
I'd like to know just that. I've tried almost every servers on the wiki without any luck. I'm playing Pokemon Soul Silver but I'm not be able to access to the GTS. If not, there is someone who knows any way around?

**Comment by SilverSzymonPL** [comment]
Does it work now?

**Comment by Valkristh** [comment]
Try using wimmfi
