### ISSUE TITLE
Personal Server not reachable from outside

### ISSUE THREAD

**Issue by VegaASM** [barronwaffles/dwc_network_server_emulator#410]
Hello, I got my own server up and running (for awhile now, but it's only been for inside my home network). So I wanted to make the server reachable from anyone. I have my public IPv4 address in the dnsmasq.conf file. I tested from my Wii putting my public IP on the Primary/Secondary DNS settings. Connection to my server was successful.

However, I have a friend in the UK try to connect to my server and there's no response at all.
- I have ports 80,443,9001,9009,28910,29900,29901,and 29920 open on TCP
- All ports are open on UDP

I noticed Nintendo also used ports 27900 (gamespyQR server) and 27901 (gamespy natneg server), do I need to open these ports too?

My friend deleted his save data and changed his Wii Internet DNS settings to my IP, but every time he tests the Wii connection, he gets a 52XXX error code saying connection not successful. On my server, it is showing that nobody is making a connection attempt (no availability request from wiinat). Help?

**Comment by Masamune3210** [comment]
Do you have a static public IP address, most isps are dynamic unless requested

**Comment by VegaASM** [comment]
Yes, I do have a static Public IP.

**Comment by kyle95wm** [comment]
I would highly recommend signing up for a VPS provider like [DigitalOcean](https://m.do.co/c/73770570fab7) or if you want to go extremely cheap, you get get a server for $2.50/month over at [Vultr](http://www.vultr.com/?ref=6916131)

If you use the DigitalOcean link above, you get $10 of credit. That's enough to get you two months of free service. Vultr used to have a similar system but they discontinued that sadly.

**Comment by sh98** [comment]
If you have a static IP then just host it on your own.

All you need to do is port forward which you can find here: https://www.youtube.com/watch?v=AwMK6Ul1Iw8&t=146s
