### ISSUE TITLE
Other servers with download content?

### ISSUE THREAD

**Issue by Darkmech** [barronwaffles/dwc_network_server_emulator#412]
I am interested in the download content of "Solatorobo" and "Inazuma Eleven 2".

**Comment by lucs28** [comment]
I would also like to know about this, since I really want to download other banlists for Yugioh WC 2010

**Comment by JzargoTheMage** [comment]
I attempted to connect to the WFZwei server to get the Mystery Gift events for Platinum, seeing as their copy does have the dlc folder and files present, but only received a "Download Failed" error message upon searching for them. Error code 31020, system date set to 1/7/2009.

Update: Same error code on 1/19/2009, when both should be accessible to my EN cartridge. I think setting the actual date for the events, however, (4/20/2009 as my test for the Rotom Key) gave me the 20100 error for the official Nintendo servers being down.

**Comment by barronwaffles** [comment]
Sorry about that @JzargoTheMage - I don't think the code for date based distribution of mystery gifts exists in the current codebase. I'll re-implement it this weekend.

**Comment by JzargoTheMage** [comment]
Alright! Give me a poke when you do, so I don't forget to check in again.

**Comment by barronwaffles** [comment]
Sorry, just found it - I've not touched this side of the server yet so I'm still quite unfamiliar with it.
I'll try figure out why it's not returning anything.

**Comment by barronwaffles** [comment]
@JzargoTheMage - would you be able to request another gift so I can read the log output?

**Comment by JzargoTheMage** [comment]
I can't immediately, but soon.

**Comment by JzargoTheMage** [comment]
@baronwaffles I'm going to attempt to connect now, system date set to 1/7/2009.

**Comment by JzargoTheMage** [comment]
Hmm. This time it gave me the 20100 error, yet connection test is successful when attempted after. And again a 20100.

**Comment by JzargoTheMage** [comment]
Yep, still a solid 20100. I'm going to attempt the wipe of my connection settings and do one more attempt before I'll have to quit for the night.

**Comment by barronwaffles** [comment]
20100 is a nebulous error due to the reconnection problems associated with the SSL patching (the console itself needs to be powered down between connections).

I'm seeing the request yet it seems to stumble after the first response. I'll log some traffic here when I can pick up a pokemon game and see what's going on.

**Comment by JzargoTheMage** [comment]
Alright. Though I have been restarting the system between checks because of how the DS lite works, I have to in order to change the date and such.

Anyways, my final test still connected fine but still no longer gives the error downloading message, just 20100.

**Comment by barronwaffles** [comment]
@JzargoTheMage - would you be able to make one more request for me?

**Comment by JzargoTheMage** [comment]
Sure, but then I've got to be off for the night.

**Comment by JzargoTheMage** [comment]
Okay, back to the same download failed message as before.

**Comment by barronwaffles** [comment]
Thanks, I'll hopefully have this resolved in the next few days.

**Comment by lucs28** [comment]
May I ask what other games have downloadable content on WFZwei or where is the list of available dlc?

**Comment by barronwaffles** [comment]
it's currently only the mystery gifts

**Comment by Darkmech** [comment]
So there is no solution for my problem?, Until "altwfc" is online. TuT

**Comment by barronwaffles** [comment]
Unfortunately, as I don't think it's possible for me to scrape the DLC with the server in its current state.

@JzargoTheMage - mystery gifts *should* function now.

**Comment by barronwaffles** [comment]
@JzargoTheMage - just tested, mystery gifts function now.

**Comment by JzargoTheMage** [comment]
Alright, I will give it another try now and update this comment once my attempt has been made. Now only if it were easier to tell which mystery gifts are what.
-----
52100 error on first attempt, 1/1/2009.
1/2/2009 gives "The Secret Key!" for the Rotom key.
1/3/2009 gives "Regigigas is here!"
1/4/2009 gives "The Member Card!" for access to the Canalave inn for catching Darkrai.
1/7/2009 gives "Arceus has arrived!"
1/12/2009 gives "Get Oak's Letter!" for catching Shaymin.
1/14/2009 gives "Pikachu-colored Pichu!" which is self-explanatory​.
1/19/2009 gives "The Legendary Trio of Johto!"
1/21/2009 and 1/23/2009 are the other two branches of this event set.
1/27/2009 gives the Celebi event.
1/28/2009 gives the Ash's Pikachu event.
1/29/2009 gives the "Battle in Kona" Crobat event.

It appears the events included here were not all strictly WiFi events, such as the Worlds Crobat, TRU Arceus, and I believe the Regigigas. I believe the Celebi was originally a GameStop event. This is all I can say off of what I can see and what I remember off the top of my head, but perhaps someone else can update me on what originally came from where with a bit of research. For now, I'm heading off.

**Comment by malekairmaroc7** [comment]
So, did it work with the dates you said @JzargoTheMage ?
