### ISSUE TITLE
Getting error 23400 on my own hosted server

### ISSUE THREAD

**Issue by Marfjeh** [barronwaffles/dwc_network_server_emulator#413]
After setting the server up on a clean linux VM.

the wii, (dolphin emulator) can communicate with the dwc server. when starting mario kart, then i get Error `23400`

The VM is running Ubuntu Server 16.04.2 LTS.

i did use the installer.sh

did i miss something?

**Comment by VegaASM** [comment]
Try this (solved my 23400 problem)
Add this line to your apache2.conf :

HttpProtocolOptions Unsafe LenientMethods Allow0.9

**Comment by Marfjeh** [comment]
Awesome, i'll try it when i'm home. and i'll report back. thanks :)

**Comment by Marfjeh** [comment]
it works! Thank you @zak289
