### ISSUE TITLE
Error code while I'm trying to connect

### ISSUE THREAD

**Issue by MaeSchiffer** [barronwaffles/dwc_network_server_emulator#415]
I'm trying to config my desmume on Altwfc server but when I try to test the conection I have this error: "Error Code: 20100 Unable to connect with this Nintendo WFC ID."
Why have I this error? Is because the server is offline or what is the problem?
And do someone know when will be Altwfc online again?
Thank you very much.

**Comment by Darkmech** [comment]
the server is offline 

[https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers](url)

**Comment by Darkmech** [comment]
[https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers](url)

**Comment by MaeSchiffer** [comment]
I know, that is why I'm asking. I asked if I have that error because the server is offline or if i have that error because another problem with my pc.

**Comment by MaeSchiffer** [comment]
I found it.

https://github.com/polaris-/dwc_network_server_emulator/wiki/Troubleshooting
