### ISSUE TITLE
Change "NoSSL" to "AltWfc"

### ISSUE THREAD

**Issue by DamianCh99** [barronwaffles/dwc_network_server_emulator#416]
Hi, I need help, when I drag the ROM to WfcPatcher, the game comes out with the wrong extension, the NoSSL comes out, please help solve this. The game I want to patch is platinum pokemon.

**Comment by Link2738** [comment]
Hmmmm...... Ok i'll explain it to you. The "NOSSL" Allows the game to bypass the SSL checks when you change the DNS in the wifi menu. In short the patcher allows you to change the DNS and connect to the ALTWFC Servers. It's patching fine. If you want rename the file and remove the (NOSSL) before the extension.

**Comment by vigneshd332** [comment]
It's fine no problem
