### ISSUE TITLE
Error 23404 on my NDS

### ISSUE THREAD

**Issue by Myscat** [barronwaffles/dwc_network_server_emulator#417]
Everything is done as it should, i patched the ROM and put a copy of it on my Flashcard, then i got to the access point, connected, changed the DNS as the server request, but somehow i keep getting 23404 error. Are the servers down or i'm doing something wrong? i havent found ways to fix this error, so if you guys can help, i would be glad. Thank you

**Comment by barronwaffles** [comment]
Odd - are you sure you have patched the rom correctly?

What game were you attempting to connect with?
