### ISSUE TITLE
Lost Magic Ds Duel anyone pls ?

### ISSUE THREAD

**Issue by lopusu** [barronwaffles/dwc_network_server_emulator#419]
This game is my childhood and i never played the duel in this game
Anyone does it still play this game and wanna battle to me in this game ?

**Comment by barronwaffles** [comment]
You will have more success asking on the IRC channel.

**Comment by lopusu** [comment]
How ?

**Comment by barronwaffles** [comment]
There's a link provided on the main page : [https://qchat.rizon.net/?channels=altwfc](https://qchat.rizon.net/?channels=altwfc)

Be prepared to wait for a response - there's always people online but plenty of them are idle.

**Comment by barronwaffles** [comment]
I'm seeing your requests in chat but it's at an odd time zone compared to me - try in the weekend and I'll have a match with you.
