### ISSUE TITLE
Ultimate Mortal Kombat DS

### ISSUE THREAD

**Issue by BevP90** [barronwaffles/dwc_network_server_emulator#422]
Has anyone tested this game? And if so, does it work online?

**Comment by Valkristh** [comment]
I tested the EU and USA roms and don't work :(

**Comment by BevP90** [comment]
Thanks for the reply, I wonder why it doesn't go through and connect, odd. Really wanted to play this online against people.

**Comment by barronwaffles** [comment]
It possibly requires the gamestats 2 service - try a connection on the test Zwei server and see if that succeeds.

**Comment by BevP90** [comment]
Thanks for the reply, this is all completely new to me so any advice or heads up is helpful. Just need to pick up an R4 card and hope for the best.

**Comment by Valkristh** [comment]
It's working! omg! I'll try with friends right now

**Comment by BevP90** [comment]
Really? Oh shit I gotta get on UMK3. Damn I need to get an R4 card. If so, we gotta play some matches dude. I never got the chance to play UMK3 online.

**Comment by Valkristh** [comment]
Yes it's working fine i tested the eu rom

**Comment by BevP90** [comment]
I have no idea how I will connect my DS. Really don't want to have to set my security down to WEP.

**Comment by barronwaffles** [comment]
Do you have the option to enable a guest network?

**Comment by BevP90** [comment]
I might be able to on the settings, it's my housemate's router so I really shouldn't tamper with it too much.
UMK3 and Puzzle Kombat, so good. Really need to find other players.

**Comment by BevP90** [comment]
> It's working! omg! I'll try with friends right now 
Did you get to test it out with someone?

**Comment by BevP90** [comment]
> It's working! omg! I'll try with friends right now

Did you get a chance to test it out with someone?

**Comment by Valkristh** [comment]
Yes with two friends

**Comment by BevP90** [comment]
> Yes with two friends

Are you free anytime soon? I got this working online, I wanted to play a couple matches of UMK3

**Comment by barronwaffles** [comment]
I could *play* a few rounds now if you would like? Log into the IRC chat.

**Comment by BevP90** [comment]
> I could play a few rounds now if you would like? Log into the IRC chat.

Join my Discord, several people here.

**Comment by BevP90** [comment]
Deception, Armageddon and UMK DS online play. 40 people here and counting.
We need some UMK3 matches some time! 
https://discord.gg/ekYX5aa
