### ISSUE TITLE
Mario Kart issues

### ISSUE THREAD

**Issue by jnbeta** [barronwaffles/dwc_network_server_emulator#423]
I did everything on my wii, used usb loader gx and play mario kart and go online, the connection is suscessful , i select worldwide or regional and it is searching for opponents and it takes longer then an hour? Why does this happen?
I delete all of my saves and created a new one.

**Comment by FrostedGeulleisia** [comment]
The reason may be as simple as, there might be no one playing when you were searching, or everyone might just already be in a single full room. This never was an issue with the official servers as lots of people were playing on them constantly...

**Comment by ghost** [comment]
If you want to play with many players, play on the wiimmfi server : wiimmfi.de
