### ISSUE TITLE
52100 Error on my emulator

### ISSUE THREAD

**Issue by KirbyFan102** [barronwaffles/dwc_network_server_emulator#424]
This is my first time trying to use this server. I'm using a Desmume emulator, and the AltWFC server.
There are no problems with my internet, and i'm using the proper DNS Adress, yet when I try to connect to the server, I get a 52100 error code!

What should I do to fix this problem?

**Comment by BevP90** [comment]
I have no idea either, I've tried everything. I've used Hamachi, the loopback driver and my ethernet connection. It doesn't seem to matter what my settings are, I always get the error.  I got Desmume to go online once, and that was 3 years ago. I'm thinking I'll just suck it up and give in to buying an R4 card.
