### ISSUE TITLE
[Request] Port this system into Luma3ds please!

### ISSUE THREAD

**Issue by weirdal3333** [barronwaffles/dwc_network_server_emulator#425]
Start with just the DS version, then move on to all of the games!

It would really open up the communities! Imagine a Pokemon League being able to SoftBan rulebreakers (for poor sportsmanship) from their server TEMPORARILY! 
You could even do local Wifi play with your friends in another state and a ddns!

**Comment by weirdal3333** [comment]
In the end, I see an ipv6 address with the game name (and related info) dynamically encoded into a sharable QR code. This could be generated through the Rosalina menu!

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
If your talking about 3DS games? Haha, no. The 3DS uses PRUDP [ https://www.3dbrew.org/wiki/PRUDP ] (Pretty Reliable UDP) meaning this will ONLY work on DS/Wii, sorry dude. However if your talking about patching DS games on the go you can use NitroHax.

**Comment by mm201** [comment]
This project is a reimplementation of the GameSpy protocol suite, or at least the subset of it used by DS and Wii games. 3DS is a completely different platform which does not use GameSpy and is totally outside the scope of this project.

A 3DS private server isn't a bad idea for when the official servers inevitably go defunct, but it bears no relation to this project and will need to be built from the ground up.

PS. You're completely wrong about it "opening up" the communities. As long as official servers exist, private servers do the opposite, splitting the player base into the majority who'll continue to use the official servers (as they should), and the minority who know about the private server and want to be isolated from everyone else for some reason.
