### ISSUE TITLE
52200 Error on my emulator

### ISSUE THREAD

**Issue by lryx1993** [barronwaffles/dwc_network_server_emulator#429]

**Comment by lryx1993** [comment]
please help me！ I set up my server but can't connect to it,  it always shows error 52200!

**Comment by ghost** [comment]
52200-52203: This error seems to appear when attempting to connect to the server multiple times without properly disconnecting first. Reboot your console and try again.

**Comment by lryx1993** [comment]
![image](https://user-images.githubusercontent.com/30574182/29597501-88c6ea96-87f5-11e7-82a9-c4a69de73828.png)
![image](https://user-images.githubusercontent.com/30574182/29597545-d8b575b8-87f5-11e7-8124-5719917a6691.png)

when i try to buil the solution, there are build errors, what can i do?

**Comment by ghost** [comment]
Pls. Create a new Issue

**Comment by lryx1993** [comment]
all right
