### ISSUE TITLE
Problem connecting - Error 20100 HELP!

### ISSUE THREAD

**Issue by AlexBirchi** [barronwaffles/dwc_network_server_emulator#435]
Hello i've been searching a lot about my error , found many like mine , but never a solution.

First, I am using a TP-Link Router (if that is important to know).

I changed the security to WEP in order to connect to the DS, I patched my rom wich i have on a R4 card and i did every step. Introduced the DNS 104.131.93.87 , tested the connection and it works! But , when i am in game and i try using for example GTS, random battle , etc.  it won't connect, giving me the error 20100.

I tried it with Pokemon HG and Black 2 , doesn't work on both. I was wondring how can it be solved , do i have to do something to my router? Do i have to do something to my console ? Anything? Please answer , i really want to play via wi-fi with friends.

**Comment by dmoeenm** [comment]
Stop testing the connection just go straight into the online function you want to use as if you test before you do you get that error  and another thing i recommended testing the global terminal /gts features as they don't lock you out as if you go into the wifi club or mystery gift you will get locked out and forced to reset your ds then you c an use the features again and what i mean is either quit out the game (3ds,2ds,dsi) or turn on and off again  (ds lite and down)

**Comment by AlexBirchi** [comment]
i think there is a problem with my internet provider

**Comment by sh98** [comment]
If you're running this over LAN, there are no problems with you internet provider.

**Comment by sh98** [comment]
In most cases, you'll be trying to connect to AltWFC or one of the servers on the "List of Servers" page. In this case, there may be something wrong with your internet provider.

Are you using `Dolphin`?

**Comment by AlexBirchi** [comment]
what is dolphin? my router is tp link and in my country the internet provider is called digi. i think is something related to it :s

**Comment by fancythedeveloper** [comment]
Dolphin is a GameCube and Wii emulator.

**Comment by AlexBirchi** [comment]
I don't have any emulator  , i have a ds lite and r4 card. i don't know about running it on lan, what's that about?
