### ISSUE TITLE
how to Creating a pkmnFoundations server?

### ISSUE THREAD

**Issue by lryx1993** [barronwaffles/dwc_network_server_emulator#436]
1.it's OK when build "branch: sqlparam_factory", there were all build errors when build "branch: master". 
2.I can't understand "then put the files into the root of the server (the root of the area accessible via webbrowser",  should i upload all files after building, or i just need upload files after folder deploy?

**Comment by barronwaffles** [comment]
Why not ask on the applicable repository?

**Comment by lryx1993** [comment]
what's applicable repository? i am not good at English.

**Comment by barronwaffles** [comment]
This is the DWC server emulator repository, not the Pokemon Foundations one. You should ask your question there (or preferably in a community/support forum - the github issue report system isn't exactly the _correct_ place to ask for technical support)

**Comment by lryx1993** [comment]
I'm sorry, it's my fault.
