### ISSUE TITLE
Infinite Loading Loop (MKWii) (Wii)

### ISSUE THREAD

**Issue by Maritoguionyo** [barronwaffles/dwc_network_server_emulator#439]
I'm trying to connect with AltWFC on Wii, but I only get a Infinite loading loop.
I have tryed to restart a lot of times, but it just doesn't want to connect. (Im using the Ocarina code to go online by the way).

**Comment by VaronBros** [comment]
Try using the plain DNS without ocarina

**Comment by Maritoguionyo** [comment]
Do you mean just the DNS?

**Comment by Maritoguionyo** [comment]
thanks but It already work for me. instead of using the Ocarina code I just patched the game.

**Comment by Maritoguionyo** [comment]
BrainSlug works too with real time patching.
