### ISSUE TITLE
Settings incorrect?

### ISSUE THREAD

**Issue by Adelvos** [barronwaffles/dwc_network_server_emulator#440]
When I try to save the WFC connection settings, it simply says that they are incorrect and won't let me progress. Do I need to put in the SSID as well as the DNS?

**Comment by vigneshd332** [comment]
Correct settings:
SSID: SoftAP
WEP Key: leave it blank
Auto Obtain I Address: Yes
Auto Obtain DNS: No
Primary DNS: Any server Dns.
Secondary DNS: Same As Primary. 

Hope it helps!
Cheers, Vk.
