### ISSUE TITLE
How would I run this in Desume?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [barronwaffles/dwc_network_server_emulator#442]

**Comment by Chriscox462** [comment]
I remember there being an older version of desmume that has wifi support.

**Comment by vigneshd332** [comment]
Google and download 'desmume svn4219 wifi.exe'

**Comment by fancythedeveloper** [comment]
There is a 0.9.12 2015 build of DeSmuME that has Wi-Fi.
