### ISSUE TITLE
23404

### ISSUE THREAD

**Issue by SilverSzymonPL** [barronwaffles/dwc_network_server_emulator#443]
I patched pokemon heartgold and pokemon diamond and put them in 2 different desmume folders with different firmware settings but mac address the same. I successfully connected multiple times in heartgold but when I try a connection test in diamond I get error 23404. what am I doing wrong?
When I run the game in my 1st ds folder it works, but in the second one it doesn't, EVEN THOUGHT THE SETTINGS ARE EXACTLY THE SAME AND ONLY 1 RUNS AT A TIME. I even deleted firmware settings and started again but it still doesn't work!

**Comment by SilverSzymonPL** [comment]
When I run the game in my 1st ds folder it works, but in the second one it doesn't, EVEN THOUGHT THE SETTINGS ARE EXACTLY THE SAME AND ONLY 1 RUNS AT A TIME. I even deleted firmware settings and started again but it still doesn't work!

**Comment by fancythedeveloper** [comment]
I think AltWFC (and others) don't exactly like working with "Test Connection" on Pokèmon Generation 4 games.
