### ISSUE TITLE
Error to try aleatory fight in Pokemon White 2

### ISSUE THREAD

**Issue by naruhishi** [barronwaffles/dwc_network_server_emulator#444]
Trying to get into the random pairing of white pokemon 2 tells me that I can not take part in a Wi-Fi turnaround or in a random pairing because my nintendo DS shuts down while in a random battle, asks me to wait 1 hour and have passed almost 24 hours and still I still show the same error, any ideas?

**Comment by mm201** [comment]
Can't say I've seen that one, but there is a problem that you never get matchmade. (https://github.com/polaris-/dwc_network_server_emulator/issues/162)
