### ISSUE TITLE
How can I start up the server (Windows 10/Ubuntu14.04)

### ISSUE THREAD

**Issue by Maritoguionyo** [barronwaffles/dwc_network_server_emulator#445]
I was trying to make a private server on windows, but I don't know how (For Testing).

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
You can use Cygwin or if you have Windows 10 you can use Bash on Ubuntu on Windows.

**Comment by kyle95wm** [comment]
I haven't tested my install script on the Windows Bash system, but it should work in theory.

**Comment by Maritoguionyo** [comment]
I use Windows 10 32 bits :/

**Comment by Maritoguionyo** [comment]
How can I redirect my server to dns form (IP Adress   blablabal.nintendowifi.net

**Comment by Maritoguionyo** [comment]
how can i use apache (usbwebserver)

**Comment by Maritoguionyo** [comment]
I already run the master server, but I don't know  if I need to open ports for the DNS (Ubuntu)

**Comment by Maritoguionyo** [comment]
I worked for lan for now. I don't know if it works as external (ubuntu).
now how can I run this on windows?

**Comment by Maritoguionyo** [comment]
How can I make an External DNS ?
