### ISSUE TITLE
{DeSmuMe_svn4219_wifi.exe} (Windows 7) Dragon Quest IX Disconnection Problem 

### ISSUE THREAD

**Issue by Narnian21** [barronwaffles/dwc_network_server_emulator#447]
Recently me and a friend started playing Dragon Quest 9 on the DeSmuMe emulator and I looked into the possibility of a multiplayer game. After several hours of attempting to get things working, it seems that there is an issue either with my computer or something I have no idea how to fix.

Basically, I can get the Emulator to recognize the altWFC test server (104.131.93.87) and establish "connection":
<details>
<summary>Settings / Successful Connection</summary>

![error4](https://user-images.githubusercontent.com/32785219/31571605-de4c1648-b0e1-11e7-9d11-f8f0b89abc46.PNG)

![error3](https://user-images.githubusercontent.com/32785219/31571606-e995032a-b0e1-11e7-8708-9f0ad9f18def.PNG)

![error5](https://user-images.githubusercontent.com/32785219/31571612-f9b45c4c-b0e1-11e7-8ad6-774f61699fe0.PNG)

</details>

 But then on the emulator console I notice this (green dot indicates connection, red indicated disconnection):

![error6](https://user-images.githubusercontent.com/32785219/31571616-1cb35e28-b0e2-11e7-8a22-0db68b9ae9d1.PNG)

Several online videos indicated this was normal, as I did not require a connection at this time. However, after loading the game and enabling other players to join my game, I noticed that the "wifi connection" icon had a no bar connection, and the console was spamming the "WIFI: SoftAP DISCONNECTED" message indicated above (red dot).

<details>
<summary> No Bar Connection </summary>

![error1](https://user-images.githubusercontent.com/32785219/31571641-918b91f2-b0e2-11e7-9fb6-63cc75f4e679.PNG)``

</details>

A similar no bar connection was experienced when searching for other games to join.
This is the video I used to configure my emulator wifi:
https://youtu.be/Fq4GIKnM-gU

Thanks for the assistance.

**Comment by barronwaffles** [comment]
I don't think this game actually used WFC/Online for the multiplayer component, did it?
There was/is some online features (an auction house and DLC quests?) but the coop element was local wireless only.

**Comment by koenhoeijmakers** [comment]
Co-op was local wireless only yes. But there was a "wifi store" which would give you 64 extra quests and seasonal items etc, i suppose there's no other way to receive them than hacking them in.
