### ISSUE TITLE
how to set up a server from a fresh installation of Windows（Windows server2012/xp）

### ISSUE THREAD

**Issue by hwj0629** [barronwaffles/dwc_network_server_emulator#450]
It is difficult for the player,who live in Chinese, to connect to foreign websites(104.131.93.87).
I am going to set up a server in China,but i don't konw how to use linux.In addition i want to set a pkmnFoundations (GTS and Battle Video) server.However,pkmnFoundations can only be run on Windows.
So,I want to run AltWFC on Windows for me to run AltWFC, GTS and Battle Video server on one Windows computer.

**Comment by hwj0629** [comment]
@polaris- @kyle95wm @Maritoguionyo 

Could you help me?

**Comment by hwj0629** [comment]
start at windows10 cmd

F:\dwc_network_server_emulator-master>python master_server.py
Traceback (most recent call last):
  File "master_server.py", line 23, in <module>
    from gamespy_player_search_server import GameSpyPlayerSearchServer
  File "F:\dwc_network_server_emulator-master\gamespy_player_search_server.py", line 24, in <module>
    from twisted.internet.protocol import Factory
ImportError: No module named twisted.internet.protocol

**Comment by sepalani** [comment]
Altwfc was working perfectly on my Windows XP, Windows 7, Windows Server 2012 and Ubuntu 12.04. I'm also quite confident that pkmnFoundations can work under Linux. It might work with Mono or Wine.

@hwj0629 
Regarding your error, it seems you didn't install the requirements: https://github.com/polaris-/dwc_network_server_emulator#requirements

I strongly suggest that you check how to configure/host a server. Otherwise, you'll get stuck with most steps since you'll have to configure an HTTP daemon such as Apache (you can use WAMP on Windows) and other steps like that.

**Comment by hwj0629** [comment]
can i use iis?  @sepalani

**Comment by sepalani** [comment]
No idea. But if you don't know how to use Microsoft IIS I advise you not to do so and use a more user-friendly/supported method. WAMP is close enough regarding the the Apache configuration whereas IIS is completely different and I haven't heard someone running these servers on it yet. It might be possible but not as well documented.

**Comment by hwj0629** [comment]
@sepalani 
could you tell me how to set apache?

Now my nds can connect my server when wifi testing.However,it shows me ”Error Codes 20100” when i try to connet in the game

**Comment by sepalani** [comment]
Google is your friend. Keep in mind it might slightly differ depending on your version.

Here is the virtual host configs you have to setup: https://github.com/polaris-/dwc_network_server_emulator/tree/master/tools/apache-hosts

**Comment by hwj0629** [comment]
sadly,google is ban in china....
i dont know how to use that .conf. It is different between windows and linux of apache

**Comment by sepalani** [comment]
I'm pretty sure you can find the answer with any decent search engine.

Regardless, it shouldn't be different, AFAIK. You have to setup vhosts if you want to redirect servers to the appropriate ports used by altwfc. For instance, the following Nintendo servers uses the port 80: NAS server, Gamestats2, Sake servers (which have been mapped to different ones by altwfc). If you don't do that, you won't be able to connect to them. The error code 20100 usually occurs when there are NAS server issues.

I had to enable vhost on WAMP under Windows and put these rules in the config file located there:
> S:\wamp\bin\apache\apache2.4.9\conf\extra\httpd-vhosts.conf

If you don't care about Gamestats2 and Sake servers, you can just change enable the alternative config:
https://github.com/polaris-/dwc_network_server_emulator/blob/master/altwfc.cfg
```INI
[Config]
AlternativeConfig = ON
```
