### ISSUE TITLE
Trying to connect Jam with the Band (NDS) for DLC songs

### ISSUE THREAD

**Issue by ltlynx** [barronwaffles/dwc_network_server_emulator#451]
I'm trying to connect to the servers using Jam with the Band (original cartridge + AR DSi on DS Lite) and I can't connect to any server.
These are the error codes I get:
- AltWFC: 52200 (I have read it's temporary offline, so I think it's all right)
- WFZwei and VaronFi: 20100 (these are supossed to be online, so I don't understand why the connection fails)

**Comment by barronwaffles** [comment]
That code would possibly imply that the action replay cheat isn't being applied or doesn't function - would you be able to jump on IRC at some point? Here's a link to the channel - [#altwfc](https://qchat.rizon.net/?channels=altwfc)

**Comment by kyle95wm** [comment]
VaronFi’s profile server crashed yesterday under heavy traffic. It has since been restarted. All logins should work now, as long as you are using an allowed game.

**Comment by ltlynx** [comment]
I'm having trouble again.
- AltWFC: I can connect to the server and see all the songs, but, whenever I try to download one of them, I get error 31020.
- WFZwei: I can connect to the server, but no song appears in the list.
Please, could someone help me? Thanks in advance.

**Comment by ltlynx** [comment]
- VaronFi: can't connect to the server, error 23800.

**Comment by kyle95wm** [comment]
VaronFi and servers running forks of CoWFC use error 23800 as a “sorry this game is not activated”

**Comment by barronwaffles** [comment]
@ltlynx there's possibly something not configured correctly on the main altwfc server - @polaris- ?

**Comment by kyle95wm** [comment]
@ltlynx which game are you trying to connect with? VaronFi only has about 3 games whitelisted (MKW, MKDS and Smash I believe)

Error code 23800 is only relevant to the CoWFC installations such as VaronFi and BenFi. All other servers likely use dwc_network_server_emulator's base code which does not have a games whitelist.

**Comment by ltlynx** [comment]
> @ltlynx there's possibly something not configured correctly on the main altwfc server - @polaris- ?

Could you get the data into the WFZwei server? That would be great. :)

**Comment by barronwaffles** [comment]
@ltlynx it should be functional now.

**Comment by ltlynx** [comment]
@barronwaffles It totally is! Thank you a lot! I also tried connecting without a cheat device using my original games and my NN3DS and it went all right, even a DSi title.
Thanks again :) You could now close this issue.
