### ISSUE TITLE
Website "https://varonfi.cf" unsafe?

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#452]
Hello. So I went to go check to see if anyone was online on Varon-Fi. So, a security certificate error has appeared bla bla bla, and then when I went to go to the website anyways, a white page appeared with a message saying "HI" on the top left of the page. So did I get compromised in any way, or am I fine? Just in case if there is anything malicious about that website, please change it from "https://varonfi.cf" to "http://varonfi.cf", removing the s in the https in the list of servers page. Thanks!

**Comment by sh98** [comment]
Hi, I'm Person.
The website is NOT unsafe, it's just that the certificates are borked up :P 
Also, the server doesn't work, so there will be nobody on it. You're not compromised.

EDIT: I've changed https://varonfi.cf/ (secure, but with cert errors) to http://varonfi.cf/ (not secure, but no cert errors)

**Comment by benjamin238** [comment]
Hi! I'm a developer from the VaronFi team and currently, we're having some issues switching from our VPS to our locally hosted servers. The site isn't under attack, but that "HI" is being caused by our apache virtual hosts not being set up correctly.

**Comment by ghost** [comment]
Ahh okay. Thanks! Glad to know that it's not an unsafe website. :)
