### ISSUE TITLE
This project is dead and....

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#453]
..... dont use it ,because it was developed by pokeacer ,guy who is with big N ,not with Us. FUCK U Pokeacer i trusted U

**Comment by the4anoni** [comment]
Polaris left this project long time ago.....

**Comment by fancythedeveloper** [comment]
(someone close this lfmao, this isnt gonna help)

**Comment by Antviau** [comment]
What the fuck dude? This page as been updated last week by polaris!
Stop saying stupid things please!

**Comment by the4anoni** [comment]
Check code bro. Also check when i posted that

**Comment by barronwaffles** [comment]
Please, close this issue.

**Comment by the4anoni** [comment]
Ok
