### ISSUE TITLE
Error 23800

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#454]
Spanish:

Al intentar acceder a la GTS en Pokemon Perla me sale el error 23800. No se ni que es este error ni como se soluciona ¿Alguien me podria ayudar por favor?

Descripcion del error: La Conexión Wi-Fi de Nintendo tiene un volumen de tráfico demasiado elevado o el servicio se ha interrumpido. Vuelve a intentar conectarte más tarde.

El DNS que estoy usando es: 45.77.98.67

Gracias.

English (Google Traslate):

When trying to access the GTS in Pokemon Pearl I get error 23800. I do not know what this error is or how it is solved. Would someone help me please?

Error description: Nintendo Wi-Fi Connection has a high traffic volume or the service has been interrupted. Try again to connect later.

The DNS that I am using is: 45.77.98.67

Thanks.

**Comment by kyle95wm** [comment]
The meaning of 23800 at VaronFi is that only a select few games are allowed. Please give me the Game ID of the game you are trying to connect with so I can enable it at VaronFi.

**Comment by ghost** [comment]
Pokémon Pearl. Edit: Game id? How do I get the id of the game? I think the id is this: Pokémon Pearl APAE-31D0AFDE (US, but I use Eu) look it up online. But it did not specify the region of the game. (google traslate)
![capt2222ura](https://user-images.githubusercontent.com/34074740/33376411-5147178c-d4ec-11e7-9f09-c2f9fdc89622.PNG)

Pokemon Perla version (SP): APAS-f5737dd4

**Comment by ghost** [comment]
Spanish:

He solucionado el problema conectandome al servidor principal (104.131.93.87). Y he dejado un Pickachu en la GTS. Una pregunta: ¿Puedo crear una Issue para avisar de que he subido un pokemon a la GTS? ¿Puedo abusar del glitch de la clonacion mediante GTS? Desde luego gracias por leer y por contestar

English:


I have solved the problem by connecting to the main server (104.131.93.87). And I've left a Pickachu in the GTS. One question: Can I create an Issue to warn that I have uploaded a pokemon to the GTS? Can I abuse the glitch of cloning using GTS? Thanks for reading and answering

**Comment by Valkristh** [comment]
Hay un grupo de fb más o menos activo donde se juega e intercambia pokemon, puedes tratar ahí, no creo que sea conveniente avisar cada vez que dejas un pkmn en la gts, ya que existe una página donde los usuarios pueden ver que pkmn está disponible.

**Comment by ghost** [comment]
Ya lo encontre gracias

**Comment by kyle95wm** [comment]
Okay, I've activated game ID APA at VaronFi. Try now

**Comment by Valkristh** [comment]
Se llama JUEGOS DS ALTWFC
https://mobile.facebook.com/groups/408602245998267?ref=bookmarks

**Comment by ghost** [comment]
Spanish:

Lo intente pero ahora me aparece una pantalla azul al intentear conectar. Este el el mensaje: Ha habido un error de conexión. Porfavor, apaga la consola DS y vuelve a intentarlo.

English (Google translate):

I tried but now a blue screen appears when trying to connect. 
This is the message: There has been a connection error. Please turn off the DS console and try again.
![captu33333ra](https://user-images.githubusercontent.com/34074740/33483112-fe8b7890-d67a-11e7-9c21-a6c3fd0494f7.PNG)

DNS: 45.77.98.67

**Comment by ghost** [comment]
Spanish:

Una pregunta: ¿el servidor principal (104.131.93.87) esta online? Pregunto porque ayer (Jueves 30/11/2017) me pude conectar a la GTS. Pero hoy (Viernes 1/12/2017) no. Hoy aparece el error 23502

English (Google translate):

One question: is the main server (104.131.93.87) online? I ask because yesterday (Thursday 30/11/2017)  I could connect to the GTS. But not today (Friday 1/12/2017). Today error 23502 appears

**Comment by ghost** [comment]
Spanish:

Al intentar conectarme al servidor principal (104.131.93.87) me aparecio el error 52200. Este error lo solucionaba reiniciando el desmume. Pero no funciono, hasta en la prueba de conexion sale este error (cosa que jamas me habia pasado). Ayuda porfavor

English (Google translate):

When trying to connect to the main server (104.131.93.87) error 52200 appeared. This error solved it by restarting the "desmume". But it did not work, even in connection test comes out this error (which had never happened to me). Please help

**Comment by Valkristh** [comment]
El dns principal está offline, lo puedes comprobar en la wiki, regalos misteriosos a veces funcionan, lo mismo para la gts, debes tener paciencia por algún motivo que desconozco está offline

**Comment by ghost** [comment]
Okay, pero si no me equivoco el error 52200 es cuando te conectas por primera vez, y ayer me pude conectar al server principal

**Comment by Valkristh** [comment]
Jamás tuve ese error en consola, no se como será en emulador, pero mencionaste haber conectado a otro dns más arriba, entonces puede interpretarse como primera conexión al server al oficial quizá, de todas maneras en el troubleshooting ese error tiene que ver con tratar de conectarse demasiadas veces sin desconectar como corresponde

**Comment by ghost** [comment]
esque yo la primera vez que me conecte logre solucionar ese error reseteando, pero ahora no funciona. hasta borre la configuracion de la CWF a ver si se solucionaba pero no

**Comment by Valkristh** [comment]
Así es como se soluciona, reseteando la consola o en tu caso emulador, pero cada vez que intentas conectar haces prueba de conexión?

**Comment by ghost** [comment]
No, de hecho la primera vez que me logre conectar (ayer) este error me salio el primer intento hice reset y se soluciono. Esa primera vez el test de coneccion fue bien, pero ahora este mismo error tambien sale en el test. Nose k hacer

**Comment by ghost** [comment]
Otra pregunta: ¿La sala union es con CWF? porque si puedo entrar a la sala pero no puedo entrar a la GTS

**Comment by Valkristh** [comment]
No es necesario hacer el test cada vez que vas a intentar conectar, es por eso que el server (que por cierto sigue OFFLINE) interpreta que conectas y desconectas a cada rato y te da ese error, el test es obligatorio una vez después de borrar wfc.
(https://github.com/polaris-/dwc_network_server_emulator/wiki/Troubleshooting)
Sobre la sala union no tengo idea la verdad

**Comment by ghost** [comment]
Okay, aunque no entiendo eso de que este offline si es que ayer me conecte, haste deje un pickachu en la GTS como puedes comprobar: http://pkmnclassic.net/gts/ (lo pones en modo 4ta gen, yo soy el que se llama LEÓN) Porcierto no hago el test cada vez que me conecto

**Comment by Valkristh** [comment]
Lo mencioné más arriba a veces funciona la gts y regalos misteriosos, otras no, aquí puedes ver que sigue offline
https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers

**Comment by ghost** [comment]
Acabo de conectarme a la GTS, por lo visto son puros errores que se solucionan solos. Intercambie un Haunter por un Machoke, asi que funciona.

**Comment by ghost** [comment]
Valkristh ¿Juegas pokemon? Se que no es el lugar para decirlo pero acabo de subir un darkari de evento legal a la GTS de Perla. Y como tu me ayudaste a entender algunos errores, pues te aviso para que lo consigas antes que nadie.

Use este metodo para conseguirlo: https://www.youtube.com/watch?v=SVlzbWZpmzU

**Comment by Valkristh** [comment]
Si, juego heartgold, pero no puedo reclamar ese darkrai porque no lo he visto xD
Y la mayoría de pkmn de eventos se pueden conseguir por regalo misterioso en todo caso

**Comment by Supremeaccess** [comment]
¿Y no puedes poner un bidoof pidiendo un darkrai? Porque yo puedo poner un pokemon pidiendo un mew y jamas lo he visto

**Comment by fancythedeveloper** [comment]
English: I believe VaronFi now supports Pokèmon Diamond (and Pearl) now.

Spanish: Creo que VaronFi ahora es compatible con Pokèmon Diamond (y Pearl) ahora.

(used google translate lol)
