### ISSUE TITLE
Lubuntu 16.04 : Server installed but can't connect to it

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#458]
Hi everybody,

I follow the instructions on the wiki to setup the server ( automatic and manual method ) but i can't connect to it. There is no answer. I test the connection on the same computer ( client and server are both on the same computer ) . The server is setup for local mode, not external .

> [2017-12-14 15:18:10 | GamespyDatabase] [1I9nvbIM] STARTING: CREATE TABLE IF NOT EXISTS users (profileid INT, userid TEXT, password TEXT, gsbrcd TEXT, email TEXT, uniquenick TEXT, pid TEXT, lon TEXT, lat TEXT, loc TEXT, firstname TEXT, lastname TEXT, stat TEXT, partnerid TEXT, console INT, csnum TEXT, cfc TEXT, bssid TEXT, devname BLOB, birth TEXT, gameid TEXT, enabled INT, zipcode TEXT, aim TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [1I9nvbIM] DONE: Took 0.0153799057007 real time / 0.000416 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [VORmmRSw] STARTING: CREATE TABLE IF NOT EXISTS sessions (session TEXT, profileid INT, loginticket TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [VORmmRSw] DONE: Took 4.29153442383e-05 real time / 4.2e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [5cs2IpGa] STARTING: CREATE TABLE IF NOT EXISTS buddies (userProfileId INT, buddyProfileId INT, time INT, status INT, notified INT, gameid TEXT, blocked INT)
> [2017-12-14 15:18:10 | GamespyDatabase] [5cs2IpGa] DONE: Took 2.38418579102e-05 real time / 2.2e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [QKdjrX4Y] STARTING: CREATE TABLE IF NOT EXISTS pending_messages (sourceid INT, targetid INT, msg TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [QKdjrX4Y] DONE: Took 2.09808349609e-05 real time / 2e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [69exu0NH] STARTING: CREATE TABLE IF NOT EXISTS gamestat_profile (profileid INT, dindex TEXT, ptype TEXT, data TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [69exu0NH] DONE: Took 2.19345092773e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [qLYkbP7Q] STARTING: CREATE TABLE IF NOT EXISTS gameinfo (profileid INT, dindex TEXT, ptype TEXT, data TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [qLYkbP7Q] DONE: Took 2.09808349609e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [Hz9AHepZ] STARTING: CREATE TABLE IF NOT EXISTS nas_logins (userid TEXT, authtoken TEXT, data TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [Hz9AHepZ] DONE: Took 2.09808349609e-05 real time / 2e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [CtqApm24] STARTING: CREATE TABLE IF NOT EXISTS banned (gameid TEXT, ipaddr TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [CtqApm24] DONE: Took 2.00271606445e-05 real time / 1.9e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [LhK028YD] STARTING: CREATE TABLE IF NOT EXISTS pending (macadr TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [LhK028YD] DONE: Took 2.50339508057e-05 real time / 2.3e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [16LyGkCf] STARTING: CREATE TABLE IF NOT EXISTS registered (macadr TEXT)
> [2017-12-14 15:18:10 | GamespyDatabase] [16LyGkCf] DONE: Took 2.00271606445e-05 real time / 1.9e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [Xby05Onm] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS gamestatprofile_triple ON gamestat_profile(profileid,dindex,ptype)
> [2017-12-14 15:18:10 | GamespyDatabase] [Xby05Onm] DONE: Took 2.59876251221e-05 real time / 2.5e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [e1tkmYRG] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS users_profileid_idx ON users (profileid)
> [2017-12-14 15:18:10 | GamespyDatabase] [e1tkmYRG] DONE: Took 2.31266021729e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [HS8DkZU6] STARTING: CREATE INDEX IF NOT EXISTS users_userid_idx ON users (userid)
> [2017-12-14 15:18:10 | GamespyDatabase] [HS8DkZU6] DONE: Took 2.50339508057e-05 real time / 2.4e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [mM3ZDaAR] STARTING: CREATE INDEX IF NOT EXISTS pending_messages_targetid_idx ON pending_messages (targetid)
> [2017-12-14 15:18:10 | GamespyDatabase] [mM3ZDaAR] DONE: Took 2.69412994385e-05 real time / 2.6e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [eEi4WlgR] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS sessions_session_idx ON sessions (session)
> [2017-12-14 15:18:10 | GamespyDatabase] [eEi4WlgR] DONE: Took 2.28881835938e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [zILI91dN] STARTING: CREATE INDEX IF NOT EXISTS sessions_loginticket_idx ON sessions (loginticket)
> [2017-12-14 15:18:10 | GamespyDatabase] [zILI91dN] DONE: Took 2.21729278564e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [TNgquzll] STARTING: CREATE INDEX IF NOT EXISTS sessions_profileid_idx ON sessions (profileid)
> [2017-12-14 15:18:10 | GamespyDatabase] [TNgquzll] DONE: Took 2.59876251221e-05 real time / 2.4e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [9HLt0e6v] STARTING: CREATE UNIQUE INDEX IF NOT EXISTS nas_logins_authtoken_idx ON nas_logins (authtoken)
> [2017-12-14 15:18:10 | GamespyDatabase] [9HLt0e6v] DONE: Took 2.21729278564e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [X2w8KzPU] STARTING: CREATE INDEX IF NOT EXISTS nas_logins_userid_idx ON nas_logins (userid)
> [2017-12-14 15:18:10 | GamespyDatabase] [X2w8KzPU] DONE: Took 2.21729278564e-05 real time / 2.1e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [nH7CoK7D] STARTING: CREATE INDEX IF NOT EXISTS buddies_userProfileId_idx ON buddies (userProfileId)
> [2017-12-14 15:18:10 | GamespyDatabase] [nH7CoK7D] DONE: Took 2.09808349609e-05 real time / 2e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [my4RFjNx] STARTING: CREATE INDEX IF NOT EXISTS buddies_buddyProfileId_idx ON buddies (buddyProfileId)
> [2017-12-14 15:18:10 | GamespyDatabase] [my4RFjNx] DONE: Took 2.40802764893e-05 real time / 2.3e-05 processor time
> [2017-12-14 15:18:10 | GamespyDatabase] [Clul9Ac8] STARTING: CREATE INDEX IF NOT EXISTS gamestat_profile_profileid_idx ON gamestat_profile (profileid)
> [2017-12-14 15:18:10 | GamespyDatabase] [Clul9Ac8] DONE: Took 2.21729278564e-05 real time / 2.2e-05 processor time
> [2017-12-14 15:18:10 | GamespyBackendServer] Started server on 127.0.0.1:27500...
> [2017-12-14 15:18:10 | GameSpyProfileServer] Now listening for connections on 0.0.0.0:29900...
> [2017-12-14 15:18:10 | GameSpyPlayerSearchServer] Now listening for player search connections on 0.0.0.0:29901...
> [2017-12-14 15:18:10 | GameSpyGamestatsServer] Now listening for connections on 0.0.0.0:29920...
> [2017-12-14 15:18:10 | AdminPage] Now listening for connections on port 9009...
> [2017-12-14 15:18:10 | RegisterPage] Now listening for connections on port 9998...
> [2017-12-14 15:18:10 | GameStatsServerHttp] Now listening for connections on 127.0.0.1:9002...
> [2017-12-14 15:18:10 | StorageServer] Checking for and creating database tables...
> [2017-12-14 15:18:10 | NasServer] Now listening for connections on 127.0.0.1:9000...
> [2017-12-14 15:18:10 | GameSpyNatNegServer] Server is now listening on 0.0.0.0:27901...
> [2017-12-14 15:18:10 | GameSpyQRServer] Server is now listening on 0.0.0.0:27900...
> [2017-12-14 15:18:10 | GameSpyServerBrowserServer] Now listening for connections on 0.0.0.0:28910...
> [2017-12-14 15:18:21 | StorageServer] Now listening for connections on 127.0.0.1:8000...

Any ideas please ? Before creating my server I try to connect the client on the servers listed in the wiki and all work without issue so I saw that I have a problem with the setup of my server.

**Comment by barronwaffles** [comment]
The first thing I'd investigate would be checking that your PC is using the correct DNS resolver to locate the required URLs (*.nintendowifi.net) - see if `nslookup test.nintendowifi.net` responds with the appropriate internal IP address.

If that looks correct then there's likely something not quite right with your httpd - check that you have the correct host and port proxy configurations

**Comment by ghost** [comment]
Sorry for the late answer. I updated one of my projects on Github. Here is the result of the command : 

> Server:		127.0.0.1
> Address:	127.0.0.1#53
> 
> Name:	test.nintendowifi.net
> Address: 192.168.1.48

I see my internal IP address so I think according to your message that it is correct. So it will be my httpd. How to check correctly the host and port proxy configurations according to your experience ?

**Comment by barronwaffles** [comment]
Largely depends on the httpd being used - if possible join the official [IRC channel](http://kiwiirc.com/client/irc.rizon.net/altwfc) and I'll attempt to help troubleshoot.

**Comment by ghost** [comment]
Issue solved thanks to ideas and suggestions of barronwaffles on IRC chat. Server and Client cannot be on the same machine. I tested on another computer and with a 3DS as clients : connection without issue in the two cases on the server.
