### ISSUE TITLE
How can I play a random matching on pokemon black?

### ISSUE THREAD

**Issue by wogn2001** [barronwaffles/dwc_network_server_emulator#459]
guys I live in korea and i have wanted to play random match so much so that i studied a lot about how to.
finally I reached to success in test but in game, i fail.
the 104.131.93.87 seems to be closed and the 45.77.98.67 and others seems not to apply pokemon random matching. I can't wait so If there is someone who know solutions, Please help me. Thank you.

**Comment by fancythedeveloper** [comment]
You're gonna have to use friend codes for this. Also, I don't know if random matchmaking is supported on Pokèmon Generation 5.
