### ISSUE TITLE
An attempt at cleaning up the Virtual Hosts .conf files

### ISSUE THREAD

**Issue by VegaASM** [barronwaffles/dwc_network_server_emulator#460]
EDIT: Issue solved.

**Comment by zak289** [comment]
UPDATE: found the fix, but it only works when using registered custom domains.

I used a hex editor and forced all 6 nas domains to listen on port 81 (6 lines of nas domains to edit). Updated apache to listen on 81 along with 80 obv. And it worked. Now I can remove that silly HttpProtocolOptions from apache2.conf

If you do this method, your domain name with the ':81: added must be shorter than nintendowifi.net.

Remember to add back the "/ac" and /pr" after the :81 back on the nas domains.

NOTE: This doesnt work with naswii, domains must be nas
