### ISSUE TITLE
Mega Man Star Force

### ISSUE THREAD

**Issue by SMR95** [barronwaffles/dwc_network_server_emulator#461]
I've been playing Mega Man Star Force Dragon (I have Lv 100) on my DS Lite, however, I do not know anyone who plays these games. This is why I am trying to make a BrotherBand between Mega Man Star Force Dragon and Mega Man Star Force Pegasus on the same PC using DeSmuME, however, there is always an error that says that the brother code is wrong. I followed all the configuration steps to the letter but I do not know if there are compatibility problems or if I am not doing well in DeSmuME. Can someone give me a hand?

Thank you!

**Comment by Valkristh** [comment]
Try connecting your console with pc

**Comment by SMR95** [comment]
Thanks for giving me your recommendation.

Unfortunately, it was not possible to connect the two games. Maybe the service is not developed for MMSF 1 or maybe the version of DeSmuME that I have is not good.
Can someone who uses this emulator help me?

Thank you!

**Comment by barronwaffles** [comment]
@SMR95 - mind jumping on [IRC](http://kiwiirc.com/client/irc.rizon.net/altwfc) at some point so I can help nail down what's causing issues? I think I've seen one of the Megaman titles attempt to use an unimplemented feature.

If you don't get a reply instantly just hang around.

**Comment by SMR95** [comment]
Hello everyone!

Again I tried to connect the MMSF Dragon and MMSF Pegasus games, this time I used an NDS Lite and an NDSi. The games connect perfectly to the WFC and the player's profile is successfully updated to obtain the Friend Code. This Friend Code is necessary to establish a connection between them, however, it is not possible to connect them, an error is always generated and it says that the code entered is incorrect.

Before the AltWFC server was offline at the end of 2017 the connection was established perfectly, now it is impossible. I am not aware of the code and I do not know how it could help solve the problem, however, I could help you with what is within my reach. If a MegaMan lover has the knowledge and is willing to review the problem, do not hesitate to contact me.

Thanks for your attention.

**Comment by Valkristh** [comment]
If the problem is with the friend code, the only thing i can think to solve this, is deleting WFC configuration and make a new friend code

**Comment by SMR95** [comment]
It's not that easy, it has a problem. User BarronWaffles found that it could be an issue with how it's storing + sending the personal data. It's stuck at the "Downloading Friend's info" stage.

**Comment by barronwaffles** [comment]
@SMR95 - try again and see if you have any luck (might require new friendcodes).
