### ISSUE TITLE
Error Code 23404

### ISSUE THREAD

**Issue by fancythedeveloper** [barronwaffles/dwc_network_server_emulator#463]
I get this error when doing the "Test Connection" thing on Pokèmon Pearl.

I had this problem on both AltWFC and VaronFi.
![pokemon_pearl_usa_nds-lgc nossl __6626](https://user-images.githubusercontent.com/30706150/35165077-e6947162-fd1a-11e7-92e5-52e7315910bd.png)

**Comment by kyle95wm** [comment]
Problems on VaronFi were fixed a day or so ago so you shouldn't have a problem.
