### ISSUE TITLE
FFCC: EoT - Keep getting error 20100

### ISSUE THREAD

**Issue by MadCatLynx** [barronwaffles/dwc_network_server_emulator#466]
Hi all!

I'm having some issues with Final Fantasy Crystal Chronicles: Echoes of Time.

I am using DSLite with R4 SDHC (YS Menu). I tried using a clean (US) ROM with AltWFC patcher, as well as the WFC replay patcher. 
I added the codes required to bypass the SSL but whenever I try to test connection or try to save and go online in-game, I get error 20100. 

I even tried switching up DNS addresses.. Nothing works.

I'd really appreciate some leads as to how to fix this issue. 
Thanks in advanced for your support!

**Comment by AlexBirchi** [comment]
They don't know how to fix it. I had this problem for about 1 year. still no fix. But in my opinion is due to the internet provider or something like that.. try with another connection.
