### ISSUE TITLE
Connection Problems to own Server (23502)

### ISSUE THREAD

**Issue by Spygot** [barronwaffles/dwc_network_server_emulator#470]
I just set up an Server in my local network to play Mario Kart DS via LAN. But when i tried to connect using the local ip of the server (configured that in the setup) it gave me Error 23502 (High Traffic or Server Down). I am no using Linux very long but i think there are too many errors during the init. I clipped a screenshot of it on this post and i hope you can help me with that problem.  I can also add the code in an answere if you need it. 
![screenshot wfcserver](https://user-images.githubusercontent.com/36778597/36622175-2dd0f63e-18fc-11e8-8b7e-d9a601999ea3.png)

**Comment by Dr-Wily** [comment]
What is your network conf on both side (server & DS) ?

**Comment by Spygot** [comment]
The Server was set up with the local IP of the Computer (192.168.2.127,LAN) and the DS was an DesMuMe Emulator on a Windows 10 PC (LAN). I tried to connect with the local IP.

**Comment by Spygot** [comment]
I now solved the Problem with the errors (Server was running twice) but i still can't connect. DesMuMe gives me error 52100. On the Ubuntu PC i can see if someone uses the admin page. But still i am unable to connect, the console doesn't even show me that some DS would try to connect. The Emulator is fine, connecting to an other DNS works.
