### ISSUE TITLE
Error 20100 when connecting to own server.

### ISSUE THREAD

**Issue by Antviau** [barronwaffles/dwc_network_server_emulator#471]
Hi I created recently a server for my wii but when I try to connect to it it give me the error 20100.
But my game is correctly patched my network working and all dns are configured on my box and computer. Help? Also I can connect to my ip and see the stats and acess the admin page.

**Comment by ghost** [comment]
Because nobody takes the time to help you, I will share you a solution. Have you on the Wii change the DNS IP on the parameters of the Wifi connection ? Like in the DS, you must set the DNS on the Wii to the IP of your server
