### ISSUE TITLE
Server on Raspberry Pi?

### ISSUE THREAD

**Issue by FlitPix** [barronwaffles/dwc_network_server_emulator#474]
Hello! I was wondering if it would be possible to host a server on a Raspberry Pi 3 with Raspbian (with only a few people, ten at most, using it)? I saw that it was possible to host one on an Ubuntu computer, so I was wondering if it were possible on Raspbian?

**Comment by MisterSheeple** [comment]
It's possible. Raspbian is a variant of Linux, so yes, it is possible.

**Comment by FlitPix** [comment]
Well, I was able to do it by following the guide, so thanks for answering!
