### ISSUE TITLE
(Bug) The Add Wiimmfi/CTGP Support option in Installer just exits the installer.

### ISSUE THREAD

**Issue by MisterSheeple** [barronwaffles/dwc_network_server_emulator#476]
3/14/2018 Update: Just talked to BeanJr, the creator of the installer script, and he said that the option should be removed, so I guess it has no purpose. I will just keep this open until he or someone else fixes it or at least notices.

**Comment by kyle95wm** [comment]
I decided to remove that menu option. It was redundant since the script now makes the Wiimmfi stuff mandatory. Feel free to close this.
