### ISSUE TITLE
unable to connect to altwfc

### ISSUE THREAD

**Issue by vigneshd332** [barronwaffles/dwc_network_server_emulator#477]
i am unable to connect to altwfc by using wifi adapter in my laptop (hp-241) running windows 8.1.
emulator is desmume svn4219. using patched roms with winpcap. getting error(access point not in range)

**Comment by vigneshd332** [comment]
Error code 52000

**Comment by vigneshd332** [comment]
Sorry 52001

**Comment by kyle95wm** [comment]
[Info on error code 52001](https://wiimmfi.de/error?e=52001)

**Comment by vigneshd332** [comment]
Thx
