### ISSUE TITLE
Wi-Fi Club issue on Pokemon Games

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#478]
Questions about the wiki : Is the project pkmn-classic-framework needed to play battles and exchange pokemons with a Friend Code ?

**Comment by barronwaffles** [comment]
It's an external component that enables various pokemon specific functionality (GTS most notably).
I'm not entirely sure but I think a few titles use *plain* WFC functions for basic friend trading/battling.

**Comment by ghost** [comment]
Because if the Wi-Fi club can work with dwc_network_server_emulator, this is good for me ( exchange can be done on Wi-Fi club instead of GTS ) . That why I wanted confirmation about it.

**Comment by ghost** [comment]
Do we need special DNS configurations on a dwc_network_server_emulator for Pokemon Games for Wi-Fi Club support only ?

**Comment by ghost** [comment]
Nothing work when using Wi-Fi Club on Pokemon Games with a personnal server.
Do we use special configurations on the server ?
