### ISSUE TITLE
Nintendo Wi-Fi support not working anymore ( but marked as working according to the Wiki ) 

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#479]
Hi everybody,

I tested some on the informations on the Wiki about the compatibility.
Even with an external or a personnal server, multiplayer wifi is not working according to your datas. Here is some examples (I haven't tested all the datas of the wiki) :
-> Pokemon Wifi-Club can't trade or battle with friends ( in the two cases : external and personnal server ) , Mondial Battle is not working / GTS only working ( with the external server that has the pkmn-classic-framework (104.131.93.87) )
-> Star Fox Command game : the players are detected : One player has a framerate to 100%, the others no. But all the players can get the game working at 100% on solo.

Can you explain me what is the problem ? If it isnt a problem on my side, that's not normal that Wiki has bad informations / mistakes about the compatibility list.

**Comment by barronwaffles** [comment]
I've played Starfox Command and know that it functions fine - are you using an emulator or real hardware?

**Comment by ghost** [comment]
Emulator and real hardware side : 
- my special version of Desmume that have the WiFi support - 0.9.12 ( https://github.com/JackoboLeChocobo/DeSmuME-Reloaded )
- Tested with DS Games on a Nintendo 3DS ( not the XL version )

**Comment by barronwaffles** [comment]
The compatibility list generally only covers real hardware - it's known that WFC play via emulation/desmume has issues with many titles.

**Comment by ghost** [comment]
I know that people doesn't like Desmume and his developpers, but it is easy to say that... Why the information "The compatibility list generally only covers real hardware" is not present in the wiki ?

**Comment by barronwaffles** [comment]
It wasn't intended to be a personal statement about the program or its developers - I don't know/care enough about either to form an opinion  - it's just a known issue that a large number of titles don't function well via WFC.

I'll append that information to the wiki now.
