### ISSUE TITLE
Error 20100 (Mario Kart Wii / AltWFC) PLEASE HELP (i use dolphin)

### ISSUE THREAD

**Issue by CrocodileCroco** [barronwaffles/dwc_network_server_emulator#481]
Hi i wanted to connect to altwfc, but it keeps having error 20100, using pem files does not work, restarting the router and deleting save files does not work too !
Can you please help me??? 😞

**Comment by barronwaffles** [comment]
Is this via Dolphin? Make sure you have enabled the NoSSL cheat or patched the iso, then configure the DNS setting on your network adapter - google should be able to provide you with a guide on how to do this.

**Comment by CrocodileCroco** [comment]
I have patched the iso, where do i configure the DNS, on windows settings? on router?

**Comment by barronwaffles** [comment]
You could do either, but doing it inside Windows would be the more *friendly* choice.

**Comment by CrocodileCroco** [comment]
I think it's working ! Thank you! But now i have error 61070 🤔

**Comment by barronwaffles** [comment]
Interesting... as a test try one of the alternative servers listed [here](https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers) and see if you still have the same issue (will likely require a new save file).

**Comment by CrocodileCroco** [comment]
Do i need to change windows dns to connect to alternative servers?

**Comment by CrocodileCroco** [comment]
and also it's a ctgp iso patched to be compatible with altwfc

**Comment by barronwaffles** [comment]
Yes, that will require you to change the DNS again.

I'm not familiar with the modified Mariokart Wii stuff, so I don't know if that is causing/can cause issues.

**Comment by CrocodileCroco** [comment]
I tried with VaronFi, and it makes 20100 error again

**Comment by CrocodileCroco** [comment]
Using zwei.moe makes 20100 error too

**Comment by CrocodileCroco** [comment]
Changing DNS on both Ethernet and WiFi still makes 20100 error code

**Comment by CrocodileCroco** [comment]
also when i configure DNS on windows, it does not let me change the secondary dns to the same as the primary one

**Comment by Lilicogamer13** [comment]
i having the same problem, but with wiimmfi
