### ISSUE TITLE
Dinosaur King DLC

### ISSUE THREAD

**Issue by DinoOtaku** [barronwaffles/dwc_network_server_emulator#482]
Have you the DLC Mysteries Dinosaurs from Dinosaur King ? For example, the Pachycephalosaurus or the Deinonychus.

**Comment by barronwaffles** [comment]
It looks like the content for it is on the server - it might be worth testing.

**Comment by DinoOtaku** [comment]
The content is for all versions or japanese version only ?

**Comment by DinoOtaku** [comment]
And thank you.

**Comment by barronwaffles** [comment]
It looks like there's content for all versions.

**Comment by DinoOtaku** [comment]
Ok thanks.

**Comment by DinoOtaku** [comment]
I managed to connect in your server but I can not find how to get the DLCs of this game.

**Comment by barronwaffles** [comment]
Sorry, I'm not familiar with the game so I don't know what's required to obtain the DLC content.
I can only recommend looking around online - gamefaqs is usually a safe bet for issues like this.

**Comment by KurumiSly** [comment]
Last question, I don't find the date for the french event of Deoxys in the 5 gen, in particular the item number.

**Comment by KurumiSly** [comment]
Last question, I don't find the date for the french event of Deoxys and Zekrom in the 5 gen, in particular the item number.

**Comment by DinoOtaku** [comment]
What is the content of the Dinosaur King (EU) DLC ?

**Comment by barronwaffles** [comment]
I don't know, you would need to check in-game.
