### ISSUE TITLE
White Screen on retail cartridge + AR DSi

### ISSUE THREAD

**Issue by yeoxl** [barronwaffles/dwc_network_server_emulator#488]
I'm currently encountering white screen on boot with a retail copy of **Professor Layton and the Curious Village** and AR DSi played on NDS Lite / DSi XL. Just white on both screens, not able to load into the Nintendo Logo.

I did not encounter any issues with the sequel retail copy of **Professor Layton and the Diabolical Box**, the AR code generated was successfully inputted into AR DSi and was able to connect to AltWFC to unlock the weekly puzzles. 

Both my retail cartridge are in USA region and I use clean rom dump obtain from my retail cartridge.

Any help would be greatly appreciated, I prefer playing a legal copy over the original hardware.

* **Operating system: Win10** 
* **WfcReplay version: 0.7** 
* **ROM information: NTR-A5FE-USA (Clean Dump from Wood Dumper)** 
* **Tested on: NDS Lite / DSi XL (both experiencing same issue)** 

* **::Bypass HTTPS v0.7 for [A5FE] LAYTON1**
5209B348 EE070F90
E200007C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2DD93CD 0009000A
0005000B 0012000E
004D015E 00000000
0209B348 E92D401E
0209B34C FAFD934A
D2000000 00000000

**Comment by barronwaffles** [comment]
If you have a flashcart I'd suggest trying nitrohax, as I'm certain that I was able to get my copy of Curious Village online using it.

Interestingly my situation is the reverse of yours - I couldn't get Diabolical Box online using this method (resulted in a white screen).

**Comment by yeoxl** [comment]
Hi barronwaffles, thanks for introducing me nitrohax. May I know the details of your setup? 

Are you using nitrohax on the NDS / 3DS as there are two version. 

Is your copy of your **Professor Layton and the Curious Village** a retail copy or rom file? If it's a retail copy is it in USA / EU region?

**Comment by barronwaffles** [comment]
I've used both the NDS/flashcard and 3DS releases at various times, but my most common use case is on a flashcart with a cart-detect switch modified DSi XL.

My exact copy is the AU/NZ release, but I'm fairly certain that's the same as the US release.

**Comment by yeoxl** [comment]
Thanks barronwaffle, I've tried nitrohax using flashcart swap to retail cart (USA) on my NDS and it still gives me a white screen upon boot up. Strange, I know for a fact that the patch for WfcReplay will generate slightly different code for different region game cartridge. Unfortunately I do not have a EU/AU copy to test if the issue lies with different region cartridge.

If anyone reads this, would you be kind enough to test if your USA copy of **Professor Layton and the Curious Village** is able to inject WfcReplay code successfully to connect to AltWFC, thanks!

**Comment by barronwaffles** [comment]
Sorry, I just ran the game again and I'm running into the same issue - I'm not sure if I'm incorrectly  remembering or not though, as I have the weekly puzzles unlocked and I didn't touch the game till the original WFC was closed.

An alternative solution would be to use a save dumper along with modified rom to acquire the DLC before restoring the save to the original cartridge (I've definitely done this for Contact).

**Comment by yeoxl** [comment]
You are really a great help, I'm adamant about playing my original copy of Curious Village and I have thought of injecting save into my retail cartridge.

barronwalffles, are you referring to this method? **https://gbatemp.net/threads/nds-backup-tool-wifi.252623/**

I'm leaving this as my last resort for fear that it might corrupt my save file or even worst, damage my retail cartridge permanently. Any thoughts?

**Comment by barronwaffles** [comment]
There's a 3DS application that is a bit easier to use, but that guide should also work fine.

I don't think it's possible for it to damage the cart permanently, but it's a good idea to keep the original save dump as a backup.

**Comment by yeoxl** [comment]
Noted, I'll give an update if I manage to inject my save back into my cartridge.

**Comment by yeoxl** [comment]
Hey barronwaffles, which nossl patcher did you use for your rom dump? I used WFCpatcher v1.6 but was unable to run the game successfully in my R4. Sigh, my options are quite limited with all my fail attempts to unlock the weekly puzzles.

**Comment by barronwaffles** [comment]
You might have luck using the flashcart cheat engine - I also ran into a few roms that wouldn't boot after using WFCPatcher.

I generated a NoSSL cheat database [here](https://github.com/barronwaffles/NobodySSL) that covers the entire release library.

**Comment by yeoxl** [comment]
Hi baronwaffles, here's an update. I manage to find another flashcart EDGE and got WFCpatched rom running. The servers I tried to connect both gave me an error of 31020. Interestingly the progress bar during the download of weekly puzzle for **Curious Village** differs:
1) AltWFC DNS: 104.131.93.87 , the download bar hit almost 50% before I got the 31020 error.
2) WFZwei DNS: 172.104.88.237, the download bar is like 10% and I got the 31020 error.

Is the error server related? I'm so close to getting this to work! Argh* If anyone is willing to help, I don't mind sending my save dump for you to download the weekly puzzle and mail the save file back to me so that I can inject into my retail cartridge.

**Comment by barronwaffles** [comment]
@yeoxl - I just pushed a change on WFZwei, try that DNS again and see if the results are different.

**Comment by yeoxl** [comment]
@barronwaffles I finally manage to download through WFZwei server! What did you just do, may I ask?
Finally I'm able to finish downloading the "DLC", very thankful for your help!

**Comment by barronwaffles** [comment]
Strangely the files for the American release weren't present on the server, but in a (incredibly) fortunate turn it was one of the few titles I had backed up when manually scraping DLC from the original/official WFC - so I uploaded those.

Not sure how that happened, I'll try get in contact with the project owner/altwfc operator - it's possibly that an archive was simply skipped over when creating the current DLC set.

**Comment by yeoxl** [comment]
I see, that explains everything and my countless search on the forum and people suggesting to use EU version instead. Now we know the reason why I hope this post will serve as some reference and guide for others in the future. 

Update: I'm able to download "DLC" for **Professor Layton and the Last Specter (USA)**
             Download fails for **Professor Layton and the unwound future (USA)**

@barronwaffles do you mind helping me check if server WFZwei has the DLC set for **Unwound Future** thanks!

**Comment by barronwaffles** [comment]
Try downloading via zwei and I'll check the access log.

**Comment by yeoxl** [comment]
I manage to download the "DLC" for **Professor Layton and the unwound future (USA)** with a patched rom. Strangely it didn't work with my AR DSi / Nitrohax.

I finally manage to get all DLC for the 4 titles of Professor Layton, thanks barronwaffles =)

**Comment by barronwaffles** [comment]
Awesome, glad to hear.

Feel free to close the issue.
