### ISSUE TITLE
working on Twl loader (3ds) or Drastic emulator for android)

### ISSUE THREAD

**Issue by guillepecado** [barronwaffles/dwc_network_server_emulator#489]
Hello everyone. i wanted to know if this can work on twl loader (DS emulator for 3ds) or Drastic Emulator for android, just for playing pokemon games. thanks in advance!

**Comment by Maritoguionyo** [comment]
Yes it works in TWLoader (make sure TWLoader is updated though), I think it doesn't work with drastic

**Comment by guillepecado** [comment]
Awesome! Do you have any guide? So I can play HeartGold and trade and battle online?

**Comment by Maritoguionyo** [comment]
Do you have a WEP connection or open?

**Comment by guillepecado** [comment]
I have a wap / wap2 psk wifi connection with password. Why are you asking that?

**Comment by ductator** [comment]
DS Games will only connect to WEP or unencrypted WIFIs.

**Comment by guillepecado** [comment]
Thanks for the info!
