### ISSUE TITLE
New Local Server and Don't know what I'm doing!

### ISSUE THREAD

**Issue by VJ4523** [barronwaffles/dwc_network_server_emulator#490]

**Comment by VJ4523** [comment]
I'm new to this wii hacking thing. I wanted to set up a local server so I can play animal crossing with my friends from two different wiis. I used the install script on fresh install of Ubuntu 14.04, but I'm not sure where to go from here. How do I connect the wiis to the server? I know you are suppose to use the ip address of the computer your running the server on, but that's all I know. ANY help would be appreciated.

**Comment by fancythedeveloper** [comment]
Use the github wiki to help you setup.

**Comment by VJ4523** [comment]
I did look over the wiki....it dosen't say specifically how to connect a wii to a local server. Here's what I've done so far:
- Put homebrew on both wiis
- Put Usbloader gx on both
- Installed the DWC network server on a fresh install of Ubuntu 14.04

Now this is where it gets frustrating, when I typed in the IP address of my local server in the wiis dns address, it dosen't connect. I don't know if I install it right or not. Heck, I don't even know where the admin page is for the server. HELP ME PLEASE!

Just putting it out there: I have no experience with servers, I just want to play my favourite Nintendo games with my friends.

**Comment by kyle95wm** [comment]
Hi @VJ4523! I'm sorry to hear that you were having issues with my installer. When you got to the dnsmasq setup, what IP did you put in? Please check the bottom of your
`/etc/dnsmasq.conf` file and make sure that the IP address for both Nintendo and Wiimmfi, match up with the IP you would get by typing in `hostname -I` on the command line. If you need to update the address, remember to run `sudo service dnsmasq restart` after to make the changes stick.

**Comment by VJ4523** [comment]
Sorry about replying so late....I'm finally out school for the summer! I put in the LAN IP, mainly because the instruction said that was recommended. I tried these commands last night and it worked! Thank you @kyle95wm . I think before I take on a project this big ... I'll do some more research. Hey, is there any way for me to see how many consoles or players are playing at any given time?

**Comment by kyle95wm** [comment]
@VJ4523 to answer your question, yes and no.

Yes, you can see HOW MANY people are online, but there are no specifics. Just go to `http://<IP>:9001` of your server to get a stats page. To see all registered consoles, the CoWFC fork (it supersedes the DWC Network Server Emulator and the installer you used in the original post) allows you to see all registered consoles, and what type they are (Wii vs DS). I would check out the CoWFC fork. I've implemented a lot of features into it that I think you might like. I'm also in the process of writing a documentation wiki [here](https://github.com/kyle95wm/CoWFC/wiki)
