### ISSUE TITLE
Getting a white screen when I install the patch on my 3ds?

### ISSUE THREAD

**Issue by lharck** [barronwaffles/dwc_network_server_emulator#491]

**Comment by OPBreloom** [comment]
Are you using Nitrohax and have CFW?

**Comment by lharck** [comment]
@OPBreloom Just my flash card (r4i3DS RTS)'s standard firmware. I only get the white screen when I use the action replay codes / use the NOSSL patch in this video which I'm assuming is the same concept (https://www.youtube.com/watch?v=33SxxK5gskI). 

Patching everything through the executable here though doesn't show the white screen, but when I get to the Wifi settings, I don't have the option to erase previous settings.
