### ISSUE TITLE
Megaman Starforce 3 Red Joker.

### ISSUE THREAD

**Issue by OPBreloom** [barronwaffles/dwc_network_server_emulator#492]
Hi I'm using NitroHax and have a CFW 3DS, and when I try to input my Wi-Fi Password it says its invalid. Can anyone help? it's the correct password as well.

**Comment by barronwaffles** [comment]
Is the security protocol for the Wireless AP that you're attempting to connect with WEP?

**Comment by ghost** [comment]
Game dont work on altwfc anyway.

**Comment by barronwaffles** [comment]
I'm fairly certain it does - what issue did you have trying to play it?
