### ISSUE TITLE
Error code 52100 on connection test

### ISSUE THREAD

**Issue by Sleepy64** [barronwaffles/dwc_network_server_emulator#493]
So, I was getting 52000 before (unable to obtain IP address).

So I manually put in my own IP address, and I stopped getting this error. However I keep getting error code 52100 whenever performing a connection test. I input the DNS correctly (both primary and secondary) and my network is WEP-secured. I've tried just about everything but nothing works. The Action Replay code is correct. The only thing I could think of that might be giving me this error is me using AR DS instead of DSi.

**Comment by malekairmaroc7** [comment]
Which DNS do you use? That Error Code means that you maybe used a wrong DNS.

**Comment by Sleepy64** [comment]
AltWfc. I used the right one both for primary and secondary DNS.

**Comment by malekairmaroc7** [comment]
Do you have many Friend Codes? If not then try deleting Nintendo WFC Data and rewrite the data (DNS, WiFi-Settings) again.

**Comment by Sleepy64** [comment]
I tried doing that as well. Nothing seems to be working. Perhaps my router is just too new? It could literally get hacked at any second now, lol. There's almost no security on it.

**Comment by barronwaffles** [comment]
Would it be possible for you to post some images/photos of your connection settings screen?
