### ISSUE TITLE
"These settings are invalid. Confirm the information and try again."

### ISSUE THREAD

**Issue by NaturalHarmonia** [barronwaffles/dwc_network_server_emulator#496]
I patched Pokemon White and have tried to save the changed DNS settings but I keep getting this message. Any advice?

**Comment by NaturalHarmonia** [comment]
I'm still having this issue. I play on my Nintendo 3DS.

**Comment by barronwaffles** [comment]
are you able to post a screenshot of your current configuration?

**Comment by NaturalHarmonia** [comment]
No I don't believe I can.
