### ISSUE TITLE
Is it possible to set up a server for Suikoden Tierkreis or does it require additional server info that is unavailable?

### ISSUE THREAD

**Issue by Adventuresea** [barronwaffles/dwc_network_server_emulator#497]
The game allowed one to "send away" one or more teammates on missions, and receive missions from other people. The missions were all in the game, the server was needed for storing info about which characters were dispached and when (they all had timers and if the person who accepted the mission didn't return them back within the limit, the characters would return automatically - I think the game would give them back to you even if you didn't go online, as it only looked at the time to check if enough time had elapsed).

**Comment by barronwaffles** [comment]
I recall Suikoden using gamestats2 to handle that functionality - the main altwfc server is running a shim for that service but it *should* function on wfzwei / 172.104.88.237

**Comment by mm201** [comment]
The altwfc fake gamestats server always returns blank responses. It works fine to get past things like score submissions which would otherwise error out, but won't work for something like this.

**Comment by Adventuresea** [comment]
Thank you for the replies. Fortunately the game has multi-card play so you can still do them with a friend.

**Comment by barronwaffles** [comment]
Ah, that's good to hear.

It might still be worthwhile attempting it on one of the server emulators that are using the [alternative gamestats2 service](https://github.com/sepalani/GamestatsHTTP) as it *should* function without issue.

**Comment by Adventuresea** [comment]
Do you think it's up and running on them or do I have to setup a server for it somehow? I haven't done this before.

**Comment by barronwaffles** [comment]
@Adventuresea it should function fine on this DNS : 172.104.88.237

**Comment by Adventuresea** [comment]
Thanks, I'll try it and post whether it's working once I get ahold of a DS Lite compatible wifi connection agian.
