### ISSUE TITLE
How would one get this running on a raspberry pi 3?

### ISSUE THREAD

**Issue by FM1337** [barronwaffles/dwc_network_server_emulator#498]
Are there any plans to update the installer so you could run this on a raspberry pi 3? It would be rather useful for hosting LAN WFC servers so that you could just buy a cheap router and host pretty much LAN parties

**Comment by kyle95wm** [comment]
@FM1337 Yeah, use the older "dwc_network_installer" script. No matter what I've tried to do, I can't seem to get the CoWFC fork to install properly (lack of a real mysql server package and php 7.1)

**Comment by FM1337** [comment]
There's no point in keeping this issue open, I sadly haven't had the time to test this and since there's no point in running a local server anymore in my eyes, I decided to close the issue.
