### ISSUE TITLE
Server down for a week

### ISSUE THREAD

**Issue by guillepecado** [barronwaffles/dwc_network_server_emulator#499]
Hello ! some players have been having problems to connect to the server. it has been down for a week. hope yo can solve it! thanks a lot!

**Comment by kyle95wm** [comment]
This is why the community has created a [list of other servers](https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers) while the main server is offline.

**Comment by guillepecado** [comment]
you are right, but it seems to nobody plays pokemon on the others servers. besides the web page, which is amazing. thanks a lot!
