### ISSUE TITLE
Final Fantasy Crystal Chronicals Echoes of Time disconnection when using offical server

### ISSUE THREAD

**Issue by GaySquirrel** [barronwaffles/dwc_network_server_emulator#500]
I highly doubt anyone has any information about this, but I and a friend got desmume wifi working and connected to the official server via nintendo WFC. But when we try to connect to each other things go fine all the way up until the very end when the game saves after gathering the party members. basically the one inviting is fine but the visitor is dc'd... 

This sucks :( i miss this game so much and was really happy when i saw in the compatibility list this game was working

**Comment by barronwaffles** [comment]
It's entirely possible that this is an issue with the emulator (the compatibility list generally refers to playing via original hardware)  - I'll see if I can confirm this with a friend later.

**Comment by GaySquirrel** [comment]
Yeah, I was just curious. Its probably something we did XD. We tried following all the tutorials on how to set wifi up. I feel like you're right about it being an emulator issue.

**Comment by ghost** [comment]
MelonDS got online Wi-Fi support so you can try with that.
Not sure If it will work for you though
