### ISSUE TITLE
AltWFC down for years/very long time ?

### ISSUE THREAD

**Issue by flutterbrony** [barronwaffles/dwc_network_server_emulator#501]
Hi, I'm folllowing this project for some years now, but I never was able to connect to AltWFC servers everytime I try it, is it down ? What server would you recommand for pokemon and mariokart ds ?

**Comment by barronwaffles** [comment]
The main server should be functional right now.

**Comment by flutterbrony** [comment]
Nevermind, I could get it working too ^^'
