### ISSUE TITLE
Mystery Gift for PkMn Esp

### ISSUE THREAD

**Issue by JBapt23** [barronwaffles/dwc_network_server_emulator#504]
Hi there, i saddly saw that the Mystery Gift for the 5th Gen Spanish Pokemon are not implmented, maybe can you add it to the server ? the four letter codes are IRAS, IRBS, IRDS & IRES

By the way, please can you tell me how to convert a *.pgf to *.myg (tool & usage) and how to upload to altwfc servers ?

Thanks in advance

**Comment by RenegadeRaven** [comment]
To convert *.pgf to *.myg use [this](https://github.com/AdmiralCurtiss/MysteryGiftConvert).

**Comment by JBapt23** [comment]
That's good, i'm suppose that works only command line, but, how to upload to the actual servers?

**Comment by InternalLoss** [comment]
5th Generation Pokémon gifts work differently; they use IREO for Pokémon White iirc - the language is determined based off MYSTERY_X where X is a language.
