### ISSUE TITLE
Error 52000 and 52100 Unsolvable

### ISSUE THREAD

**Issue by 123321mario** [barronwaffles/dwc_network_server_emulator#511]
Hello, I tried to connect to AltWFC and WFZwei on my New 3DS XL running TWiLight Menu++ with : 
-Patched rom for AltWFC
-Unpatched rom for WFZwei
-Unsecured WiFi hotspot (4G sharing)
-Unsecured WiFi repeater
-Changing my 3DS local IP
-Using 8.8.8.8 as secondary DNS 
-Installing the server at home (It didn't worked on Ubuntu for Windows)

I tried multiple games and they're all supported : 
Mario Kart DS
Pokémon Ranger
Pokémon Ranger 2
Pokémon Ranger 3
Pokémon Diamond
Pokémon Platinium
Solatorobo
(all europe versions)

Can someone help me ? I always get errors 52000 or 52100 every single time I try to do a connection test in the settings (I use the games settings not the built in settings in the 3DS config menu) or actually connecting via the game. I remember that both servers were working on my old DS Lite last year with a flashcart but now it's broken and I don't have any physical online game. The 3DS can connect to Internet normally with the browser or online 3DS games/apps.

**Comment by Conobi** [comment]
Same here.
I can't connect at all!

**Comment by Conobi** [comment]
Re-open it! It stills occur!

**Comment by barronwaffles** [comment]
Ask somewhere more appropriate for assistance on connecting to the server - either the [official IRC channel](https://qchat.rizon.net/?channels=altwfc) or [this discord group](https://discord.gg/9vbEZkx).
