### ISSUE TITLE
Inazuma Eleven DLC

### ISSUE THREAD

**Issue by jjk1029384756** [barronwaffles/dwc_network_server_emulator#514]
I'm new to this, and after buying a copy of Inazuma Eleven from a British fellow over in the UK, I've found that there are DLCs for this game. I already knew, back when they shut down the servers for DS and Wii way back when, and want to try to get the full experience from the game. I downloaded the dwc_server_emulator_master ZIP and tried to find the YEEP file that was found under this page: https://github.com/barronwaffles/dwc_network_server_emulator/wiki/Nintendo-DS-Download-Content
and could not find it in the folder. I'm completely new to this, once again, and I'd like to find some help and to not brick my DS if possible. Thank you all for your time, and I hope to receive a helpful response in the near future.

**Comment by barronwaffles** [comment]
Follow the main connection guide (ignoring the steps regarding cheat devices / ROM patching) [here](https://github.com/barronwaffles/dwc_network_server_emulator/wiki), but use `172.104.88.237` as the DNS - this should provide you with access to the DLC.

**Comment by jjk1029384756** [comment]
Thanks Barron, but I can't connect to the internet for some reason. I don't know where else to go (cause if I contact Nintendo to help, they'd get suspicious and I know the legal stuff that went down over more simple issues) I have Xfinity wifi, and the DS says that "the access point's security settings are not supported by the Nintendo DS. For help, visit support.nintendo.com (which obviously won't help and i can't find anything for that)" Thank you again Barron for helping me with these issues, I'm looking forward to hearing your reply and a possible solution to this.

**Comment by barronwaffles** [comment]
Connecting your DS to the Internet requires either an open/unsecured or WEP encrypted access point, I can't really help you beyond that.

**Comment by jjk1029384756** [comment]
It's probably my wifi router itself. I've got to figure this out ASAP. Sorry I haven't responded in a week, and thanks for the help barron, I'll let you know how things are going when and if they get fixed
