### ISSUE TITLE
Inazuma eleven 3 i can't download the content

### ISSUE THREAD

**Issue by Bonaldyr** [barronwaffles/dwc_network_server_emulator#516]
in the game have some teams i only can play if i have ticket, but this ticket isn't more avaible since 2011, i can download this if i connect in your servers?
i already patched the roms and connect to the wifi, and the error code is 30210 
i need a specific date of the event to download them?

**Comment by TheMadCroctor** [comment]
I'm not an expert, but I saw that all of the 3 IE 3 games are on the list of compatible games so you should be able to get the dlc via the servers

I got the dlc for IE 1 and 2 setting my primary DNS to 172.104.88.237 and my secondary DNS to 8.8.8.8 make sure that you have a working connection before messing with the settings (a mistake I made) you can do that by just doing a connection test with the standard settings, it works if you get a message that says that your game isn't compatible with WiFi services anymore

I hope this explaination helps (even though I don't have a clue what that error code means)
