### ISSUE TITLE
Connected my Nintendo DS to my CoWFC server

### ISSUE THREAD

**Issue by Tris-250** [barronwaffles/dwc_network_server_emulator#519]
Hello, I installed Ubuntu, then CoWFC, I installed all the components that had to be installed before installing CoWFC, I configure the port of my Internet box, my computer with Gufw Firewall, the game of my Nintendo DS is well patched (I was able to connect to another server).
And I can access the home web page from another network, but I can not connect my Nintendo DS to my server, I get error 52100, can you help me?

To connect my Nintendo DS to the Internet I use a 4G network, my box using the protocol WPA2-PSK (AES) while my Nintendo DS supports only the open protocol or the WEP (which is not secure) but since network I can connect to the home page of my web server.

I'm using Ubuntu 16.04, can it come from the Ubuntu security update

**Comment by Tris-250** [comment]
Thank you very much

**Comment by Tris-250** [comment]
Hello, I managed to connect to my server CoWFC, it was a problem related to the firewall

**Comment by Real96** [comment]
> Hello, I managed to connect to my server CoWFC, it was a problem related to the firewall

Can i ask you how exactly you fixed this? Cause i'm getting your same error, but i can reach correctly the server using my browser
