### ISSUE TITLE
Mystery Gift 5th Gen not working

### ISSUE THREAD

**Issue by SalaKarSA** [barronwaffles/dwc_network_server_emulator#520]
Hi,
first of all, thanks for your efforts and your awesome work. I have a question regarding to mystery gift downloads of the 5th generation for German regions (black: IRBD, black2: IRED).

If I try to download a gift on my console, I receive the message that threre are no mystery gifts available. Downloads for Gen4 with the same DNS are working.

Therefore my question is, whether Gen5 games for German regions are supported or not. Moreover, if they are not supported, can I do anything in order to receive gifts / or is it even likely that they'll get support soon?

Thank you.

**Comment by pharaone** [comment]
Same problem here with an italian cartridge, no gifts found

**Comment by barronwaffles** [comment]
I'm not terribly familiar with Pokemon content, but I'll attempt to investigate this when I have some spare time.

**Comment by pharaone** [comment]
Thanks, I forgot to say that until 2 months ago both italian and German gifts where working (i've seen lots of comments in reddit saying that they where working) then suddenly they stopped working

**Comment by elosha** [comment]
I have the same problem with a German version of Pokemon White (IRAD), while it works flawlessly in Gen IV games like HeartGold. I read that Gen V would not work on DS/DSL, but still does on later consoles like the DSi. However I can't confirm that since I only own a DS Lite.

Tried with the server of pkmnclassic.net.

**Comment by h0lley** [comment]
I'd also like to request support for the german Gen 5 games.
I suppose the issue is that there's simply no data for those games in the dlc directory?
though then it's strange that it has been reported to be working in the past...

edit: here are the IDs of the games in question
```
White        IRAD
White 2      IRDD
Black        IRBD
Black 2      IRED
```

**Comment by elosha** [comment]
I've been curious and tried using White with the www.pkmnclassic.net server today. It worked without any issue, I was able to receive lots of Mystery Gifts.

But I don't see a fix in this repo regarding the issue. ;) Did they fix it locally now?

**Comment by barronwaffles** [comment]
It's likely that they recovered / generated content that doesn't exist on this server right now.

**Comment by h0lley** [comment]
> I've been curious and tried using White with the [www.pkmnclassic.net](http://www.pkmnclassic.net) server today. It worked without any issue, I was able to receive lots of Mystery Gifts.

are they even using dwc_network_server_emulator? I don't see any kind of reference to it in their git.
also, I am not getting any gifts on B2/IRED when connecting to pkmnclassic.net.

**Comment by elosha** [comment]
They reference this project in their readme:
> Direct communications are handled by [AltWFC](https://github.com/polaris-/dwc_network_server_emulator) and are outside the scope of this project. They work at the time of writing but haven't been tested that thoroughly.

The Mystery Gifts I'm getting using W (IRAD) from PkmnClassic coincides with this list:
[European Gen 5 Events](https://www.pokewiki.de/Events/5._Generation/Europa)

Maybe ask them for help or a patch?

**Comment by barronwaffles** [comment]
It previously relied on AltWFC, but I think it's likely using another service i.e Wiimmfi

**Comment by elosha** [comment]
Why "wontfix"? It should be a pretty easy fix for someone who is involved in the project. Is there any news on this?
