### ISSUE TITLE
Pokémon Pearl error 60000 on Wi-Fi Club

### ISSUE THREAD

**Issue by hfc2x** [barronwaffles/dwc_network_server_emulator#521]
Hello. I'm trying to connect to the Wi-Fi club (the one downstairs in Pokémon Centers) with my legit copy of Pokémon Pearl on my Nintendo DS Lite. [I read on GBATemp](https://gbatemp.net/threads/nds-constraint-taking-advantage-of-a-flaw-in-the-nintendo-ds-i-ssl-library.522011/page-9#post-8419393) that most Pokémon games connect just fine, but Pokémon Pearl seems to have issues for some reason.

I tried connecting with my other games, and as expected, they work just fine. Pokémon Pearl throws a connection error 60000. Can something be done about this? Pokémon GTS on the other hand works fine with any game, even Pearl.

![Error 60000](https://user-images.githubusercontent.com/8249996/59157233-23539e00-8a75-11e9-9978-4311747a35c2.jpg)

**Comment by barronwaffles** [comment]
Following [step 3 of the DS Connection Gude](https://github.com/barronwaffles/dwc_network_server_emulator/wiki#nintendo-dsdsi3ds2ds-configuration) should resolve your issue.

**Comment by hfc2x** [comment]
Ah, thank you, that solved it!
