### ISSUE TITLE
yugioh 2010 dlc doesn't work  

### ISSUE THREAD

**Issue by caiqichang** [barronwaffles/dwc_network_server_emulator#524]
yugioh 2010 dlc doesn't work ? and i can't found the dlc resource anywhere .

**Comment by barronwaffles** [comment]
It should work fine - what issue are you having?

**Comment by caiqichang** [comment]
@barronwaffles 

first, yugioh 2007, 2008, 2009, 2011 all work well, only 2010 has this problem.

when i enter the download content page, it shows:
![Uploading IMG_20190805_052802.jpg…]()

when i chose one to download, it shows:
![Uploading IMG_20190805_052751.jpg…]()

my device is Japanese edition, and i have tried:
1. rom region: Japan, Europe, USA, Korea
2. SSL or NoSSL (using cheat code)
3. Server 172.104.88.237 and 104.131.93.87

**Comment by caiqichang** [comment]
@barronwaffles 

first, yugioh 2007, 2008, 2009, 2011 all work well, only 2010 has this problem.

when i enter the download content page, it shows:
![IMG_20190805_052802](https://user-images.githubusercontent.com/20108732/62429596-0f5dad00-b743-11e9-9ea7-fbe93310db68.jpg)

when i chose one to download, it shows:
![IMG_20190805_052751](https://user-images.githubusercontent.com/20108732/62429597-14226100-b743-11e9-8d4a-d6ea55975567.jpg)


my device is Japanese edition, and i have tried:
1. rom region: Japan, Europe, USA, Korea
2. SSL or NoSSL (using cheat code)
3. Server 172.104.88.237 and 104.131.93.87

**Comment by barronwaffles** [comment]
Very interesting, just confirmed this myself.

I'll look into this further when I can find some time.

**Comment by caiqichang** [comment]
@barronwaffles 
thank you
finally i found that is due to the game itself.

![TIM截图20190823184757](https://user-images.githubusercontent.com/20108732/63587762-579c1c80-c5d7-11e9-9278-be7b703964cc.png)

![TIM截图20190823184722](https://user-images.githubusercontent.com/20108732/63587773-5c60d080-c5d7-11e9-84ef-e35f54b4d7db.png)
