### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by msikma** [barronwaffles/dwc_network_server_emulator#528]
It seems the Discord link listed on the wiki has expired.

I've generated a new one that should never expire: https://discord.gg/h7DDEzh

This should be changed [on the wiki home](https://github.com/barronwaffles/dwc_network_server_emulator/wiki) as well as [on the main website](http://altwfc.com/). (Maybe it would be useful if the site linked to the wiki instead?) I think it might be useful if this link were added to the `readme.md` file as well since it lists only the IRC channel right now.

**Comment by msikma** [comment]
This should still be changed.

**Comment by SebiderSushi** [comment]
Today i tried that link, it told me that it is also expired :(
