### ISSUE TITLE
Error 23404 with own Server

### ISSUE THREAD

**Issue by monosod26** [barronwaffles/dwc_network_server_emulator#529]
Hi, 

I'm running my own DWC server on a Raspberry Pi Zero W and set up seemed to go fine. I can access :9001 and :9008 admin page, however, when I change my PC's DNS to that of the IP of the Pi and play my WiiMMFI patched Mario Kart Wii ROM, I get error 23404.

The Raspberry Pi is running on DMZ on my router.

When I change the ports of ports.conf and 000-default.conf to port 81, I get an infinite "connecting to WiiMMFI" when I try to connect in Mario Kart.

**Comment by monosod26** [comment]
Looked at apache logs,  "page=admin&section=game%20whitelist" isn't working as well PHP Fatal error : Uncaught Error@ Class 'ConsoleWaiting'

**Comment by monosod26** [comment]
Currently using an older i5-3330m Laptop connected via Ethernet with DMZ enabled on the router for the laptop. CoWFC from EnergyCube is installed on a fresh Ubuntu 16.0 LTS OS.

**Comment by monosod26** [comment]
Issue was with patcher not with DWC

**Comment by monosod26** [comment]
Please use Patcher v3 for MKWii

**Comment by calvinhendriks** [comment]
Where can I find patcher v3?
