### ISSUE TITLE
Outdated setup procedure

### ISSUE THREAD

**Issue by sepalani** [barronwaffles/dwc_network_server_emulator#537]
The wiki is outdated and doesn't have a proper setup guide and point to outdated install script outside the repository.

TODO:
 - [ ] Install/Setup procedure for Windows
 - [ ] Install/Setup procedure for Linux
 - [ ] Address Apache2 duplicate Host header leading to Error 400 issue (HttpProtocolOptions Unsafe/mod_headers)

**Comment by barronwaffles** [comment]
Sounds like a plan - mind trying to set something up via IRC (#altwfc-dev @ rizon) at some point?
