### ISSUE TITLE
Is there a guide somewhere for setting this up to work with SSL via nds-constraint?

### ISSUE THREAD

**Issue by flarn2006** [barronwaffles/dwc_network_server_emulator#544]
I'm trying to make a Raspberry Pi image that'll host a Wi-Fi access point that'll let you store and retrieve .MIO files for WarioWare DIY. But the only setup instructions I see are about using CoWFC instead (which requires Ubuntu) and issue #81 (which doesn't include SSL setup.) I know how to make the fake certificates, but I'm not sure how to configure this code to use them.

**Comment by flarn2006** [comment]
Actually, I think I figured it out for the most part, with the help of the info in #81. I'm supposed to set up the HTTP server (I used nginx) as a reverse proxy to connect to the locally-hosted server. However, my DS (actually a 3DS running a DS cartridge) is still retrying `nas.nintendowifi.net` multiple times before failing there, as evidenced by the DNS queries it's making.

I don't know if this is the issue, but is there a way to verify whether the DS is accepting the certificate? I am using a wildcard certificate (attached) for `*.nintendowifi.net`, but I had the same issue with a `nas.nintendowifi.net` one, so I don't think that's the issue. If I connect to https://nas.nintendowifi.net/ from my PC with the same DNS redirection, the only certificate issue it warns me about is the expected one (invalid CA) which shouldn't be an issue on the DS.

**EDIT:** I did a packet capture, and Wireshark is telling me there was indeed an SSL handshake failure. But not on the DS's end, apparently. The DS initiates the connection with the Raspberry Pi and does the three-step TCP handshake. Then the DS sends the Pi a Client Hello packet. The Pi sends a TCP ACK in response, followed by a fatal SSLv3 alert, "Handshake Failure". Then the Pi terminates the connection with a FIN,ACK.

**Comment by Dr-Wily** [comment]
+1, imlementing nds-constraint into dwc_network_server_emulator would be nice to prevent patching game to remove SSL.

**Comment by Leseratte10** [comment]
Is the web server you're using accepting SSLv2 connections? Modern versions of Apache and other web servers don't (for security reasons), but that's the only thing the DS accepts: https://gbatemp.net/threads/apache-server-version-that-works-with-ssl-v3.533725/

**Comment by flarn2006** [comment]
Yeah I realized that was the problem later on and forgot to update my post.
I'll close the issue; thanks for reminding me.
