### ISSUE TITLE
Is it really necessarry to open all UDP ports? Disconnection after 1 minute.

### ISSUE THREAD

**Issue by Shynixn** [barronwaffles/dwc_network_server_emulator#545]
Hello,

I have tried putting the dwc_network_server_emulator into a Docker Container (Dockerfile, DockerImage) and was able to connect to it using Dolphin and Mariokart Wii. However, after a minute or so it disconnects me similar to issue #384 and #262. 

The following ports are mapped from the container to the host:

```
-p 53:53p -p 80:80 -p 443:443 -p 8000:8000 -p 9000:9000 -p 9001:9001 -p 9002:9002 -p 9003:9003 -p 9009::9009 -p 9998:9998 -p 27500:27500 -p 27900:27900 -p 27901:27901 -p 28910:28910 -p 29900:29900 -p 29901:29901 -p 29920:29920
```
According to to the troubleshooting page, you should open all udp ports for peer-to-peer connection but as far as I understood it, this is only necessarry between the different Wiis, not the dwc_server_emulator and the Wii. 

Does anyone have a tip for me how I can fix the disconnection after a minute? The error codes are either 94020 or 84020.

**Comment by InternalLoss** [comment]
> According to to the troubleshooting page, you should open all udp ports for peer-to-peer connection but as far as I understood it, this is only necessarry between the different Wiis, not the dwc_server_emulator and the Wii.

this is correct, opening ports is only required like this between peers, not the emulator itself. 
84020 implies that `MASTER server is down or UDP packets are being blocked`, but obviously MASTER must be reachable for you to all be playing. Is there anything showing in a log?
