### ISSUE TITLE
Nintendo WFC service for this software has been halted

### ISSUE THREAD

**Issue by GuckTubeYT** [barronwaffles/dwc_network_server_emulator#546]
I used melonDS and i setted all, when i connect, it give me error
Nintendo WFC service for this software has been halted
sorry for bad grammar

**Comment by InternalLoss** [comment]
This error indicates you're probably not connecting to AltWFC and instead connecting to regular Nintendo Wi-Fi Connection.

**Comment by barthogenes** [comment]
Yeah I think you need to add some lines to your hosts file on Windows so melonDS will connect to your local dwc server instead of the (now halted) Nintendo servers.

**Comment by GuckTubeYT** [comment]
> Yeah I think you need to add some lines to your hosts file on Windows so melonDS will connect to your local dwc server instead of the (now halted) Nintendo servers.

I tried melonds, but its still doesnt work

**Comment by barthogenes** [comment]
Add the following lines to your hosts file on Windows and try again.
Don't forget to replace all occurrences of `192.168.2.116` with the IP of your dwc server.
<details>
  <summary>Spoiler</summary>
  <img src="https://user-images.githubusercontent.com/20557666/109008045-21000000-76ad-11eb-81b4-d4b8c609d051.png" />
</details>

**Comment by barthogenes** [comment]
I've got it working for Mario Kart Wii by adding the following lines to the bottom of my `C:\Windows\System32\drivers\etc\hosts` file:
```
192.168.2.116		gamestats.gs.nintendowifi.net
192.168.2.116		mariokartwii.gamestats.gs.nintendowifi.net
192.168.2.116		gamestats2.gs.nintendowifi.net
192.168.2.116		mariokartwii.gamestats2.gs.nintendowifi.net
192.168.2.116		gpcm.gs.nintendowifi.net
192.168.2.116		gpsp.gs.nintendowifi.net
192.168.2.116		mariokartwii.available.gs.nintendowifi.net
192.168.2.116		mariokartwii.master.gs.nintendowifi.net
192.168.2.116		mariokartwii.ms19.gs.nintendowifi.net
192.168.2.116		mariokartwii.natneg1.gs.nintendowifi.net
192.168.2.116		mariokartwii.natneg2.gs.nintendowifi.net
192.168.2.116		mariokartwii.natneg3.gs.nintendowifi.net
192.168.2.116		mariokartwii.sake.gs.nintendowifi.net
192.168.2.116		naswii.nintendowifi.net
192.168.2.116		mariokartwii.race.gs.nintendowifi.net
192.168.2.116		nintendowifi.net
192.168.2.116		nas.nintendowifi.net
192.168.2.116		dls1.nintendowifi.net
192.168.2.116		sake.gs.nintendowifi.net
```
Replace `192.168.2.116` with the IP address of your private server.
Maybe this will work for melonDS aswell.

**Comment by GuckTubeYT** [comment]
> I've got it working for Mario Kart Wii by adding the following lines to the bottom of my `C:\Windows\System32\drivers\etc\hosts` file:
> 
> ```
> 192.168.2.116		gamestats.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.gamestats.gs.nintendowifi.net
> 192.168.2.116		gamestats2.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.gamestats2.gs.nintendowifi.net
> 192.168.2.116		gpcm.gs.nintendowifi.net
> 192.168.2.116		gpsp.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.available.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.master.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.ms19.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.natneg1.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.natneg2.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.natneg3.gs.nintendowifi.net
> 192.168.2.116		mariokartwii.sake.gs.nintendowifi.net
> 192.168.2.116		naswii.nintendowifi.net
> 192.168.2.116		mariokartwii.race.gs.nintendowifi.net
> 192.168.2.116		nintendowifi.net
> 192.168.2.116		nas.nintendowifi.net
> 192.168.2.116		dls1.nintendowifi.net
> 192.168.2.116		sake.gs.nintendowifi.net
> ```
> 
> Replace `192.168.2.116` with the IP address of your private server.
> Maybe this will work for melonDS aswell.

Ummmmm... but, if i want to play another online ds game, it still work?
Sorry if my grammar is bad

**Comment by barthogenes** [comment]
I don't know, you would have to try it to find out. I think the DS uses most of the same servers as the Wii so it might work.
Maybe if you replace `mariokartwii` with `mariokartds` it will work with Mario Kart DS for example.
The correct way would be to change the DNS address of your network card in Windows to your private DWC server IP address, but that did not work for me so I used the `C:\Windows\System32\drivers\etc\hosts` file as a workaround.
To try this you can follow the steps from [this video](https://youtu.be/VUoE6R071oo?t=1045) (starts at 17:25).
