### ISSUE TITLE
how to fix error code 20100

### ISSUE THREAD

**Issue by Killzalot** [barronwaffles/dwc_network_server_emulator#549]
Ive tried everything I can think of but keep getting this error.
I followed this video - https://www.youtube.com/watch?v=VUoE6R071oo&t=887s
The only thing I can think of is the dnsmasq config may need changing that the video didnt mention.
I Verified my IP matches dnsmasq.  I changed my settings to the dns of my ethernet adaptor 10. 0 .0. 25.  Ive repatched the game using v3 of wiimfii patcher.  Restarted apache 2 and dnsmasq in Ubuntu.  If anyone can help me fix this I would appreciate it.  Willing to donate as well.  Hit me up on discord killzalot#0541.

**Comment by barthogenes** [comment]
I've got it working by adding the following lines to the bottom of my `C:\Windows\System32\drivers\etc\hosts` file:
```
192.168.2.116		gamestats.gs.nintendowifi.net
192.168.2.116		mariokartwii.gamestats.gs.nintendowifi.net
192.168.2.116		gamestats2.gs.nintendowifi.net
192.168.2.116		mariokartwii.gamestats2.gs.nintendowifi.net
192.168.2.116		gpcm.gs.nintendowifi.net
192.168.2.116		gpsp.gs.nintendowifi.net
192.168.2.116		mariokartwii.available.gs.nintendowifi.net
192.168.2.116		mariokartwii.master.gs.nintendowifi.net
192.168.2.116		mariokartwii.ms19.gs.nintendowifi.net
192.168.2.116		mariokartwii.natneg1.gs.nintendowifi.net
192.168.2.116		mariokartwii.natneg2.gs.nintendowifi.net
192.168.2.116		mariokartwii.natneg3.gs.nintendowifi.net
192.168.2.116		mariokartwii.sake.gs.nintendowifi.net
192.168.2.116		naswii.nintendowifi.net
192.168.2.116		mariokartwii.race.gs.nintendowifi.net
192.168.2.116		nintendowifi.net
192.168.2.116		nas.nintendowifi.net
192.168.2.116		dls1.nintendowifi.net
192.168.2.116		sake.gs.nintendowifi.net
```
Replace `192.168.2.116` with the IP address of your private server.
