### ISSUE TITLE
Communication Error w/ no code

### ISSUE THREAD

**Issue by LucarioRanger** [barronwaffles/dwc_network_server_emulator#550]
I've been trying to do Random Matches on Pokemon Black 2. The problem is, while I can connect just fine to the server, the moment the game has to 'receive data', it just tells me "Communication error..." with no error code. (See picture below)

Any idea what's up? I can use GTS just fine. I haven't been able to find any other people having this issue so is it just me?

![20210519_085132](https://user-images.githubusercontent.com/68386215/118815711-777d7480-b87f-11eb-8f02-32029e1be9a1.jpg)

**Comment by mm201** [comment]
The Random Matchup search uses `mod` as one of its column names, which collides with the `mod` SQL function and causes all kinds of grief for Wiimmfi. Random Matchup never worked on altWFC either, possibly for similar reasons. I filed #162 for it which unfortunately also got staled.

**Comment by sepalani** [comment]
Could you please provide a network dump or eventually give more details about the servers affected. I'll try to have a look at it.
