### ISSUE TITLE
Error Code 60000 when i try to rejoin nintendo wfc on mario kart wii

### ISSUE THREAD

**Issue by Kevin12-1** [barronwaffles/dwc_network_server_emulator#551]
I deleted my nintendo profile from mkwii and it says error code 60000 when i back out and come back in. heres what i mean

https://drive.google.com/file/d/1pJysW90DwUAxb-KAhIzOAgwl6NPjzVD5/view?usp=sharing

the video showing this

**Comment by Kevin12-1** [comment]
Fixed tysm!

**Comment by Kevin12-1** [comment]
incase anyone needed this

https://mkwii.com/showthread.php?tid=1483

**Comment by mm201** [comment]
This is 100% a real, legit bug and shouldn't be staled. Please see the mkwii.com link.
