### ISSUE TITLE
Custom MarioKart Wii mods

### ISSUE THREAD

**Issue by calvinhendriks** [barronwaffles/dwc_network_server_emulator#553]
Nice work on the custom WFC server! I got it to work on a vanilla version of Mario Kart WII.
However, I try to use some custom distribution (custom maps) and it gives me error 23404. Now I know these patchers that belong to these custom distros change the url to wiimmfi.de, but I have setup a web server which forwards these urls to the custom WFC server (this project). If i patch the normal ISO to not use SSL and use the wiimmfi.de domain, it works. 
I know that these mods use something called LE-CODE and I was wondering if this makes it incompatible with the custom server.

**Comment by Leseratte10** [comment]
LE-CODE in its default form is incompatible with servers other than Wiimmfi. You would need to patch the lecode-XXX.bin binary in the game image to disable the built-in Wiimmfi patch, and then run a normal Wiimmfi patcher over the ISO. 
Assuming these mods are running on the latest version of LE-CODE, all you'd need to do is open that binary file in a hex editor, search for `48 00 00 6d 80 01 00 0c` and replace that with `60 00 00 00 80 01 00 0c` which will disable the builtin Wiimmfi patch and makes LE-CODE packs behave like normal Mario Kart Wii with regards to server connections. 

We aren't actively testing if LE-CODE still works properly on non-Wiimmfi servers, but I don't think it has that much special code that would break on AltWFC. Still, we can't give any support for running LE-CODE packs on non-Wiimmfi servers, so if you run into any issues please don't report them to Wiimm, me, or the CT pack author; instead, report them to the custom server creators.

**Comment by calvinhendriks** [comment]
Hey,

Thx for the reply!. So i changed the hex code in the lecode-PAL.bin (i use a pal iso) inside the distros ISO patcher (Variety Pack) and patched a vanilla ISO. I still get the 23404 error :(
Can you tell me what the wiimmfi patcher does exactly? does it only change the domain names? 
And what does changing the hex code do exactly? should I still patch with a wiimmfi patcher after changing the hex code? if so ? why?
Thx a lot for your help!!

**Comment by Leseratte10** [comment]
Patching that code removes all Wiimmfi patches from the LE-CODE. This means you still need to apply normal patches for a custom server - changing HTTPS to HTTP and changing nintendowifi.net to your server's domain.

**Comment by calvinhendriks** [comment]
I wanted to let you know that I got it to work (using the binary swap you suggested). Thx for the help! My friends will also thank you when we have an epic LAN party in a few weeks. Keep up the great work on wiimmfi and mario kart modding in general :)

**Comment by BaltaGamer** [comment]
Hi! So I'm trying to do the hex edit, but can't seem to find any results. I already have my server set up, but 23404 is haunting me. Can anybody give me a step by step reference of what should I do? Thank you! (Also I'm editing lecode-USA.bin with HxD).
