### ISSUE TITLE
Guides to self host on a Raspberry Pi

### ISSUE THREAD

**Issue by vico93** [barronwaffles/dwc_network_server_emulator#555]
Sorry the totally dumb question (i'm zeroed on the subject), but is there any guide to setup & selfhost this server on a Raspberry Pi 3 to private use? Could a RPI handle this for, lets say, 3 or 4 players?

**Comment by studiobram** [comment]
You can find a guide for setting it up on this repo [https://github.com/studiobram/dwc-docker/tree/main](https://github.com/studiobram/dwc-docker/tree/main) and you can find a more advanced version with a vpn in the release/vpn branch. I have tested it on a raspberry pi 2b with 7 people using dolphin and it seemed to work fine
