### ISSUE TITLE
AC:WW support?

### ISSUE THREAD

**Issue by ChimeraUltima** [barronwaffles/dwc_network_server_emulator#88]
I'm curious, will there be server support for Animal Crossing: Wild World at some point in the future? I'm not sure what the limitations are or whether online play in Wild World is server sided or becomes p2p once players establish a connection with each other like some other Wii and DS titles.

**Comment by lpla** [comment]
I'm also interested in this feature, because it is the only game in the list of http://save-nintendo-wifi.com/ which is cooperative and can be connected for hours with other players. Can I help in any way?

**Comment by ghost** [comment]
i can open my gate on my personal AltWFC... And it's p2p by the way
And Wiimmfi has AC:WW DLC
