### ISSUE TITLE
Are servers down/will all versions of every game be working in the future?

### ISSUE THREAD

**Issue by Maganet** [barronwaffles/dwc_network_server_emulator#89]
When I try to connect trhough Pokemon Black I get the 52100. My internet connection is okay, so the servers are down probably. Also I cant connect with my EU English Platinum. Does this version work or will be implemented in the future?

**Comment by mm201** [comment]
The server's been experiencing some downtime lately. Both of those games do work.

**Comment by Kird38** [comment]
I am experiencing the same problem, but I am only trying to get my friend code. it keeps saying I need to be connected to WFC to get my friend code, but I put in all the info this site gave me and the connection test works. My game is Pokemon White. I am also not using an emulator or action replay, is that the problem? What am I doing wrong?

**Comment by Kird38** [comment]
The error code that I have been getting is 20100 and the DNS is plugged in correctly.

**Comment by ghost** [comment]
you have to use an action replay or a patched rom to connect to the server's dns for ds games
