### ISSUE TITLE
Referencing from dwc to pkmn_foundations

### ISSUE THREAD

**Issue by ductator** [barronwaffles/dwc_network_server_emulator#91]
Looking to host my own server for test purposes, how is the above mention connection established?
As far as I have gotten right now, 
gamestats2.gs.nintendowifi.net and pokemondpds.master.gs.nintendowifi.net need to be redirected for me to establish connections to hyper-gts, while few others point to the dwc server
Is the referencing to pkmn foundations done by the dwc server or is this done by DNS server?

**Comment by mm201** [comment]
Please don't. Linking more than one AltWFC server to Pokemon Foundations will cause PID collisions. (Basically, multiple games will "fight" over the same account.)

If it's for development purposes, you should run your own instance of the fGTS as well.

**Comment by ductator** [comment]
That's what I was planning to do, having both services running on private (virtual) servers. Still have to figure out how to compile pkmn-foundations (VS2012 doesn't seem to do the job) properly and getting it to run. Meanwhile I'm trying to find out how the redirect works, as there is no referencing in the .py files I had a look at. Using HyperGTS seems to work fine with DNS rerouting.

**Comment by mm201** [comment]
The altwfc redirect is done in Apache. I don't have the exact configuration but it uses mod_proxy.

On Windows, your best bet is using IIS. (It's an available feature on all Pro versions of Windows since 7.) Create a new web application in an empty folder, add gamestats2.gs.nintendowifi.net as a binding, then use VS's Publish feature to deploy to that folder. It should just work.

**Comment by ductator** [comment]
For now I am using DNS redirect for gamestats2.
But I can't figure out how to properly compile and set up the fGTS Server.
I'm using Server 2012 R2 with fully installed IIS role. Then created a website as you mentioned, published gts from the projectmap via web deploy localhost and I can't even access Default.aspx or RommLeaders.aspx. No point speaking about the gts executable when not even the simple things work out.
I hope you can give me some pointers.

**Comment by mm201** [comment]
I forgot to mention that you also need to prepare the database.
Creating a new MySQL server and running the included database.sql script should work.
You will need to change the database reference in the server's (GTS) `web.config` file to use the correct IP address, username, and password for your MySQL server. 

I'd consider making a tutorial for this, but the intended audience is mainly developers who should be able to figure this stuff out on their own.

If you still have issues, consider filing a bug report in [my bug tracker](https://github.com/mm201/pkmnFoundations/issues) with detailed information and I'll try to help.

Note that the available Pokemon index is likely to raise a `KeyNotFoundException` unless you populate the Pokedex. The website is very much in a WIP state right now with very little in the way of error checking or user friendliness.
