### ISSUE TITLE
Can't t connect to the Internet on dsi roms.

### ISSUE THREAD

**Issue by robbie008** [barronwaffles/dwc_network_server_emulator#98]
Im using a wfc patched rom however my internets encryption(something like that anyway) is not supported on the rom. I have to go into settings to be able to set up a connection. Because I have to set up the connection in system settings this means I can't connect to the server. Can you help me with this problem? Thanks in advance.

**Comment by einstein95** [comment]
As you are using a DS or DS-enhanced ROM, your network settings should be
WEP or unsecured.

**Comment by AdmiralCurtiss** [comment]
Not a problem with this server, DS games just don't support WPA in general.
